# -*- coding: utf-8 -*-
"""
多义项释义补齐脚本（一次性数据工具）
- 对 5 个词库数据文件中 word 类型词条的 cn/chinese 字段做批量替换
- 同一单词在所有教材副本统一为同一份释义
- 仅改释义字符串，不动 en/ph/id → 音频映射与学习进度不受影响
"""
import re
import sys
from collections import defaultdict

sys.stdout.reconfigure(encoding="utf-8")

# 中考大纲式多义项词典：word -> 新释义（原义在前，最多 3~4 个常用义）
ENRICH = {
    # ── 数据纠错（原释义词性/词义明显错误）──
    "gym": "n. 体育馆；健身房",
    "hamburger": "n. 汉堡包",
    "sore": "adj. 疼痛的",
    "tiny": "adj. 极小的；微小的",
    "lead": "v. 引导；带领 n. 领先；铅",
    "bin": "n. 垃圾箱；储物箱",
    "blind": "adj. 失明的 v. 使失明",
    "narrow": "adj. 狭窄的",
    "perfect": "adj. 完美的；极好的 n. （语法）完成时",
    "basic": "adj. 基本的 n. 基础；原理",
    "separate": "adj. 分开的 v. 分开；隔离",
    "seldom": "adv. 很少；不常",
    "very": "adv. 很；非常 adj. 恰好的",
    "soap": "n. 肥皂；（口语）肥皂剧",
    "somebody": "pron. 某人 n. 了不起的人",
    "nobody": "pron. 没有人 n. 无名小卒",
    "none": "pron. 没有一个 adv. 一点也不",
    "ready": "adj. 准备好的",
    "final": "adj. 最后的 n. 决赛；期末考试",
    "primary": "adj. 首要的；初级的",
    "produce": "v. 生产；制造 n. 农产品",
    "next": "adj. 下一个的 adv. 接下来 n. 下一个",
    "least": "adj. 最少的 adv. 最少",
    "main": "adj. 主要的 n. 主要部分",
    "classic": "adj. 经典的 n. 经典作品",
    "beat": "v. 敲打；打败 n. 心跳(声)；节拍",
    "hit": "v. 打；击中 n. 打击；热门作品",
    "click": "v. 点击 n. 咔哒声",
    "mix": "v. 混合 n. 混合物",
    "survive": "v. 幸存；比……活得长",
    "festival": "n. 节日 adj. 节日的",
    "junior": "adj. 年少的 n. 年少者；晚辈",
    "local": "adj. 当地的；本地的",
    "partner": "n. 搭档；伙伴",
    "monitor": "n. 班长；显示器 v. 监控",
    "perform": "v. 表演；执行",
    # ── 常用多义项补齐 ──
    "ability": "n. 能力；才能",
    "able": "adj. 能够的；有能力的",
    "about": "prep. 关于；大约 adv. 大约；四处",
    "above": "prep. 在……上方；超过 adv. 在上面",
    "abroad": "adv. 在国外；到国外",
    "absent": "adj. 缺席的；缺少的",
    "accept": "v. 接受；接纳",
    "account": "n. 账户；账目；描述",
    "act": "v. 行动；表演；扮演 n. 行为；(戏剧的)一幕",
    "action": "n. 行动；行为；作用",
    "active": "adj. 活跃的；积极的",
    "address": "n. 地址；住址 v. 写地址；向……讲话",
    "adult": "n. 成人 adj. 成年的",
    "advantage": "n. 优点；好处；优势",
    "advice": "n. 建议；劝告",
    "advise": "v. 劝告；建议",
    "afford": "v. 买得起；负担得起",
    "afraid": "adj. 害怕的；担心的",
    "after": "prep. 在……之后 conj. 在……以后 adv. 以后",
    "age": "n. 年龄；时代",
    "ahead": "adv. 在前；向前",
    "aid": "n. 帮助；援助 v. 帮助",
    "aim": "n. 目标 v. 瞄准；旨在",
    "air": "n. 空气；空中",
    "all": "adj. 所有的 pron. 全部 adv. 完全",
    "allow": "v. 允许；准许",
    "alone": "adj. 单独的；孤独的 adv. 独自",
    "along": "prep. 沿着 adv. 向前；一起",
    "another": "adj. 另外的 pron. 另一个",
    "anxious": "adj. 焦虑的；渴望的",
    "any": "adj. 任何的 pron. 任何一个",
    "appear": "v. 出现；显得",
    "arm": "n. 手臂 v. 武装",
    "around": "prep. 在……周围；大约 adv. 到处；在附近",
    "arrive": "v. 到达；达到",
    "art": "n. 美术；艺术；文科",
    "article": "n. 文章；冠词；物品",
    "as": "conj. 当……时；因为；虽然 prep. 作为 adv. 同样地",
    "attack": "v. 攻击 n. 攻击；(疾病)发作",
    "attend": "v. 出席；参加；照料",
    "attention": "n. 注意；关心",
    "award": "n. 奖品 v. 授予",
    "available": "adj. 有空的；可用的",
    "away": "adv. 离开；远离；消失",
    "bad": "adj. 坏的；严重的",
    "balance": "n. 平衡；余额",
    "ball": "n. 球；舞会",
    "band": "n. 乐队；带子",
    "bank": "n. 银行；河岸",
    "bargain": "n. 便宜货 v. 讨价还价",
    "bat": "n. 球拍；蝙蝠",
    "behave": "v. 表现；举止端正",
    "believe": "v. 相信；认为",
    "bell": "n. 铃；钟",
    "benefit": "n. 好处 v. 有益于",
    "best": "adj. 最好的 adv. 最好地",
    "better": "adj. 更好的 adv. 更好",
    "bill": "n. 账单；钞票；法案",
    "bit": "n. 少量；一点",
    "bitter": "adj. 苦的；痛苦的",
    "black": "adj. 黑色的 n. 黑色",
    "block": "v. 阻塞 n. 街区；大块",
    "blow": "v. 吹；刮 n. 打击",
    "blue": "adj. 蓝色的；忧郁的 n. 蓝色",
    "body": "n. 身体；主体",
    "book": "n. 书 v. 预订",
    "born": "adj. 天生的 v. 出生（bear 的过去分词）",
    "both": "adj. 两者的 pron. 两者",
    "bow": "v. 鞠躬 n. 弓；蝴蝶结",
    "bright": "adj. 明亮的；聪明的",
    "build": "v. 建造；建立",
    "burn": "v. 烧；燃烧 n. 烧伤",
    "business": "n. 生意；商业；事务",
    "but": "conj. 但是 prep. 除……以外",
    "calculate": "v. 计算；估计",
    "camp": "n. 营地 v. 露营",
    "capital": "n. 首都；资本；大写字母",
    "card": "n. 卡片；纸牌",
    "case": "n. 情况；箱；案例",
    "challenge": "n. 挑战 v. 向……挑战",
    "chance": "n. 机会；可能性",
    "chat": "v. 聊天 n. 闲谈",
    "class": "n. 班级；课；阶级",
    "clear": "adj. 清楚的；晴朗的 v. 清除",
    "club": "n. 俱乐部；社团",
    "coach": "n. 教练；长途汽车",
    "coat": "n. 外套；涂层",
    "collect": "v. 收集；接走",
    "colour": "n. 颜色 v. 涂色",
    "comic": "n. 漫画 adj. 喜剧的",
    "common": "adj. 常见的；共同的",
    "company": "n. 公司；陪伴",
    "compete": "v. 竞争；比赛",
    "condition": "n. 情况；条件",
    "conflict": "n. 冲突 v. 冲突",
    "connect": "v. 连接；联系",
    "control": "v. 控制 n. 控制",
    "correct": "adj. 正确的 v. 改正",
    "could": "aux. 能；可以（can 的过去式）",
    "country": "n. 国家；乡下",
    "course": "n. 课程；过程",
    "cross": "v. 穿过 n. 十字",
    "crowd": "n. 人群 v. 挤满",
    "cup": "n. 杯子；奖杯",
    "cycle": "v. 骑自行车 n. 循环；周期",
    "daily": "adj. 每日的 adv. 每天 n. 日报",
    "dance": "v. 跳舞 n. 舞蹈",
    "dark": "adj. 黑暗的 n. 黑暗",
    "date": "n. 日期；约会",
    "degree": "n. 度；程度；学位",
    "delay": "n. 延误 v. 延误；推迟",
    "desert": "n. 沙漠 v. 抛弃",
    "design": "v. 设计 n. 设计",
    "develop": "v. 发展；发育；冲洗(照片)",
    "diet": "n. 日常饮食；节食",
    "direct": "adj. 直接的 v. 指导；导演",
    "dish": "n. 盘子；菜肴",
    "divide": "v. 分开；除",
    "do": "v. 做 aux. （构成疑问句和否定句的助动词）",
    "doctor": "n. 医生；博士",
    "doubt": "n. 怀疑 v. 怀疑",
    "draw": "v. 画；拉；吸引",
    "dress": "n. 连衣裙 v. 穿衣",
    "drive": "v. 驾驶；驱赶 n. 驾车",
    "dry": "adj. 干燥的 v. 弄干",
    "duty": "n. 责任；职责",
    "each": "adj. 每个 pron. 每个",
    "early": "adj. 早的 adv. 早",
    "earth": "n. 地球；土；陆地",
    "east": "n. 东方 adj. 东方的 adv. 向东",
    "either": "adj. (两者之中)任一的 pron. 任一 adv. 也（用于否定句）",
    "elder": "n. 年长者 adj. 年长的",
    "email": "n. 电子邮件 v. 发电子邮件",
    "end": "n. 结束 v. 结束",
    "energy": "n. 精力；能量",
    "enter": "v. 进入；参加",
    "entrance": "n. 入口；进入",
    "even": "adv. 甚至；更 adj. 平的",
    "event": "n. 事件；比赛项目",
    "ever": "adv. 曾经；究竟",
    "example": "n. 例子；榜样",
    "except": "prep. 除……之外 conj. 只是",
    "exchange": "n. 交流 v. 交换",
    "excuse": "v. 原谅 n. 借口",
    "exit": "n. 出口 v. 退出",
    "expect": "v. 预期；期待",
    "experience": "n. 经历；经验 v. 经历",
    "experiment": "n. 实验 v. 实验",
    "express": "v. 表达 adj. 快速的 n. 快车",
    "face": "n. 脸 v. 面对",
    "fair": "adj. 公平的；晴朗的",
    "false": "adj. 错误的；假的",
    "far": "adj. 远的 adv. 远",
    "farm": "n. 农场 v. 务农",
    "fashion": "n. 时尚；方式",
    "fast": "adj. 快速的 adv. 快",
    "feed": "v. 喂养；饲养",
    "feel": "v. 感觉；摸起来",
    "few": "adj. 很少的 pron. 少数",
    "figure": "n. 数字；人物；身材",
    "film": "n. 电影；胶卷 v. 拍摄",
    "fire": "n. 火；火灾 v. 开火；解雇",
    "first": "num. 第一 adj. 第一的 adv. 首先",
    "fish": "n. 鱼 v. 钓鱼",
    "fix": "v. 修理；固定",
    "flat": "n. 公寓 adj. 平的",
    "floor": "n. 地板；楼层",
    "flood": "n. 洪水 v. 淹没",
    "focus": "n. 焦点 v. 集中",
    "fool": "n. 傻瓜 v. 愚弄",
    "foot": "n. 脚；英尺",
    "force": "n. 力量 v. 强迫",
    "forward": "adj. 向前的 adv. 向前",
    "free": "adj. 自由的；免费的；空闲的",
    "fresh": "adj. 新鲜的；淡的",
    "front": "n. 前面 adj. 前面的",
    "full": "adj. 满的；完全的",
    "fun": "n. 乐趣 adj. 有趣的",
    "funny": "adj. 好笑的；奇怪的",
    "future": "n. 未来 adj. 未来的",
    "get": "v. 得到；到达；变得",
    "gift": "n. 礼物；天赋",
    "giant": "adj. 巨大的 n. 巨人",
    "glass": "n. 玻璃；玻璃杯",
    "go": "v. 去；变得；进行",
    "gold": "n. 金 adj. 金色的",
    "graduate": "n. 毕业生 v. 毕业",
    "green": "adj. 绿色的 n. 绿色",
    "ground": "n. 地面；理由",
    "group": "n. 团体；组 v. 分组",
    "guard": "n. 警卫 v. 保卫",
    "guess": "v. 猜 n. 猜测",
    "half": "n. 一半 adj. 一半的",
    "hall": "n. 大厅；礼堂",
    "hand": "n. 手 v. 递",
    "hard": "adj. 困难的；硬的 adv. 努力地",
    "harm": "n. 伤害 v. 伤害",
    "have": "v. 有；吃；喝 aux. （构成完成时的助动词）",
    "head": "n. 头；领导 v. 前往",
    "hear": "v. 听见；听说",
    "heart": "n. 心脏；中心",
    "help": "v. 帮助 n. 帮助",
    "high": "adj. 高的 adv. 高",
    "hike": "n. 徒步旅行 v. 徒步",
    "hope": "v. 希望 n. 希望",
    "host": "n. 主人；主持人 v. 主办",
    "hot": "adj. 炎热的；辣的",
    "hug": "v. 拥抱 n. 拥抱",
    "human": "n. 人 adj. 人类的",
    "hunt": "v. 打猎；搜寻",
    "in": "prep. 在……里 adv. 进入；在家",
    "increase": "v. 增加 n. 增加",
    "influence": "n. 影响 v. 影响",
    "inside": "n. 内部 adj. 里面的 adv. 在里面 prep. 在……里面",
    "interest": "n. 兴趣；利息 v. 使感兴趣",
    "interview": "n. 采访 v. 采访",
    "jam": "n. 果酱；堵塞",
    "job": "n. 工作；职业",
    "joke": "n. 笑话 v. 开玩笑",
    "judge": "n. 法官 v. 判断",
    "key": "n. 钥匙；键；答案",
    "kid": "n. 小孩 v. 开玩笑",
    "kiss": "v. 亲吻 n. 吻",
    "knock": "v. 敲 n. 敲击",
    "land": "n. 陆地 v. 着陆",
    "late": "adj. 迟的；晚期的 adv. 晚；迟",
    "laugh": "v. 大笑 n. 笑",
    "left": "adj. 左边的 n. 左边 v. 离开（leave 的过去式）",
    "lesson": "n. 课；教训",
    "level": "n. 水平 adj. 平的",
    "life": "n. 生活；生命",
    "likely": "adj. 有可能的 adv. 很可能",
    "list": "n. 目录 v. 列出",
    "little": "adj. 小的 adv. 稍微 pron. 少量",
    "long": "adj. 长的 adv. 长期地",
    "lock": "n. 锁 v. 锁上",
    "lost": "adj. 丢失的；迷路的",
    "lot": "pron. 许多 n. 许多；签",
    "loud": "adj. 大声的 adv. 大声地",
    "mad": "adj. 疯狂的；生气的",
    "magic": "n. 魔术 adj. 有魔力的",
    "many": "adj. 许多的 pron. 许多",
    "march": "n. 三月 v. 行军",
    "marry": "v. 结婚；嫁；娶",
    "master": "n. 主人 v. 掌握",
    "mean": "v. 意思是；意味着 adj. 刻薄的",
    "medicine": "n. 药；医学",
    "medium": "adj. 中等的 n. 媒介",
    "memory": "n. 记忆；回忆；内存",
    "middle": "n. 中间 adj. 中间的",
    "milk": "n. 牛奶 v. 挤奶",
    "million": "num. 百万 n. 百万",
    "mine": "pron. 我的 n. 矿",
    "minute": "n. 分钟；一会儿",
    "mistake": "n. 错误 v. 弄错",
    "mobile": "adj. 移动的 n. 手机",
    "model": "n. 模型；模范",
    "mouse": "n. 老鼠；鼠标",
    "move": "v. 移动；感动 n. 移动",
    "name": "n. 名字 v. 命名",
    "natural": "adj. 自然的；天生的",
    "near": "adj. 近的 prep. 靠近 adv. 附近",
    "need": "v. 需要 n. 需要；需求",
    "neither": "pron. 两者都不 adv. 也不 conj. 也不",
    "note": "n. 笔记；便条；纸币 v. 注意",
    "nothing": "pron. 没有什么 n. 无",
    "novel": "n. 小说 adj. 新奇的",
    "now": "adv. 现在；既然",
    "object": "n. 物体 v. 反对",
    "offer": "v. 提供 n. 提议",
    "officer": "n. 军官；官员",
    "oil": "n. 油；石油",
    "one": "num. 一 pron. 一个",
    "open": "v. 打开 adj. 开着的",
    "operate": "v. 操作；动手术",
    "opposite": "adj. 相反的 n. 反义词 prep. 在……对面",
    "other": "adj. 其他的 pron. 另一个",
    "over": "prep. 在……上方；超过 adv. 结束",
    "pack": "n. 包裹 v. 打包",
    "pain": "n. 疼痛；痛苦",
    "paint": "v. 用颜料画 n. 油漆",
    "paper": "n. 纸；论文；报纸",
    "park": "n. 公园 v. 停车",
    "part": "n. 部分；角色 v. 分离",
    "party": "n. 聚会；政党",
    "passage": "n. 通道；段落",
    "past": "n. 过去 adj. 过去的 prep. 过",
    "patient": "adj. 有耐心的 n. 病人",
    "phone": "n. 电话 v. 打电话",
    "picture": "n. 图片；照片 v. 想象",
    "pity": "n. 遗憾 v. 同情",
    "place": "n. 地方 v. 放置",
    "plan": "n. 计划 v. 计划",
    "plant": "n. 植物 v. 种植",
    "player": "n. 运动员；播放器",
    "please": "adv. 请 v. 使高兴",
    "pink": "adj. 粉红色的 n. 粉红色",
    "point": "v. 指 n. 点；分数；观点",
    "pool": "n. 游泳池；水池",
    "poor": "adj. 贫穷的；差劲的",
    "position": "n. 位置；职位",
    "positive": "adj. 积极的；肯定的",
    "pound": "n. 磅；英镑",
    "practice": "n. 练习 v. 练习",
    "praise": "v. 表扬 n. 表扬",
    "pretty": "adj. 漂亮的 adv. 相当",
    "print": "v. 打印 n. 印刷",
    "process": "v. 处理 n. 过程",
    "program": "n. 节目；程序",
    "progress": "n. 进步 v. 进步",
    "quarrel": "v. 争吵 n. 争吵",
    "quarter": "n. 一刻钟；四分之一",
    "question": "n. 问题 v. 询问",
    "quick": "adj. 快的 adv. 快",
    "rain": "n. 雨 v. 下雨",
    "rather": "adv. 宁可；相当",
    "read": "v. 读；理解",
    "reason": "n. 理由 v. 推理",
    "record": "n. 纪录 v. 录制",
    "refund": "n. 退款 v. 退款",
    "regret": "v. 后悔 n. 后悔",
    "regular": "adj. 规律的；经常的",
    "remain": "v. 保持；留下",
    "repair": "v. 修理 n. 修理",
    "reply": "v. 回复 n. 回复",
    "report": "n. 报告 v. 报告",
    "research": "n. 研究 v. 研究",
    "respect": "n. 尊敬 v. 尊敬",
    "rest": "n. 休息；其余 v. 休息",
    "result": "n. 结果 v. 导致",
    "return": "v. 返回；归还 n. 返回",
    "rich": "adj. 富裕的；丰富的",
    "risk": "n. 风险 v. 冒险",
    "rock": "n. 岩石 v. 摇动",
    "room": "n. 房间；空间",
    "row": "n. 排 v. 划船",
    "rule": "n. 规则；惯例",
    "safe": "adj. 安全的 n. 保险箱",
    "sale": "n. 出售；促销",
    "same": "adj. 相同的 pron. 同样的事物",
    "scare": "v. 使害怕 n. 恐慌",
    "schedule": "n. 日程表 v. 安排",
    "score": "n. 得分 v. 得分",
    "seat": "n. 座位 v. 使就座",
    "second": "num. 第二 n. 秒",
    "secret": "n. 秘密 adj. 秘密的",
    "see": "v. 看见；明白；会见",
    "sense": "n. 感觉；意义 v. 感觉到",
    "serious": "adj. 严肃的；严重的",
    "several": "adj. 几个的 pron. 几个",
    "shake": "v. 摇动 n. 摇动",
    "shape": "n. 形状 v. 塑造",
    "share": "v. 分享 n. 份额",
    "shock": "n. 震惊 v. 使震惊",
    "shoot": "v. 射击；拍摄",
    "shop": "n. 商店 v. 购物",
    "shout": "v. 喊叫 n. 喊叫",
    "sick": "adj. 生病的；恶心的",
    "side": "n. 边；面；一方",
    "silver": "n. 银 adj. 银色的",
    "simple": "adj. 简单的；朴素的",
    "since": "prep. 自……以来 conj. 自……以来；既然 adv. 此后",
    "single": "adj. 单一的；单身的",
    "skate": "v. 滑冰 n. 冰鞋",
    "skip": "v. 跳绳；跳过",
    "sleep": "v. 睡觉 n. 睡眠",
    "slow": "adj. 慢的 v. 减速",
    "smart": "adj. 聪明的；时髦的",
    "smile": "v. 微笑 n. 微笑",
    "smoke": "n. 烟 v. 吸烟",
    "snow": "n. 雪 v. 下雪",
    "soft": "adj. 软的；柔和的",
    "sound": "n. 声音 v. 听起来",
    "speak": "v. 说话；发言",
    "speed": "n. 速度 v. 加速",
    "spend": "v. 花费（钱/时间）；度过",
    "spirit": "n. 精神；情绪",
    "square": "n. 广场 adj. 正方形的",
    "standard": "n. 标准 adj. 标准的",
    "star": "n. 星；明星",
    "station": "n. 车站；台",
    "stay": "v. 停留 n. 逗留",
    "step": "n. 脚步；步骤 v. 踩；踏",
    "still": "adv. 仍然 adj. 静止的",
    "store": "n. 商店 v. 储存",
    "straight": "adj. 直的 adv. 直接地",
    "stress": "n. 压力；重音 v. 强调",
    "subject": "n. 学科；主题；主语",
    "suggest": "v. 建议；暗示",
    "suit": "n. 套装 v. 适合",
    "support": "v. 支持 n. 支持",
    "sure": "adj. 确信的 adv. 当然",
    "surprise": "n. 惊奇 v. 使惊奇",
    "suspect": "n. 嫌疑人 v. 怀疑",
    "sweet": "adj. 甜的 n. 糖果",
    "swim": "v. 游泳 n. 游泳",
    "symbol": "n. 符号；象征",
    "tap": "n. 水龙头 v. 轻拍",
    "tape": "n. 带子；磁带",
    "telephone": "n. 电话 v. 打电话",
    "tell": "v. 告诉；讲述；分辨",
    "term": "n. 学期；术语",
    "terminal": "n. 航站楼；终端",
    "test": "n. 测试 v. 测试",
    "text": "n. 文本 v. 发短信",
    "thank": "v. 感谢 n. 感谢",
    "there": "adv. 那里；在那里",
    "thick": "adj. 厚的；浓的",
    "thin": "adj. 瘦的；薄的",
    "thing": "n. 东西；事情",
    "thought": "n. 想法；思想 v. 想（think 的过去式）",
    "thunder": "n. 雷 v. 打雷",
    "till": "prep. 直到 conj. 直到",
    "time": "n. 时间；次数；时代",
    "tip": "n. 小费；提示 v. 给小费",
    "tonight": "n. 今晚 adv. 今晚",
    "top": "n. 顶部 adj. 最高的",
    "total": "n. 总数 adj. 总的",
    "touch": "v. 触摸 n. 触摸",
    "trade": "n. 贸易 v. 交易",
    "train": "n. 火车 v. 训练",
    "transport": "n. 交通 v. 运输",
    "travel": "v. 旅行 n. 旅行",
    "treasure": "n. 财宝 v. 珍视",
    "trouble": "n. 麻烦 v. 使烦恼",
    "true": "adj. 真实的；忠诚的",
    "trust": "v. 信任 n. 信任",
    "underground": "n. 地铁 adj. 地下的",
    "until": "prep. 直到 conj. 直到",
    "up": "adv. 向上 prep. 向上",
    "upset": "adj. 难过的 v. 使难过",
    "usual": "adj. 平常的",
    "valuable": "adj. 宝贵的；贵重的",
    "value": "n. 价值 v. 重视",
    "volunteer": "n. 志愿者 v. 自愿",
    "vote": "v. 投票 n. 投票",
    "wake": "v. 醒来；唤醒",
    "warm": "adj. 暖和的 v. 加热",
    "wash": "v. 洗 n. 洗",
    "water": "n. 水 v. 浇水",
    "weak": "adj. 虚弱的；薄弱的",
    "welcome": "v. 欢迎 adj. 受欢迎的 n. 欢迎",
    "west": "n. 西方 adj. 西方的",
    "white": "adj. 白色的 n. 白色",
    "whole": "adj. 整个的 n. 全部",
    "wide": "adj. 宽的 adv. 广泛地",
    "wild": "adj. 野生的；狂野的",
    "will": "aux. 将要 n. 意志；遗嘱",
    "wind": "n. 风 v. 绕；缠",
    "witness": "n. 目击者 v. 目击",
    "wonder": "v. 想知道 n. 奇观；惊讶",
    "work": "n. 工作 v. 工作；起作用",
    "worry": "v. 担心 n. 担心",
    "worth": "adj. 值得的 n. 价值",
    "would": "aux. 将（will 的过去式）；愿意",
    "write": "v. 写；写作",
    "wrong": "adj. 错误的 adv. 错误地 n. 错误",
    "yard": "n. 院子；码",
    "zero": "n. 零 num. 零",
}

DATA_DIR = "src/data"
FILES = ["curriculum.ts", "grades4to9.ts", "waiyanshe.ts", "oxford.ts", "kebiaoBank.ts"]

# 外研/牛津：mk("wy", g, u, "word", "en", "ph", "cn")
PAT_PREFIX = re.compile(
    r'(mk\("(?:wy|ox)",\s*\d+,\s*\d+,\s*"word",\s*")([^"]+)(",\s*"[^"]*",\s*")([^"]+)(")'
)
# 人教：mk(g, u, "word", "en", "ph", "cn")
PAT_PLAIN = re.compile(
    r'(mk\(\s*\d+\s*,\s*\d+\s*,\s*"word",\s*")([^"]+)(",\s*"[^"]*",\s*")([^"]+)(")'
)
# 课标库对象：{ en: "...", ph: "...", cn: "..." }
PAT_BANK = re.compile(
    r'(\{\s*en:\s*")([^"]+)(",\s*ph:\s*"[^"]*",\s*cn:\s*")([^"]+)(")'
)

# 先扫一遍：同词在某些文件已含多义项、在别的文件仍是单义 → 统一为最长的多义版本
mixed = defaultdict(set)
for f in FILES:
    src = open(f"{DATA_DIR}/{f}", encoding="utf-8").read()
    for pat in (PAT_PREFIX, PAT_PLAIN):
        for m in pat.finditer(src):
            mixed[m.group(2).lower()].add(m.group(4))
    for m in PAT_BANK.finditer(src):
        mixed[m.group(2).lower()].add(m.group(4))

UNIFY = {}
for w, cns in mixed.items():
    if w in ENRICH:
        continue
    multis = [c for c in cns if "；" in c or (" " in c.strip() and any(p in c for p in (" n.", " v.", " adj.", " adv.", " prep.")))]
    singles = cns - set(multis)
    if multis and singles:
        UNIFY[w] = sorted(multis, key=len)[-1]

TARGETS = dict(ENRICH)
TARGETS.update(UNIFY)

counts = {f: 0 for f in FILES}
skipped_same = 0

def sub_factory(pat, fname):
    def repl(m):
        global skipped_same
        w = m.group(2).lower()
        if w not in TARGETS:
            return m.group(0)
        new = TARGETS[w]
        if m.group(4) == new:
            skipped_same += 1
            return m.group(0)
        counts[fname] += 1
        return m.group(1) + m.group(2) + m.group(3) + new + m.group(5)
    return repl

for f in FILES:
    path = f"{DATA_DIR}/{f}"
    src = open(path, encoding="utf-8").read()
    for pat in (PAT_PREFIX, PAT_PLAIN, PAT_BANK):
        src = pat.sub(sub_factory(pat, f), src)
    open(path, "w", encoding="utf-8", newline="\n").write(src)

print("词典词条数:", len(ENRICH), "| 混合统一词条数:", len(UNIFY))
print("各文件替换条数:", counts, "| 已是目标释义跳过:", skipped_same)
print("混合统一词列表:", sorted(UNIFY.keys()))
