#!/usr/bin/env node
/**
 * scripts/intake_curriculum.mjs
 * 「waiyanshe G1G2 / oxford 重建」智能录入器
 *
 * 用户拍教材内页后，用 iPad"实况文本"功能复制每个词条，
 * 粘贴到 stdin 每行一个词条：
 *
 *   1|hello|/həˈləʊ/|int. 喂；你好
 *   1|hi|/haɪ/|int. 喂；你好
 *   1|good morning||早上好
 *   2|stand|/stænd/|v. 站
 *
 * 第 1 列是必填的 grade|unit（默认 = 上一次，留空继续上一组）
 * 第 2 列是英文词条（必填）
 * 第 3 列是音标（可空 → 留待音频脚本后补）
 * 第 4 列是中文释义（可空）
 *
 * --curriculum wy：waiyanshe 一起线（G1G2 用）
 * --curriculum ox：oxford 一起线（整线）
 *
 * --preview：只解析 + 预览，不写到文件（默认）
 * --apply：导出 TS 代码块（等待用户确认后再 Edit curriculum.ts）
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// === 词条工厂（与 src/data/kebiaoBank.ts 保持一致）===
const prefixSeqs = new Map();
function mkEntry(prefix, grade, unit, type, en, ph, cn) {
  const n = (prefixSeqs.get(prefix) ?? 0) + 1;
  prefixSeqs.set(prefix, n);
  return {
    id: `${prefix}-g${grade}u${unit}e${String(n).padStart(4, "0")}`,
    grade, unit, type, english: en, phonetic: ph, chinese: cn,
  };
}

const argv = process.argv.slice(2);
const curriculumKey = argv.includes("--curriculum")
  ? argv[argv.indexOf("--curriculum") + 1]
  : "wy";
const isApply = argv.includes("--apply");
const bookLabel = argv.includes("--book")
  ? argv[argv.indexOf("--book") + 1]
  : "";

const PREFIX = { wy: "wy", ox: "ox", rj: "rj" }[curriculumKey] || curriculumKey;

// === 读 stdin ===
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => (input += chunk));
process.stdin.on("end", parse);

function parse() {
  if (!input.trim()) {
    console.error("用法：先拍教材内页 → iPad 复制文本 → 粘到 stdin");
    console.error(
      "  每行：grade|unit|english|ipa|chinese 或简写：unit|english|ipa|chinese"
    );
    process.exit(1);
  }

  const lines = input.split(/\r?\n/).filter((l) => l.trim() && !l.trim().startsWith("#"));
  const entries = [];
  let lastGU = null;

  for (const line of lines) {
    const cells = line.split("|").map((c) => c.trim());
    let g, u, en, ph = "", cn = "";
    if (cells.length >= 5) {
      [g, u, en, ph, cn] = cells;
    } else if (cells.length === 4) {
      [u, en, ph, cn] = cells;
    } else if (cells.length === 3) {
      [u, en, cn] = cells;
    } else if (cells.length === 2) {
      [u, en] = cells;
    } else {
      console.error(`⚠️ 跳过：格式无法识别 "${line}"`);
      continue;
    }

    if (!g) g = lastGU?.g ?? 1;
    if (!u) u = lastGU?.u ?? 1;
    g = Number(g); u = Number(u);
    if (!en) {
      console.error(`⚠️ 跳过：缺英文 "${line}"`);
      continue;
    }
    lastGU = { g, u };
    const type = en.includes(" ") ? "phrase" : "word";
    entries.push(mkEntry(PREFIX, g, u, type, en, ph, cn));
  }

  // 汇总 + 按 (g,u) 分组
  const grouped = new Map();
  for (const e of entries) {
    const k = `G${e.grade}U${e.unit}`;
    if (!grouped.has(k)) grouped.set(k, []);
    grouped.get(k).push(e);
  }

  console.log(`\n=== 解析结果（${entries.length} 条词条 / ${grouped.size} 个 Unit） ===`);
  for (const [k, arr] of [...grouped.entries()].sort((a, b) => {
    const ag = a[0], bg = b[0];
    return ag < bg ? -1 : ag > bg ? 1 : 0;
  })) {
    console.log(`\n[${k}]  ${arr.length} 条`);
    for (const e of arr.slice(0, 3)) {
      console.log(`  ${e.english}${e.phonetic ? " /" + e.phonetic + "/" : ""}${e.chinese ? " — " + e.chinese : ""}`);
    }
    if (arr.length > 3) console.log(`  ... 等共 ${arr.length} 条`);
  }

  // 导出 TS 代码块
  const tsLines = [
    `// generated by scripts/intake_curriculum.mjs at ${new Date().toISOString()}`,
    `// curriculum: ${curriculumKey} | prefix: ${PREFIX} | book: ${bookLabel}`,
    ``,
  ];
  for (const [, arr] of grouped) {
    for (const e of arr) {
      tsLines.push(
        `      mk("${PREFIX}", ${e.grade}, ${e.unit}, "${e.type}", ${JSON.stringify(e.english)}, ${JSON.stringify(e.phonetic)}, ${JSON.stringify(e.chinese)}),`
      );
    }
  }

  if (isApply) {
    const outPath = join(ROOT, "src", "data", `_intake_${PREFIX}_${Date.now()}.ts`);
    writeFileSync(outPath, tsLines.join("\n") + "\n", "utf8");
    console.log(`\n✅ 已写出：${outPath}`);
    console.log(`\n📋 待你手动合并到 curriculum.ts / waiyanshe.ts / oxford.ts 相应 Unit 段。`);
  } else {
    console.log(`\n--- 预览（--apply 才会写入）---`);
    console.log(tsLines.join("\n"));
  }
}
