// patch_g9_full.mjs
// ====================================================================
// PEP 九年级（旧版全一册）整段重做：把 G9 段（U1-U12 精简版）替换为
// U1-U14 完整版（PEP Go for it! 2014 旧版，按用户 2026-09-05 截图）。
//
// 历史踩坑（务必遵守 patch_unit_template.mjs 列出 5 条）：
//   - G9 是文件最末段，没有「下段起点」可作 OLD_END_MARK，
//     所以用 `\n];\n`（文件唯一）作为 OLD_END_MARK。
//   - after = text.slice(endIdx + OLD_END_MARK.length) 必须 + len
//   - NEW_BLOCK 末尾自带最后一个 unit 的 `\n  },\n`，与 OLD_END_MARK `\n];\n` 衔接
//
// 使用：node scripts/patch_g9_full.mjs → tsc → dump → build
// ====================================================================

import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const TARGET = path.resolve(__filename, '../../src/data/grades4to9.ts');
const text = fs.readFileSync(TARGET, 'utf8');

// ===== 1. OLD_START_MARK / OLD_END_MARK =====
const OLD_START_MARK = `  // ==================== 九年级（Go for it 全一册 U1-12） ====================
  {
    grade: 9,
    unit: 1,
    title: "How can we become good learners 学习方法",
    entries: [
`;
const OLD_END_MARK = `];
`;

const startIdx = text.indexOf(OLD_START_MARK);
if (startIdx < 0) { console.error('❌ OLD_START_MARK 未找到'); process.exit(1); }
const endIdx = text.indexOf(OLD_END_MARK, startIdx);
if (endIdx < 0) { console.error('❌ OLD_END_MARK 未找到'); process.exit(1); }

// ===== 2. mk() 辅助（中文/单引号/特殊字符必须 JSON.stringify）=====
const m = (g, u, type, en, ph, cn) =>
  `      mk(${g}, ${u}, ${JSON.stringify(type)}, ${JSON.stringify(en)}, ${JSON.stringify(ph)}, ${JSON.stringify(cn)}),`;

// ===== 3. block() 单元模板 =====
const block = (n, title, body) => `  {
    grade: 9,
    unit: ${n},
    title: ${JSON.stringify(title)},
    entries: [
${body}
    ],
  },
`;

// ===== 4. U1-U14 词条（按 2026-09-05 用户截图教材原词 + Recycling + Useful expressions）=====

// -------- U1: How can we become good learners? (Learning how to learn) --------
const U1 = [
  m(9, 1, 'word', 'textbook', '/ˈtekstbʊk/', 'n. 教科书；课本'),
  m(9, 1, 'word', 'conversation', '/ˌkɑːnvərˈseɪʃn/', 'n. 交谈；谈话'),
  m(9, 1, 'word', 'aloud', '/əˈlaʊd/', 'adv. 大声地；出声地'),
  m(9, 1, 'word', 'pronunciation', '/prəˌnʌnsiˈeɪʃn/', 'n. 发音；读音'),
  m(9, 1, 'word', 'secret', '/ˈsiːkrət/', 'n. 秘密；秘诀 adj. 秘密的；保密的'),
  m(9, 1, 'word', 'grammar', '/ˈɡræmər/', 'n. 语法'),
  m(9, 1, 'word', 'sentence', '/ˈsentəns/', 'n. 句子'),
  m(9, 1, 'word', 'patient', '/ˈpeɪʃnt/', 'adj. 有耐心的 n. 病人'),
  m(9, 1, 'word', 'expression', '/ɪkˈspreʃn/', 'n. 表情；表示；表达方式'),
  m(9, 1, 'word', 'discover', '/dɪˈskʌvər/', 'v. 发现；发觉'),
  m(9, 1, 'word', 'look up', '/lʊk ʌp/', '（在词典、参考书中或通过电脑）查阅；抬头看'),
  m(9, 1, 'word', 'repeat', '/rɪˈpiːt/', 'v. 重复；重做'),
  m(9, 1, 'word', 'note', '/noʊt/', 'n. 笔记；记录 v. 注意；指出'),
  m(9, 1, 'word', 'pal', '/pæl/', 'n. 朋友；伙伴'),
  m(9, 1, 'word', 'physics', '/ˈfɪzɪks/', 'n. 物理；物理学'),
  m(9, 1, 'word', 'chemistry', '/ˈkemɪstri/', 'n. 化学'),
  m(9, 1, 'word', 'memorize', '/ˈmeməraɪz/', 'v. 记忆；记住'),
  m(9, 1, 'word', 'pattern', '/ˈpætərn/', 'n. 模式；方式'),
  m(9, 1, 'word', 'pronounce', '/prəˈnaʊns/', 'v. 发音'),
  m(9, 1, 'word', 'increase', '/ɪnˈkriːs/', 'v. 增加；增长'),
  m(9, 1, 'word', 'speed', '/spiːd/', 'n. 速度'),
  m(9, 1, 'word', 'review', '/rɪˈvjuː/', 'v. & n. 回顾；复习'),
  m(9, 1, 'word', 'partner', '/ˈpɑːrtnər/', 'n. 搭档；同伴'),
  m(9, 1, 'word', 'born', '/bɔːrn/', 'v. 出生 adj. 天生的'),
  m(9, 1, 'word', 'ability', '/əˈbɪləti/', 'n. 能力；才能'),
  m(9, 1, 'word', 'create', '/kriˈeɪt/', 'v. 创造；创建'),
  m(9, 1, 'word', 'brain', '/breɪn/', 'n. 大脑'),
  m(9, 1, 'word', 'active', '/ˈæktɪv/', 'adj. 活跃的；积极的'),
  m(9, 1, 'word', 'attention', '/əˈtenʃn/', 'n. 注意；关注'),
  m(9, 1, 'word', 'knowledge', '/ˈnɑːlɪdʒ/', 'n. 知识；学问'),
  m(9, 1, 'word', 'overnight', '/ˌoʊvərˈnaɪt/', 'adv. 一夜之间；在夜间'),
  m(9, 1, 'word', 'lifelong', '/ˈlaɪflɔːŋ/', 'adj. 终身的；毕生的'),
  m(9, 1, 'word', 'wisely', '/ˈwaɪzli/', 'adv. 明智地；聪明地'),
  m(9, 1, 'phrase', 'pay attention to', '/peɪ əˈtenʃn tuː/', '注意'),
  m(9, 1, 'phrase', 'connect ... with', '/kəˈnekt wɪð/', '把……和……连接或联系起来'),
  m(9, 1, 'phrase', 'be good at', '/biː ɡʊd æt/', '擅长'),
  m(9, 1, 'phrase', 'be interested in', '/biː ˈɪntrəstɪd ɪn/', '对…感兴趣'),
  m(9, 1, 'phrase', 'find out', '/faɪnd aʊt/', '找出；查明'),
  m(9, 1, 'phrase', 'learn from', '/lɜːrn frɒm/', '向…学习'),
  m(9, 1, 'sentence', 'How can we become good learners?', '', '我们怎样才能成为好的学习者？'),
  m(9, 1, 'sentence', 'I learn by studying with a group.', '', '我通过小组合作学习。'),
  m(9, 1, 'sentence', 'Do you learn English by reading aloud?', '', '你是通过大声读来学英语的吗？'),
  m(9, 1, 'sentence', 'Yes, I do. It helps my pronunciation.', '', '是的。它帮助我的发音。'),
  m(9, 1, 'sentence', 'How can I read faster?', '', '我怎样才能读得更快？'),
  m(9, 1, 'sentence', 'You can read faster by reading word groups.', '', '你可以通过读词组来读得更快。'),
  m(9, 1, 'sentence', 'How can I improve my pronunciation?', '', '我怎样才能改进我的发音？'),
  m(9, 1, 'sentence', 'One way is by listening to tapes.', '', '一个方法是听磁带。'),
].join('\n');

// -------- U2: I think that mooncakes are delicious! (Festivals) --------
const U2 = [
  m(9, 2, 'word', 'mooncake', '/ˈmuːnkeɪk/', 'n. 月饼'),
  m(9, 2, 'word', 'lantern', '/ˈlæntərn/', 'n. 灯笼'),
  m(9, 2, 'word', 'stranger', '/ˈstreɪndʒər/', 'n. 陌生人'),
  m(9, 2, 'word', 'relative', '/ˈrelətɪv/', 'n. 亲属；亲戚'),
  m(9, 2, 'word', 'folk', '/foʊk/', 'adj. 民间的；民俗的'),
  m(9, 2, 'word', 'goddess', '/ˈɡɑːdəs/', 'n. 女神'),
  m(9, 2, 'word', 'whoever', '/huːˈevər/', 'pron. 无论谁；不管什么人'),
  m(9, 2, 'word', 'steal', '/stiːl/', 'v. (stole/stəʊl/, stolen/ˈstəʊlən/) 偷；窃取'),
  m(9, 2, 'word', 'lay', '/leɪ/', 'v. (laid/leɪd/, laid) 放置；安放；产（卵）；下（蛋）'),
  m(9, 2, 'word', 'dessert', '/dɪˈzɜːrt/', 'n. （饭后）甜点；甜食'),
  m(9, 2, 'word', 'garden', '/ˈɡɑːrdn/', 'n. 花园；果园'),
  m(9, 2, 'word', 'tradition', '/trəˈdɪʃn/', 'n. 传统'),
  m(9, 2, 'word', 'admire', '/ədˈmaɪər/', 'v. 欣赏；仰慕'),
  m(9, 2, 'word', 'treat', '/triːt/', 'n. 款待；招待 v. 招待；请（客）'),
  m(9, 2, 'word', 'tie', '/taɪ/', 'n. 领带 v. 捆；束'),
  m(9, 2, 'word', 'dinosaur', '/ˈdaɪnəsɔːr/', 'n. 恐龙'),
  m(9, 2, 'word', 'mushroom', '/ˈmʌʃruːm/', 'n. 蘑菇'),
  m(9, 2, 'word', 'togetherness', '/təˈɡeðərnəs/', 'n. 和睦相处；亲密无间'),
  m(9, 2, 'word', 'happiness', '/ˈhæpinəs/', 'n. 快乐；高兴'),
  m(9, 2, 'word', 'lunar', '/ˈluːnər/', 'adj. 月球的；月亮的'),
  m(9, 2, 'word', 'riddle', '/ˈrɪdl/', 'n. 谜；谜语'),
  m(9, 2, 'word', 'celebration', '/ˌselɪˈbreɪʃn/', 'n. 庆典；庆祝活动'),
  m(9, 2, 'word', 'firework', '/ˈfaɪərwɜːrk/', 'n. 烟火；烟花 (pl.) 烟花表演'),
  m(9, 2, 'word', 'gather', '/ˈɡæðər/', 'v. 聚集；集合'),
  m(9, 2, 'word', 'suggest', '/səˈdʒest/', 'v. 建议；提议'),
  m(9, 2, 'word', 'custom', '/ˈkʌstəm/', 'n. 风俗；习俗'),
  m(9, 2, 'word', 'involve', '/ɪnˈvɑːlv/', 'v. 包含；牵涉'),
  m(9, 2, 'word', 'crowd', '/kraʊd/', 'n. 人群；观众'),
  m(9, 2, 'word', 'bottom', '/ˈbɑːtəm/', 'n. 底部；最下部'),
  m(9, 2, 'word', 'dust', '/dʌst/', 'n. 尘土；尘土 v. 掸去'),
  m(9, 2, 'word', 'couplet', '/ˈkʌplət/', 'n. 对联；对句'),
  m(9, 2, 'word', 'eve', '/iːv/', 'n. 前夕；前夜'),
  m(9, 2, 'word', 'express', '/ɪkˈspres/', 'v. 表达；表示'),
  m(9, 2, 'word', 'reunion', '/ˌriːˈjuːniən/', 'n. 团聚；团圆'),
  m(9, 2, 'word', 'mark', '/mɑːrk/', 'v. 标志；做标记 n. 迹象；记号；分数'),
  m(9, 2, 'word', 'smell', '/smel/', 'v. (smelt/smelt/, smelled/smeld/) 闻；发出…气味 n. 气味；臭味'),
  m(9, 2, 'word', 'breeze', '/briːz/', 'n. 微风；和风'),
  m(9, 2, 'word', 'picnic', '/ˈpɪknɪk/', 'n. & v. 野餐'),
  m(9, 2, 'word', 'coming', '/ˈkʌmɪŋ/', 'adj. 即将发生的；下一个的 n. 到来'),
  m(9, 2, 'word', 'Egypt', '/ˈiːdʒɪpt/', 'n. 埃及'),
  m(9, 2, 'word', 'Scottish', '/ˈskɑːtɪʃ/', 'adj. 苏格兰的；苏格兰人的'),
  m(9, 2, 'phrase', 'put on', '/pʊt ɒn/', '增加（体重）；发胖'),
  m(9, 2, 'phrase', 'lay out', '/leɪ aʊt/', '摆开；布置'),
  m(9, 2, 'phrase', 'take place', '/teɪk pleɪs/', '发生'),
  m(9, 2, 'phrase', 'count down', '/kaʊnt daʊn/', '倒计时'),
  m(9, 2, 'phrase', 'set off', '/set ɒf/', '点燃；使…爆炸'),
  m(9, 2, 'phrase', 'in person', '/ɪn ˈpɜːrsn/', '亲自'),
  m(9, 2, 'phrase', 'be similar to', '/biː ˈsɪmɪlər tuː/', '与…相似'),
  m(9, 2, 'phrase', 'Mid-Autumn Festival', '/ˌmɪdˈɔːtəm ˈfestɪvl/', '中秋节'),
  m(9, 2, 'phrase', 'Water Festival', '/ˈwɔːtər ˈfestɪvl/', '泼水节'),
  m(9, 2, 'phrase', 'Mother\u2019s Day', '/ˈmʌðərz deɪ/', '母亲节'),
  m(9, 2, 'phrase', 'Father\u2019s Day', '/ˈfɑːðərz deɪ/', '父亲节'),
  m(9, 2, 'phrase', 'Spring Festival', '/sprɪŋ ˈfestɪvl/', '春节'),
  m(9, 2, 'phrase', 'Auld Lang Syne', '/ˌɔːld læŋ ˈsaɪn/', '《友谊地久天长》'),
  m(9, 2, 'sentence', 'I think that mooncakes are delicious!', '', '我认为月饼很好吃！'),
  m(9, 2, 'sentence', 'I wonder if they\u2019ll have the races again next year.', '', '我想知道明年他们是否会再举办比赛。'),
  m(9, 2, 'sentence', 'I wonder whether June is a good time to visit Hong Kong.', '', '我想知道六月是不是去香港的好时候。'),
  m(9, 2, 'sentence', 'I believe that April is the hottest month in Thailand.', '', '我相信四月是泰国最热的月份。'),
  m(9, 2, 'sentence', 'What fun the Water Festival is!', '', '泼水节多么有趣啊！'),
  m(9, 2, 'sentence', 'How pretty the dragon boats were!', '', '龙舟多漂亮啊！'),
].join('\n');

// -------- U3: Could you please tell me where the restrooms are? (Getting around) --------
const U3 = [
  m(9, 3, 'word', 'restroom', '/ˈrestruːm/', 'n. (美) 洗手间；公共厕所'),
  m(9, 3, 'word', 'stamp', '/stæmp/', 'n. 邮票；印章'),
  m(9, 3, 'word', 'bookstore', '/ˈbʊkstɔːr/', 'n. 书店'),
  m(9, 3, 'word', 'beside', '/bɪˈsaɪd/', 'prep. 在…旁边；在…附近'),
  m(9, 3, 'word', 'postcard', '/ˈpoʊstkɑːrd/', 'n. 明信片'),
  m(9, 3, 'word', 'pardon', '/ˈpɑːrdn/', 'v. 原谅 interj. 请再说一遍'),
  m(9, 3, 'word', 'washroom', '/ˈwɑːʃruːm/', 'n. 洗手间；厕所'),
  m(9, 3, 'word', 'bathroom', '/ˈbæθruːm/', 'n. 浴室；洗手间'),
  m(9, 3, 'word', 'normally', '/ˈnɔːrməli/', 'adv. 通常；正常情况下'),
  m(9, 3, 'word', 'rush', '/rʌʃ/', 'v. & n. 仓促；急促'),
  m(9, 3, 'word', 'pass by', '/pæs baɪ/', '路过；经过'),
  m(9, 3, 'word', 'staff', '/stæf/', 'n. 管理人员；职工'),
  m(9, 3, 'word', 'grape', '/ɡreɪp/', 'n. 葡萄'),
  m(9, 3, 'word', 'policeman', '/pəˈliːsmən/', 'n. (pl. policemen) 男警察'),
  m(9, 3, 'word', 'central', '/ˈsentrəl/', 'adj. 中心的；中央的'),
  m(9, 3, 'word', 'nearby', '/ˌnɪrˈbaɪ/', 'adj. 附近的；邻近的 adv. 在附近'),
  m(9, 3, 'word', 'mail', '/meɪl/', 'v. 邮寄；发电子邮件 n. 邮件；信件'),
  m(9, 3, 'word', 'east', '/iːst/', 'adv. 向东；朝东 adj. 东方的；东部的 n. 东；东方'),
  m(9, 3, 'word', 'fascinating', '/ˈfæsɪneɪtɪŋ/', 'adj. 迷人的；极有吸引力的'),
  m(9, 3, 'word', 'inexpensive', '/ˌɪnɪkˈspensɪv/', 'adj. 不昂贵的'),
  m(9, 3, 'word', 'uncrowded', '/ʌnˈkraʊdɪd/', 'adj. 不拥挤的；人少的'),
  m(9, 3, 'word', 'convenient', '/kənˈviːniənt/', 'adj. 便利的；方便的'),
  m(9, 3, 'word', 'mall', '/mɔːl/', 'n. 商场；购物中心'),
  m(9, 3, 'word', 'clerk', '/klɜːrk/', 'n. 职员'),
  m(9, 3, 'word', 'corner', '/ˈkɔːrnər/', 'n. 拐角；角落'),
  m(9, 3, 'word', 'politely', '/pəˈlaɪtli/', 'adv. 礼貌地；客气地'),
  m(9, 3, 'word', 'request', '/rɪˈkwest/', 'n. & v. 要求；请求'),
  m(9, 3, 'word', 'direction', '/dəˈrekʃn/', 'n. 方向；方位'),
  m(9, 3, 'word', 'correct', '/kəˈrekt/', 'adj. 正确的；恰当的'),
  m(9, 3, 'word', 'polite', '/pəˈlaɪt/', 'adj. 有礼貌的；客气的'),
  m(9, 3, 'word', 'direct', '/dəˈrekt/', 'adj. 直接的；直率的'),
  m(9, 3, 'word', 'speaker', '/ˈspiːkər/', 'n. 讲（某种语言）的人；发言者'),
  m(9, 3, 'word', 'whom', '/huːm/', 'pron. 谁；什么人'),
  m(9, 3, 'word', 'impolite', '/ˌɪmpəˈlaɪt/', 'adj. 不礼貌的；粗鲁的'),
  m(9, 3, 'word', 'address', '/əˈdres/', 'n. 住址；地址；通讯处'),
  m(9, 3, 'word', 'underground', '/ˈʌndərɡraʊnd/', 'adj. 地下的 n. 地铁'),
  m(9, 3, 'word', 'parking lot', '/ˈpɑːrkɪŋ lɒt/', '停车场；停车区'),
  m(9, 3, 'word', 'course', '/kɔːrs/', 'n. 课程；学科'),
  m(9, 3, 'word', 'Italian', '/ɪˈtæliən/', 'adj. 意大利的；意大利人的；n. 意大利人；意大利语'),
  m(9, 3, 'phrase', 'pardon me', '/ˈpɑːrdn miː/', '抱歉，对不起；什么，请再说一遍'),
  m(9, 3, 'sentence', 'Excuse me, do you know where I can buy some medicine?', '', '打扰一下，你知道我在哪里能买到药吗？'),
  m(9, 3, 'sentence', 'Sure. There\u2019s a supermarket down the street.', '', '当然。沿这条街走下去有一个超市。'),
  m(9, 3, 'sentence', 'Could you please tell me how to get to the post office?', '', '你能告诉我怎样去邮局吗？'),
  m(9, 3, 'sentence', 'Sorry, I\u2019m not sure how to get there.', '', '抱歉，我不确定怎么去那里。'),
  m(9, 3, 'sentence', 'I wonder where we should go next.', '', '我想知道我们下一步该去哪里。'),
  m(9, 3, 'sentence', 'You should try that new ride over there.', '', '你应该试试那边那个新项目。'),
].join('\n');

// -------- U4: I used to be afraid of the dark. (How we have changed) --------
const U4 = [
  m(9, 4, 'word', 'humorous', '/ˈhjuːmərəs/', 'adj. 有幽默感的；滑稽有趣的'),
  m(9, 4, 'word', 'silent', '/ˈsaɪlənt/', 'adj. 不说话的；沉默的'),
  m(9, 4, 'word', 'helpful', '/ˈhelpfl/', 'adj. 有用的；有帮助的'),
  m(9, 4, 'word', 'from time to time', '/frɒm taɪm tuː taɪm/', '时常；有时'),
  m(9, 4, 'word', 'score', '/skɔːr/', 'n. & v. 得分；进球'),
  m(9, 4, 'word', 'background', '/ˈbækɡraʊnd/', 'n. 背景'),
  m(9, 4, 'word', 'interview', '/ˈɪntərvjuː/', 'n. 面试；访谈 v. 采访'),
  m(9, 4, 'word', 'Asian', '/ˈeɪʒn/', 'adj. 亚洲（人）的 n. 亚洲人'),
  m(9, 4, 'word', 'deal', '/diːl/', 'v. (dealt/delt/, dealt) 对付；对待；处理'),
  m(9, 4, 'word', 'shyness', '/ˈʃaɪnəs/', 'n. 害羞；腼腆'),
  m(9, 4, 'word', 'dare', '/der/', 'v. 敢于；胆敢'),
  m(9, 4, 'word', 'ton', '/tʌn/', 'n. 吨；(pl.) 大量；许多'),
  m(9, 4, 'word', 'private', '/ˈpraɪvət/', 'adj. 私人的；私密的'),
  m(9, 4, 'word', 'guard', '/ɡɑːrd/', 'n. 警卫；看守 v. 守卫；保卫'),
  m(9, 4, 'word', 'require', '/rɪˈkwaɪər/', 'v. 需要；要求'),
  m(9, 4, 'word', 'European', '/ˌjʊərəˈpiːən/', 'adj. 欧洲（人）的 n. 欧洲人'),
  m(9, 4, 'word', 'African', '/ˈæfrɪkən/', 'adj. 非洲（人）的 n. 非洲人'),
  m(9, 4, 'word', 'British', '/ˈbrɪtɪʃ/', 'adj. 英国（人）的'),
  m(9, 4, 'word', 'insect', '/ˈɪnsekt/', 'n. 昆虫'),
  m(9, 4, 'word', 'ant', '/ænt/', 'n. 蚂蚁'),
  m(9, 4, 'word', 'speech', '/spiːtʃ/', 'n. 讲话；发言'),
  m(9, 4, 'word', 'public', '/ˈpʌblɪk/', 'n. 民众 adj. 公开的；公众的'),
  m(9, 4, 'word', 'spider', '/ˈspaɪdər/', 'n. 蜘蛛'),
  m(9, 4, 'word', 'seldom', '/ˈseldəm/', 'adv. 不常；很少'),
  m(9, 4, 'word', 'influence', '/ˈɪnfluəns/', 'v. & n. 影响'),
  m(9, 4, 'word', 'absent', '/ˈæbsənt/', 'adj. 缺席；不在'),
  m(9, 4, 'word', 'fail', '/feɪl/', 'v. 不及格；失败；未能（做到）'),
  m(9, 4, 'word', 'examination', '/ɪɡˌzæmɪˈneɪʃn/', 'n. 考试；审查'),
  m(9, 4, 'word', 'boarding school', '/ˈbɔːrdɪŋ skuːl/', '寄宿学校'),
  m(9, 4, 'word', 'in person', '/ɪn ˈpɜːrsn/', '亲自'),
  m(9, 4, 'word', 'exactly', '/ɪɡˈzæktli/', 'adv. 确切地；精确地'),
  m(9, 4, 'word', 'pride', '/praɪd/', 'n. 自豪；骄傲'),
  m(9, 4, 'word', 'proud', '/praʊd/', 'adj. 自豪的；骄傲的'),
  m(9, 4, 'word', 'general', '/ˈdʒenrəl/', 'adj. 总的；普遍的；常规的 n. 将军'),
  m(9, 4, 'word', 'introduction', '/ˌɪntrəˈdʌkʃn/', 'n. 介绍'),
  m(9, 4, 'phrase', 'in public', '/ɪn ˈpʌblɪk/', '公开地；在别人（尤指生人）面前'),
  m(9, 4, 'phrase', 'deal with', '/diːl wɪð/', '应对；处理'),
  m(9, 4, 'phrase', 'take pride in', '/teɪk praɪd ɪn/', '为…感到自豪'),
  m(9, 4, 'phrase', 'be proud of', '/biː praʊd ɒv/', '为…骄傲；感到自豪'),
  m(9, 4, 'sentence', 'I used to be short.', '', '我过去个子矮。'),
  m(9, 4, 'sentence', 'I didn\u2019t use to be popular in school.', '', '我过去在学校里不受欢迎。'),
  m(9, 4, 'sentence', 'You used to be short, didn\u2019t you?', '', '你过去个子矮，是吗？'),
  m(9, 4, 'sentence', 'Yes, I did. / No, I didn\u2019t.', '', '是的，我是。/ 不，我不是。'),
  m(9, 4, 'sentence', 'Did he use to wear glasses?', '', '他过去戴眼镜吗？'),
  m(9, 4, 'sentence', 'Yes, he did. / No, he didn\u2019t.', '', '是的，他戴过。/ 不，他没有。'),
].join('\n');

// -------- U5: What are the shirts made of? (Things made in China) --------
const U5 = [
  m(9, 5, 'word', 'chopstick', '/ˈtʃɑːpstɪk/', 'n. 筷子'),
  m(9, 5, 'word', 'coin', '/kɔɪn/', 'n. 硬币'),
  m(9, 5, 'word', 'fork', '/fɔːrk/', 'n. 餐叉；叉子'),
  m(9, 5, 'word', 'blouse', '/blaʊz/', 'n. 女式短上衣；衬衫'),
  m(9, 5, 'word', 'silver', '/ˈsɪlvər/', 'n. 银 adj. 银色的'),
  m(9, 5, 'word', 'glass', '/ɡlæs/', 'n. 玻璃'),
  m(9, 5, 'word', 'cotton', '/ˈkɑːtn/', 'n. 棉；棉花'),
  m(9, 5, 'word', 'steel', '/stiːl/', 'n. 钢；钢铁'),
  m(9, 5, 'word', 'fair', '/fer/', 'n. 展览会；交易会'),
  m(9, 5, 'word', 'grass', '/ɡræs/', 'n. 草；草地'),
  m(9, 5, 'word', 'leaf', '/liːf/', 'n. (pl leaves /liːvz/) 叶；叶子'),
  m(9, 5, 'word', 'produce', '/prəˈduːs/', 'v. 生产；制造；出产'),
  m(9, 5, 'word', 'widely', '/ˈwaɪdli/', 'adv. 广泛地；普遍地'),
  m(9, 5, 'word', 'be known for', '/biː nəʊn fɔːr/', '以…闻名；为人知晓'),
  m(9, 5, 'word', 'process', '/ˈprɑːses/', 'v. 加工；处理 n. 过程'),
  m(9, 5, 'word', 'pack', '/pæk/', 'v. 包装；装箱'),
  m(9, 5, 'word', 'business', '/ˈbɪznəs/', 'n. 生意；商业'),
  m(9, 5, 'word', 'product', '/ˈprɑːdʌkt/', 'n. 产品；制品'),
  m(9, 5, 'word', 'France', '/fræns/', 'n. 法国'),
  m(9, 5, 'word', 'no matter', '/noʊ ˈmætər/', '不论；无论'),
  m(9, 5, 'word', 'local', '/ˈloʊkl/', 'adj. 当地的；本地的'),
  m(9, 5, 'word', 'brand', '/brænd/', 'n. 品牌；牌子'),
  m(9, 5, 'word', 'avoid', '/əˈvɔɪd/', 'v. 避免；回避'),
  m(9, 5, 'word', 'handbag', '/ˈhændbæɡ/', 'n. 小手提包'),
  m(9, 5, 'word', 'mobile', '/ˈmoʊbl/', 'adj. 可移动的；非固定的'),
  m(9, 5, 'word', 'everyday', '/ˈevrideɪ/', 'adj. 每日的；日常的'),
  m(9, 5, 'word', 'boss', '/bɔːs/', 'n. 老板；上司'),
  m(9, 5, 'word', 'Germany', '/ˈdʒɜːrməni/', 'n. 德国'),
  m(9, 5, 'word', 'surface', '/ˈsɜːrfɪs/', 'n. 表面；表层'),
  m(9, 5, 'word', 'material', '/məˈtɪriəl/', 'n. 材料；原料'),
  m(9, 5, 'word', 'judge', '/dʒʌdʒ/', 'n. 法官；裁判员 v. 判断；审判；评价'),
  m(9, 5, 'word', 'punish', '/ˈpʌnɪʃ/', 'v. 处罚；惩罚'),
  m(9, 5, 'word', 'traffic', '/ˈtræfɪk/', 'n. 交通；路上行驶的车辆'),
  m(9, 5, 'word', 'cap', '/kæp/', 'n. (尤指有檐的) 帽子'),
  m(9, 5, 'word', 'glove', '/ɡlʌv/', 'n. (分手指的) 手套'),
  m(9, 5, 'word', 'international', '/ˌɪntərˈnæʃnəl/', 'adj. 国际的'),
  m(9, 5, 'word', 'competitor', '/kəmˈpetɪtər/', 'n. 参赛者；竞争者'),
  m(9, 5, 'word', 'its', '/ɪts/', 'pron. 它的'),
  m(9, 5, 'word', 'form', '/fɔːrm/', 'n. 形式；类型'),
  m(9, 5, 'word', 'clay', '/kleɪ/', 'n. 黏土；陶土'),
  m(9, 5, 'word', 'balloon', '/bəˈluːn/', 'n. 气球'),
  m(9, 5, 'word', 'paper cutting', '/ˈpeɪpər ˌkʌtɪŋ/', '剪纸'),
  m(9, 5, 'word', 'scissors', '/ˈsɪzərz/', 'n. (pl.) 剪刀'),
  m(9, 5, 'word', 'lively', '/ˈlaɪvli/', 'adj. 生机勃勃的；(色彩) 鲜艳的'),
  m(9, 5, 'word', 'fairy', '/ˈferi/', 'tales 童话故事'),
  m(9, 5, 'word', 'historical', '/hɪˈstɔːrɪkl/', 'adj. (有关) 历史的'),
  m(9, 5, 'word', 'heat', '/hiːt/', 'n. 热；高温 v. 加热；变热'),
  m(9, 5, 'word', 'polish', '/ˈpɑːlɪʃ/', 'v. 磨光；修改；润色'),
  m(9, 5, 'word', 'complete', '/kəmˈpliːt/', 'v. 完成'),
  m(9, 5, 'word', 'postman', '/ˈpoʊstmən/', 'n. 邮递员'),
  m(9, 5, 'sentence', 'Are your shirts made of cotton?', '', '你的衬衫是棉布做的吗？'),
  m(9, 5, 'sentence', 'Yes, they are. And they were made in the US.', '', '是的，它们是。而且它们是在美国制造的。'),
  m(9, 5, 'sentence', 'What\u2019s the model plane made of?', '', '这个模型飞机是用什么做的？'),
  m(9, 5, 'sentence', 'It\u2019s made of used wood and glass.', '', '它是用旧木头和玻璃做的。'),
  m(9, 5, 'sentence', 'How is tea produced?', '', '茶叶是怎样生产的？'),
  m(9, 5, 'sentence', 'Tea plants are grown on the sides of mountains.', '', '茶树种植在山坡上。'),
  m(9, 5, 'sentence', 'When the leaves are ready, they are picked by hand and then are sent for processing.', '', '当茶叶长成后，由人工采摘，然后送去加工。'),
].join('\n');

// -------- U6: When was it invented? (Inventions) --------
const U6 = [
  m(9, 6, 'word', 'heel', '/hiːl/', 'n. 鞋跟；足跟'),
  m(9, 6, 'word', 'electricity', '/ɪˌlekˈtrɪsəti/', 'n. 电；电能'),
  m(9, 6, 'word', 'style', '/staɪl/', 'n. 样式；款式'),
  m(9, 6, 'word', 'project', '/ˈprɑːdʒekt/', 'n. 项目；工程'),
  m(9, 6, 'word', 'pleasure', '/ˈpleʒər/', 'n. 高兴；愉快'),
  m(9, 6, 'word', 'zipper', '/ˈzɪpər/', 'n. (=zip) 拉链；拉锁'),
  m(9, 6, 'word', 'daily', '/ˈdeɪli/', 'adj. 每日的；日常的'),
  m(9, 6, 'word', 'have a point', '/hæv ə pɔɪnt/', '有道理'),
  m(9, 6, 'word', 'website', '/ˈwebsaɪt/', 'n. 网站'),
  m(9, 6, 'word', 'pioneer', '/ˌpaɪəˈnɪr/', 'n. 先锋；先驱'),
  m(9, 6, 'word', 'list', '/lɪst/', 'v. 列表；列清单 n. 名单；清单'),
  m(9, 6, 'word', 'mention', '/ˈmenʃn/', 'v. 提到；说到'),
  m(9, 6, 'word', 'spread', '/spred/', 'v. (spread, spread) 传播；展开 v. 蔓延'),
  m(9, 6, 'word', 'by accident', '/baɪ ˈæksɪdənt/', '偶然；意外地'),
  m(9, 6, 'word', 'accidental', '/ˌæksɪˈdentl/', 'adj. 意外的；偶然的'),
  m(9, 6, 'word', 'ruler', '/ˈruːlər/', 'n. 统治者；支配者'),
  m(9, 6, 'word', 'boil', '/bɔɪl/', 'v. 煮沸；烧开'),
  m(9, 6, 'word', 'remain', '/rɪˈmeɪn/', 'v. 保持不变；剩余'),
  m(9, 6, 'word', 'sage', '/seɪdʒ/', 'n. 圣人；智者'),
  m(9, 6, 'word', 'national', '/ˈnæʃnəl/', 'adj. 国家的；民族的'),
  m(9, 6, 'word', 'trade', '/treɪd/', 'n. 贸易；交易 v. 做买卖；从事交易'),
  m(9, 6, 'word', 'popularity', '/ˌpɑːpjəˈlærəti/', 'n. 受欢迎；普及'),
  m(9, 6, 'word', 'doubt', '/daʊt/', 'n. 疑惑；疑问 v. 怀疑'),
  m(9, 6, 'word', 'fridge', '/frɪdʒ/', 'n. 冰箱'),
  m(9, 6, 'word', 'low', '/loʊ/', 'adj. 低的；矮的'),
  m(9, 6, 'word', 'somebody', '/ˈsʌmbɑːdi/', 'pron. 某人；重要人物'),
  m(9, 6, 'word', 'wolf', '/wʊlf/', 'n. 狼'),
  m(9, 6, 'word', 'warn', '/wɔːrn/', 'v. 警告；告诫'),
  m(9, 6, 'word', 'translate', '/trænsˈleɪt/', 'v. 翻译'),
  m(9, 6, 'word', 'lock', '/lɑːk/', 'v. 锁上；锁住 n. 锁'),
  m(9, 6, 'word', 'ring', '/rɪŋ/', 'v. (rang/ræŋ/, rung/rʌŋ/) （使）发出钟声或铃声；打电话'),
  m(9, 6, 'word', 'earthquake', '/ˈɜːrθkweɪk/', 'n. 地震'),
  m(9, 6, 'word', 'sudden', '/ˈsʌdn/', 'adj. 突然（的）'),
  m(9, 6, 'word', 'all of a sudden', '/ɔːl ɒv ə ˈsʌdn/', '突然；猛地'),
  m(9, 6, 'word', 'bell', '/bel/', 'n. 钟（声）；铃（声）'),
  m(9, 6, 'word', 'biscuit', '/ˈbɪskɪt/', 'n. 饼干'),
  m(9, 6, 'word', 'cookie', '/ˈkʊki/', 'n. 曲奇饼'),
  m(9, 6, 'word', 'musical', '/ˈmjuːzɪkl/', 'adj. 音乐的；有音乐天赋的'),
  m(9, 6, 'word', 'instrument', '/ˈɪnstrəmənt/', 'n. 器械；仪器；工具'),
  m(9, 6, 'word', 'crispy', '/ˈkrɪspi/', 'adj. 脆的；酥脆的'),
  m(9, 6, 'word', 'salty', '/ˈsɔːlti/', 'adj. 咸的'),
  m(9, 6, 'word', 'sour', '/ˈsaʊər/', 'adj. 酸的；有酸味的'),
  m(9, 6, 'word', 'by mistake', '/baɪ mɪˈsteɪk/', '错误地；无意中'),
  m(9, 6, 'word', 'customer', '/ˈkʌstəmər/', 'n. 顾客；客户'),
  m(9, 6, 'word', 'the Olympics', '/ði oʊˈlɪmpɪks/', '奥林匹克运动会'),
  m(9, 6, 'word', 'Canadian', '/kəˈneɪdiən/', 'adj. 加拿大的；加拿大人的 n. 加拿大人'),
  m(9, 6, 'word', 'divide', '/dɪˈvaɪd/', 'v. 分开；分散'),
  m(9, 6, 'word', 'divide ... into', '/dɪˈvaɪd ˈɪntuː/', '把…分成'),
  m(9, 6, 'word', 'basket', '/ˈbæskɪt/', 'n. 篮；筐'),
  m(9, 6, 'word', 'not only ... but also ...', '/nɒt ˈoʊnli ... bʌt ˈɔːlsoʊ .../', '不仅…而且…'),
  m(9, 6, 'word', 'look up to', '/lʊk ʌp tuː/', '钦佩；仰慕'),
  m(9, 6, 'word', 'hero', '/ˈhɪroʊ/', 'n. 英雄；男主角'),
  m(9, 6, 'word', 'professional', '/prəˈfeʃənl/', 'adj. 职业的；专业的 n. 专业人员'),
  m(9, 6, 'word', 'nearly', '/ˈnɪrli/', 'adv. 几乎'),
  m(9, 6, 'sentence', 'When was the zipper invented?', '', '拉链是什么时候发明的？'),
  m(9, 6, 'sentence', 'It was invented in 1893.', '', '它是在 1893 年发明的。'),
  m(9, 6, 'sentence', 'Who was it invented by?', '', '它是谁发明的？'),
  m(9, 6, 'sentence', 'It was invented by Whitcomb Judson.', '', '它是由惠特科姆·贾德森发明的。'),
  m(9, 6, 'sentence', 'What is the hot ice-cream scoop used for?', '', '热冰淇淋勺是用来干什么的？'),
  m(9, 6, 'sentence', 'It\u2019s used for serving really cold ice-cream.', '', '它是用来盛非常冷的冰淇淋的。'),
  m(9, 6, 'sentence', 'It is said that ...', '', '据说…'),
  m(9, 6, 'sentence', 'It is believed that ...', '', '人们相信…'),
].join('\n');

// -------- U7: Teenagers should be allowed to choose their own clothes. (Rules) --------
const U7 = [
  m(9, 7, 'word', 'license', '/ˈlaɪsns/', 'n. (=licence) 证；证件'),
  m(9, 7, 'word', 'safety', '/ˈseɪfti/', 'n. 安全；安全性'),
  m(9, 7, 'word', 'smoke', '/smoʊk/', 'v. 吸烟；冒烟 n. 烟'),
  m(9, 7, 'word', 'part-time', '/ˌpɑːrtˈtaɪm/', 'adj. & adv. 兼职（的）'),
  m(9, 7, 'word', 'pierce', '/pɪrs/', 'v. 扎；刺破；穿透'),
  m(9, 7, 'word', 'earring', '/ˈɪrɪŋ/', 'n. 耳环；耳饰'),
  m(9, 7, 'word', 'flash', '/flæʃ/', 'n. 闪光灯；闪光 v. 闪耀；闪光'),
  m(9, 7, 'word', 'tiny', '/ˈtaɪni/', 'adj. 极小的；微小的'),
  m(9, 7, 'word', 'cry', '/kraɪ/', 'v. & n. 哭；叫喊'),
  m(9, 7, 'word', 'field', '/fiːld/', 'n. 田野；场地'),
  m(9, 7, 'word', 'hug', '/hʌɡ/', 'n. & v. 拥抱；搂抱'),
  m(9, 7, 'word', 'lift', '/lɪft/', 'v. 举起；抬高 n. 电梯；搭便车'),
  m(9, 7, 'word', 'badly', '/ˈbædli/', 'adv. 严重地；差；非常'),
  m(9, 7, 'word', 'talk back', '/tɔːk bæk/', '回嘴；顶嘴'),
  m(9, 7, 'word', 'awful', '/ˈɔːfl/', 'adj. 很坏的；讨厌的'),
  m(9, 7, 'word', 'teen', '/tiːn/', 'n. (13 至 19 岁之间的) 青少年'),
  m(9, 7, 'word', 'regret', '/rɪˈɡret/', 'v. & n. 感到遗憾；懊悔'),
  m(9, 7, 'word', 'poem', '/ˈpoʊəm/', 'n. 诗；韵文'),
  m(9, 7, 'word', 'community', '/kəˈmjuːnəti/', 'n. 社区；社团'),
  m(9, 7, 'word', 'keep ... away from', '/kiːp əˈweɪ frɒm/', '避免接近；远离'),
  m(9, 7, 'word', 'chance', '/tʃæns/', 'n. 机会；可能性'),
  m(9, 7, 'word', 'make one\u2019s own decision', '/meɪk wʌnz oʊn dɪˈsɪʒn/', '自己做决定'),
  m(9, 7, 'word', 'educate', '/ˈedʒukeɪt/', 'v. 教育；教导'),
  m(9, 7, 'word', 'manage', '/ˈmænɪdʒ/', 'v. 完成（困难的事）；管理'),
  m(9, 7, 'word', 'society', '/səˈsaɪəti/', 'n. 社会'),
  m(9, 7, 'word', 'get in the way of', '/ɡet ɪn ðə weɪ ɒv/', '妨碍；挡…的路'),
  m(9, 7, 'word', 'support', '/səˈpɔːrt/', 'v. & n. 支持'),
  m(9, 7, 'word', 'end up', '/end ʌp/', '最终成为；最后处于'),
  m(9, 7, 'word', 'enter', '/ˈentər/', 'v. 进来；进去'),
  m(9, 7, 'word', 'choice', '/tʃɔɪs/', 'n. 选择；挑选'),
  m(9, 7, 'word', 'Picasso', '/pɪˈkɑːsoʊ/', 'n. 毕加索（西班牙画家）'),
  m(9, 7, 'phrase', 'take photos', '/teɪk ˈfoʊtoʊz/', '拍照'),
  m(9, 7, 'phrase', 'move out', '/muːv aʊt/', '搬出'),
  m(9, 7, 'phrase', 'take care of', '/teɪk ker ɒv/', '照顾；照料'),
  m(9, 7, 'phrase', 'look after', '/lʊk ˈæftər/', '照顾'),
  m(9, 7, 'phrase', 'care about', '/ker əˈbaʊt/', '关心；在意'),
  m(9, 7, 'sentence', 'I don\u2019t think sixteen-year-olds should be allowed to drive.', '', '我认为不应该允许十六岁的孩子开车。'),
  m(9, 7, 'sentence', 'I agree. They aren\u2019t serious enough.', '', '我同意。他们不够严肃认真。'),
  m(9, 7, 'sentence', 'Teenagers should not be allowed to have part-time jobs.', '', '不应该允许青少年做兼职工作。'),
  m(9, 7, 'sentence', 'I disagree. They can learn a lot from working.', '', '我不同意。他们可以从工作中学到很多东西。'),
].join('\n');

// -------- U8: It must belong to Carla. (Mysteries) --------
const U8 = [
  m(9, 8, 'word', 'whose', '/huːz/', 'adj. & pron. 谁的'),
  m(9, 8, 'word', 'truck', '/trʌk/', 'n. 卡车；货车'),
  m(9, 8, 'word', 'rabbit', '/ˈræbɪt/', 'n. 兔；野兔'),
  m(9, 8, 'word', 'attend', '/əˈtend/', 'v. 出席；参加'),
  m(9, 8, 'word', 'valuable', '/ˈvæljuəbl/', 'adj. 贵重的；很有用的；宝贵的'),
  m(9, 8, 'word', 'pink', '/pɪŋk/', 'adj. 粉红色的 n. 粉红色'),
  m(9, 8, 'word', 'anybody', '/ˈenibɑːdi/', 'pron. 任何人'),
  m(9, 8, 'word', 'déjà vu', '/ˌdeɪʒɑː ˈvuː/', 'n. 似曾经历过的感觉；似曾相识'),
  m(9, 8, 'word', 'mystery', '/ˈmɪstri/', 'n. 奥秘；神秘事物'),
  m(9, 8, 'word', 'be known as', '/biː nəʊn æz/', '被称为；被认为是'),
  m(9, 8, 'word', 'theory', '/ˈθɪri/', 'n. 学说；理论；看法'),
  m(9, 8, 'word', 'familiar', '/fəˈmɪliər/', 'adj. 熟悉的；常见的'),
  m(9, 8, 'word', 'hidden', '/ˈhɪdn/', 'adj. 秘密的；隐藏的'),
  m(9, 8, 'word', 'power', '/ˈpaʊər/', 'n. 能力；权力'),
  m(9, 8, 'word', 'link', '/lɪŋk/', 'n. 联系；连接'),
  m(9, 8, 'word', 'parallel', '/ˈpærəlel/', 'adj. 平行的；同时发生的'),
  m(9, 8, 'word', 'universe', '/ˈjuːnɪvɜːrs/', 'n. 宇宙'),
  m(9, 8, 'word', 'parallel universes', '/ˈpærəlel ˈjuːnɪvɜːrsɪz/', '平行宇宙'),
  m(9, 8, 'word', 'mix-up', '/ˈmɪks ʌp/', 'n. 混乱；杂乱'),
  m(9, 8, 'word', 'generally speaking', '/ˈdʒenrəli ˈspiːkɪŋ/', '一般来说'),
  m(9, 8, 'word', 'trick', '/trɪk/', 'n. 引起错觉（或记忆紊乱）的事物；诡计 v. 欺骗；欺诈'),
  m(9, 8, 'word', 'unsolved', '/ʌnˈsɑːlvd/', 'adj. 未解决的；未破解的'),
  m(9, 8, 'word', 'laboratory', '/ˈlæbrətɔːri/', 'n. 实验室'),
  m(9, 8, 'word', 'outdoors', '/ˌaʊtˈdɔːrz/', 'adv. 在户外；在野外'),
  m(9, 8, 'word', 'coat', '/koʊt/', 'n. 外套；外衣'),
  m(9, 8, 'word', 'lie', '/laɪ/', 'v. (lay/leɪ/, lain/leɪn/) 平躺；处于'),
  m(9, 8, 'word', 'sleepy', '/ˈsliːpi/', 'adj. 困倦的；瞌睡的'),
  m(9, 8, 'word', 'land', '/lænd/', 'v. 着陆；降落 n. 陆地；大地'),
  m(9, 8, 'word', 'alien', '/ˈeɪliən/', 'n. 外星人'),
  m(9, 8, 'word', 'run after', '/rʌn ˈæftər/', '追逐；追赶'),
  m(9, 8, 'word', 'suit', '/suːt/', 'n. 西服；套装 v. 适合'),
  m(9, 8, 'word', 'at the same time', '/æt ðə seɪm taɪm/', '同时；一起'),
  m(9, 8, 'word', 'circle', '/ˈsɜːrkl/', 'n. 圆圈 v. 圈出'),
  m(9, 8, 'word', 'Britain', '/ˈbrɪtn/', 'n. 不列颠'),
  m(9, 8, 'word', 'receive', '/rɪˈsiːv/', 'v. 接待；接受；收到'),
  m(9, 8, 'word', 'historian', '/hɪˈstɔːriən/', 'n. 历史学家；史学工作者'),
  m(9, 8, 'word', 'temple', '/ˈtempl/', 'n. 庙宇；寺院；圣殿'),
  m(9, 8, 'word', 'leader', '/ˈliːdər/', 'n. 领导；领袖'),
  m(9, 8, 'word', 'midsummer', '/ˌmɪdˈsʌmər/', 'n. 仲夏；中夏'),
  m(9, 8, 'word', 'medical', '/ˈmedɪkl/', 'adj. 医疗的；医学的'),
  m(9, 8, 'word', 'purpose', '/ˈpɜːrpəs/', 'n. 目的；目标'),
  m(9, 8, 'word', 'prevent', '/prɪˈvent/', 'v. 阻止；阻挠'),
  m(9, 8, 'word', 'energy', '/ˈenərdʒi/', 'n. 力量；精力'),
  m(9, 8, 'word', 'position', '/pəˈzɪʃn/', 'n. 位置；地方'),
  m(9, 8, 'word', 'burial', '/ˈberiəl/', 'n. 埋葬；安葬'),
  m(9, 8, 'word', 'honor', '/ˈɑːnər/', 'n. (=honour) 荣誉；荣幸 v. 尊敬'),
  m(9, 8, 'word', 'ancestor', '/ˈænsestər/', 'n. 祖宗；祖先'),
  m(9, 8, 'word', 'victory', '/ˈvɪktəri/', 'n. 胜利；成功'),
  m(9, 8, 'word', 'enemy', '/ˈenəmi/', 'n. 敌人；仇人'),
  m(9, 8, 'word', 'period', '/ˈpɪriəd/', 'n. 一段时间；时期；句号'),
  m(9, 8, 'word', 'noise', '/nɔɪz/', 'n. 声音；噪音'),
  m(9, 8, 'word', 'Stonehenge', '/ˈstoʊnhendʒ/', 'n. 巨石阵'),
  m(9, 8, 'phrase', 'J. K. Rowling', '/dʒeɪ keɪ ˈroʊlɪŋ/', 'J. K. 罗琳（英国作家）'),
  m(9, 8, 'sentence', 'Whose volleyball is this?', '', '这是谁的排球？'),
  m(9, 8, 'sentence', 'It must be Carla\u2019s. She loves volleyball.', '', '它一定是 Carla 的。她喜爱排球。'),
  m(9, 8, 'sentence', 'Whose hair band is this?', '', '这是谁的发带？'),
  m(9, 8, 'sentence', 'It could be Mei\u2019s hair band. Or it might belong to Linda.', '', '它可能是 Mei 的发带。或者它可能属于 Linda。'),
  m(9, 8, 'sentence', 'They both have long hair.', '', '她们俩都有长发。'),
  m(9, 8, 'sentence', 'What did you see that night?', '', '那天晚上你看见什么了？'),
  m(9, 8, 'sentence', 'I\u2019m not sure, but it can\u2019t be a dog.', '', '我不确定，但它不可能是一条狗。'),
].join('\n');

// -------- U9: I like music that I can dance to. (Music and movies) --------
const U9 = [
  m(9, 9, 'word', 'prefer', '/prɪˈfɜːr/', 'v. 更喜欢'),
  m(9, 9, 'word', 'lyrics', '/ˈlɪrɪks/', 'n. (pl.) 歌词'),
  m(9, 9, 'word', 'Australian', '/ɔːˈstreɪliən/', 'adj. 澳大利亚的；澳大利亚人的 n. 澳大利亚人'),
  m(9, 9, 'word', 'electronic', '/ɪˌlekˈtrɑːnɪk/', 'adj. 电子的；电子设备的'),
  m(9, 9, 'word', 'suppose', '/səˈpoʊz/', 'v. 推断；料想'),
  m(9, 9, 'word', 'smooth', '/smuːð/', 'adj. 悦耳的；平滑的'),
  m(9, 9, 'word', 'spare', '/sper/', 'adj. 空闲的；不用的 v. 抽出；留出'),
  m(9, 9, 'word', 'director', '/dəˈrektər/', 'n. 导演；部门负责人'),
  m(9, 9, 'word', 'case', '/keɪs/', 'n. 情况；实情'),
  m(9, 9, 'word', 'in that case', '/ɪn ðæt keɪs/', '既然那样；假使那样的话'),
  m(9, 9, 'word', 'war', '/wɔːr/', 'n. 战争；战争状态'),
  m(9, 9, 'word', 'stick', '/stɪk/', 'v. (stuck/stʌk/, stuck) 粘贴；将…刺入'),
  m(9, 9, 'word', 'stick to', '/stɪk tuː/', '坚持；固守'),
  m(9, 9, 'word', 'down', '/daʊn/', 'adj. 悲哀；沮丧'),
  m(9, 9, 'word', 'dialog', '/ˈdaɪəlɔːɡ/', 'n. (=dialogue) 对话；对白'),
  m(9, 9, 'word', 'ending', '/ˈendɪŋ/', 'n. (故事、电影等的) 结尾；结局'),
  m(9, 9, 'word', 'documentary', '/ˌdɑːkjuˈmentri/', 'n. 纪录片'),
  m(9, 9, 'word', 'drama', '/ˈdrɑːmə/', 'n. 戏；剧'),
  m(9, 9, 'word', 'plenty', '/ˈplenti/', 'pron. 大量；众多'),
  m(9, 9, 'word', 'plenty of', '/ˈplenti ɒv/', '大量；充足'),
  m(9, 9, 'word', 'shut', '/ʃʌt/', 'v. (shut, shut) 关闭；关上'),
  m(9, 9, 'word', 'shut off', '/ʃʌt ɔːf/', '关闭；停止运转'),
  m(9, 9, 'word', 'superhero', '/ˈsuːpərhɪroʊ/', 'n. 超级英雄'),
  m(9, 9, 'word', 'once in a while', '/wʌns ɪn ə waɪl/', '偶尔地；间或'),
  m(9, 9, 'word', 'intelligent', '/ɪnˈtelɪdʒənt/', 'adj. 有才智的；聪明的'),
  m(9, 9, 'word', 'sense', '/sens/', 'v. 感觉到；意识到 n. 感觉；意识'),
  m(9, 9, 'word', 'sadness', '/ˈsædnəs/', 'n. 悲伤；悲痛'),
  m(9, 9, 'word', 'pain', '/peɪn/', 'n. 痛苦；疼痛；苦恼'),
  m(9, 9, 'word', 'reflect', '/rɪˈflekt/', 'v. 反映；映出'),
  m(9, 9, 'word', 'moving', '/ˈmuːvɪŋ/', 'adj. 动人的；令人感动的'),
  m(9, 9, 'word', 'perform', '/pərˈfɔːrm/', 'v. 表演；执行'),
  m(9, 9, 'word', 'lifetime', '/ˈlaɪftaɪm/', 'n. 一生；有生之年'),
  m(9, 9, 'word', 'by the end of', '/baɪ ði end ɒv/', '在（某时间点）以前'),
  m(9, 9, 'word', 'pity', '/ˈpɪti/', 'n. 遗憾；怜悯 v. 同情；怜悯'),
  m(9, 9, 'word', 'total', '/ˈtoʊtl/', 'n. 总数；合计 adj. 总的；全体的'),
  m(9, 9, 'word', 'in total', '/ɪn ˈtoʊtl/', '总共；合计'),
  m(9, 9, 'word', 'master', '/ˈmæstər/', 'n. 大师；能手；主人 v. 掌握'),
  m(9, 9, 'word', 'praise', '/preɪz/', 'v. & n. 表扬；赞扬'),
  m(9, 9, 'word', 'recall', '/rɪˈkɔːl/', 'v. 回忆起；回想'),
  m(9, 9, 'word', 'wound', '/wuːnd/', 'n. 伤；伤口；创伤 v. 使（身体）受伤；伤害'),
  m(9, 9, 'word', 'painful', '/ˈpeɪnfl/', 'adj. 令人痛苦的；令人疼痛的'),
  m(9, 9, 'sentence', 'What kind of music do you like?', '', '你喜欢什么样的音乐？'),
  m(9, 9, 'sentence', 'I love music that/which I can sing along with.', '', '我喜欢能跟着唱的音乐。'),
  m(9, 9, 'sentence', 'What kind of movies do you like?', '', '你喜欢什么样的电影？'),
  m(9, 9, 'sentence', 'I prefer movies that/which give me something to think about.', '', '我更喜欢让我有所思考的电影。'),
  m(9, 9, 'sentence', 'What kind of musicians does Carmen like?', '', 'Carmen 喜欢什么样的音乐家？'),
  m(9, 9, 'sentence', 'She likes musicians who play different kinds of music.', '', '她喜欢演奏不同种类音乐的音乐家。'),
  m(9, 9, 'sentence', 'I don\u2019t mind ... anymore.', '', '我不再介意…'),
].join('\n');

// -------- U10: You\u2019re supposed to shake hands. (Customs) --------
const U10 = [
  m(9, 10, 'word', 'bow', '/baʊ/', 'v. & n. 鞠躬'),
  m(9, 10, 'word', 'kiss', '/kɪs/', 'v. & n. 亲吻；接吻'),
  m(9, 10, 'word', 'greet', '/ɡriːt/', 'v. 和…打招呼；迎接'),
  m(9, 10, 'word', 'relaxed', '/rɪˈlækst/', 'adj. 放松的；自在的'),
  m(9, 10, 'word', 'value', '/ˈvæljuː/', 'v. 重视；珍视 n. 价值'),
  m(9, 10, 'word', 'drop by', '/drɒp baɪ/', '顺便访问'),
  m(9, 10, 'word', 'capital', '/ˈkæpɪtl/', 'n. 首都；国都'),
  m(9, 10, 'word', 'after all', '/ˈæftər ɔːl/', '毕竟；终归'),
  m(9, 10, 'word', 'noon', '/nuːn/', 'n. 正午；中午'),
  m(9, 10, 'word', 'mad', '/mæd/', 'adj. 很生气；疯的'),
  m(9, 10, 'word', 'get mad', '/ɡet mæd/', '大动肝火；气愤'),
  m(9, 10, 'word', 'effort', '/ˈefərt/', 'n. 努力；尽力'),
  m(9, 10, 'word', 'make an effort', '/meɪk ən ˈefərt/', '作出努力'),
  m(9, 10, 'word', 'passport', '/ˈpæspɔːrt/', 'n. 护照'),
  m(9, 10, 'word', 'clean ... off', '/kliːn ɔːf/', '把…擦掉'),
  m(9, 10, 'word', 'chalk', '/tʃɔːk/', 'n. 粉笔'),
  m(9, 10, 'word', 'blackboard', '/ˈblækbɔːrd/', 'n. 黑板'),
  m(9, 10, 'word', 'northern', '/ˈnɔːrðərn/', 'adj. 北方的；北部的'),
  m(9, 10, 'word', 'coast', '/koʊst/', 'n. 海岸；海滨'),
  m(9, 10, 'word', 'season', '/ˈsiːzn/', 'n. 季；季节'),
  m(9, 10, 'word', 'knock', '/nɑːk/', 'v. 敲；击 n. 敲击声；敲击'),
  m(9, 10, 'word', 'eastern', '/ˈiːstərn/', 'adj. 东方的；东部的'),
  m(9, 10, 'word', 'take off', '/teɪk ɔːf/', '脱下（衣服）；（飞机等）起飞'),
  m(9, 10, 'word', 'worth', '/wɜːrθ/', 'adj. 值得；有…价值（的）'),
  m(9, 10, 'word', 'manner', '/ˈmænər/', 'n. 方式；方法；(pl.) 礼貌；礼仪'),
  m(9, 10, 'word', 'empty', '/ˈempti/', 'adj. 空的；空洞的'),
  m(9, 10, 'word', 'basic', '/ˈbeɪsɪk/', 'adj. 基本的；基础的'),
  m(9, 10, 'word', 'exchange', '/ɪksˈtʃeɪndʒ/', 'n. & v. 交换'),
  m(9, 10, 'word', 'go out of one\u2019s way', '/ɡoʊ aʊt ɒv wʌnz weɪ/', '特地；格外努力'),
  m(9, 10, 'word', 'make ... feel at home', '/meɪk fiːl æt hoʊm/', '使（某人）感到宾至如归'),
  m(9, 10, 'word', 'teenage', '/ˈtiːneɪdʒ/', 'adj. 十几岁的；青少年的'),
  m(9, 10, 'word', 'granddaughter', '/ˈɡrændɔːtər/', 'n. (外) 孙女'),
  m(9, 10, 'word', 'behave', '/bɪˈheɪv/', 'v. 表现；举止'),
  m(9, 10, 'word', 'except', '/ɪkˈsept/', 'prep. 除…之外 conj. 除了；只是'),
  m(9, 10, 'word', 'elbow', '/ˈelboʊ/', 'n. 肘；胳膊'),
  m(9, 10, 'word', 'gradually', '/ˈɡrædʒuəli/', 'adv. 逐步地；渐渐地'),
  m(9, 10, 'word', 'get used to', '/ɡet juːst tuː/', '习惯于'),
  m(9, 10, 'word', 'suggestion', '/səˈdʒestʃən/', 'n. 建议'),
  m(9, 10, 'word', 'Brazil', '/brəˈzɪl/', 'n. 巴西'),
  m(9, 10, 'word', 'Mexico', '/ˈmeksɪkoʊ/', 'n. 墨西哥'),
  m(9, 10, 'word', 'Cali', '/ˈkɑːli/', 'n. 卡利（哥伦比亚城市）'),
  m(9, 10, 'word', 'Colombia', '/kəˈlʌmbiə/', 'n. 哥伦比亚（南美洲国家）'),
  m(9, 10, 'word', 'Lausanne', '/loʊˈzæn/', 'n. 洛桑（瑞士城市）'),
  m(9, 10, 'word', 'Norway', '/ˈnɔːrweɪ/', 'n. 挪威'),
  m(9, 10, 'phrase', 'shake hands', '/ʃeɪk hændz/', '握手'),
  m(9, 10, 'phrase', 'on time', '/ɒn taɪm/', '准时'),
  m(9, 10, 'phrase', 'make friends', '/meɪk frendz/', '交朋友'),
  m(9, 10, 'phrase', 'to one\u2019s surprise', '/tuː wʌnz sərˈpraɪz/', '使某人吃惊的是'),
  m(9, 10, 'phrase', 'be used to', '/biː juːst tuː/', '习惯于'),
  m(9, 10, 'sentence', 'What are you supposed to do when you meet someone for the first time?', '', '当你第一次见到某人时，你应该做什么？'),
  m(9, 10, 'sentence', 'You\u2019re supposed to shake hands.', '', '你应该握手。'),
  m(9, 10, 'sentence', 'Am I supposed to wear jeans?', '', '我应该穿牛仔裤吗？'),
  m(9, 10, 'sentence', 'No, you\u2019re expected to wear a suit and tie.', '', '不，你应该穿西装打领带。'),
  m(9, 10, 'sentence', 'Is it important to be on time?', '', '准时重要吗？'),
  m(9, 10, 'sentence', 'Yes, it\u2019s important to be on time.', '', '是的，准时很重要。'),
].join('\n');

// -------- U11: Sad movies make me cry. (Feelings) --------
const U11 = [
  m(9, 11, 'word', 'rather', '/ˈræðər/', 'adv. 宁愿；相当'),
  m(9, 11, 'word', 'would rather', '/wʊd ˈræðər/', '（通常缩写为\u2019d rather）宁愿'),
  m(9, 11, 'word', 'drive', '/draɪv/', 'v. (drove/droʊv/, driven/ˈdrɪvn/) 迫使'),
  m(9, 11, 'word', 'drive sb. crazy/mad', '/draɪv ˈkreɪzi/', '使人发疯；发狂'),
  m(9, 11, 'word', 'the more ... the more ...', '/ðə mɔːr ðə mɔːr/', '越…越…；愈…愈…'),
  m(9, 11, 'word', 'lately', '/ˈleɪtli/', 'adv. 最近；不久前'),
  m(9, 11, 'word', 'be friends with sb.', '/biː frendz wɪð/', '成为某人的朋友'),
  m(9, 11, 'word', 'leave out', '/liːv aʊt/', '忽略；不提及；不包括'),
  m(9, 11, 'word', 'friendship', '/ˈfrendʃɪp/', 'n. 友谊；友情'),
  m(9, 11, 'word', 'king', '/kɪŋ/', 'n. 国王；君主'),
  m(9, 11, 'word', 'prime', '/praɪm/', 'adj. 首要的；基本的'),
  m(9, 11, 'word', 'minister', '/ˈmɪnɪstər/', 'n. 大臣；部长'),
  m(9, 11, 'word', 'prime minister', '/praɪm ˈmɪnɪstər/', '首相；总理'),
  m(9, 11, 'word', 'banker', '/ˈbæŋkər/', 'n. 银行家'),
  m(9, 11, 'word', 'fame', '/feɪm/', 'n. 名声；声誉'),
  m(9, 11, 'word', 'pale', '/peɪl/', 'adj. 苍白的；灰白的'),
  m(9, 11, 'word', 'queen', '/kwiːn/', 'n. 王后；女王'),
  m(9, 11, 'word', 'call in', '/kɔːl ɪn/', '召来；叫来'),
  m(9, 11, 'word', 'examine', '/ɪɡˈzæmɪn/', 'v. (仔细地) 检查；检验'),
  m(9, 11, 'word', 'nor', '/nɔːr/', 'conj. & adv. 也不'),
  m(9, 11, 'word', 'neither ... nor ...', '/ˈniːðər ... nɔːr .../', '既不…也不…'),
  m(9, 11, 'word', 'palace', '/ˈpæləs/', 'n. 王宫；宫殿'),
  m(9, 11, 'word', 'wealth', '/welθ/', 'n. 财富'),
  m(9, 11, 'word', 'to start with', '/tuː stɑːrt wɪð/', '起初；开始时'),
  m(9, 11, 'word', 'grey', '/ɡreɪ/', 'adj. (天空) 阴沉；昏暗的；灰色的'),
  m(9, 11, 'word', 'lemon', '/ˈlemən/', 'n. 柠檬'),
  m(9, 11, 'word', 'uncomfortable', '/ʌnˈkʌmfətəbl/', 'adj. 使人不舒服的；令人不舒适的'),
  m(9, 11, 'word', 'weight', '/weɪt/', 'n. 重量；分量'),
  m(9, 11, 'word', 'shoulder', '/ˈʃoʊldər/', 'n. 肩；肩膀'),
  m(9, 11, 'word', 'goal', '/ɡoʊl/', 'n. 射门；球门；目标'),
  m(9, 11, 'word', 'let ... down', '/let daʊn/', '使失望'),
  m(9, 11, 'word', 'coach', '/koʊtʃ/', 'n. 教练；私人教师'),
  m(9, 11, 'word', 'kick', '/kɪk/', 'v. 踢；踹'),
  m(9, 11, 'word', 'kick sb. off', '/kɪk ɔːf/', '开除某人'),
  m(9, 11, 'word', 'be hard on sb.', '/biː hɑːrd ɒn/', '对某人苛刻；对某人要求严厉'),
  m(9, 11, 'word', 'besides', '/bɪˈsaɪdz/', 'adv. 而且'),
  m(9, 11, 'word', 'teammate', '/ˈtiːmmeɪt/', 'n. 同队队员；队友'),
  m(9, 11, 'word', 'courage', '/ˈkɜːrɪdʒ/', 'n. 勇敢；勇气'),
  m(9, 11, 'word', 'rather than', '/ˈræðər ðæn/', '而不是'),
  m(9, 11, 'word', 'guy', '/ɡaɪ/', 'n. (非正式) 家伙；(pl.) 伙计们'),
  m(9, 11, 'word', 'pull together', '/pʊl təˈɡeðər/', '齐心协力；通力合作'),
  m(9, 11, 'word', 'relief', '/rɪˈliːf/', 'n. 轻松；解脱'),
  m(9, 11, 'word', 'nod', '/nɑːd/', 'v. 点头'),
  m(9, 11, 'word', 'agreement', '/əˈɡriːmənt/', 'n. (意见或看法) 一致；同意'),
  m(9, 11, 'word', 'fault', '/fɔːlt/', 'n. 过失；缺点'),
  m(9, 11, 'word', 'disappoint', '/ˌdɪsəˈpɔɪnt/', 'v. 使失望'),
  m(9, 11, 'sentence', 'The loud music makes me nervous.', '', '响亮的音乐让我紧张。'),
  m(9, 11, 'sentence', 'Money and fame don\u2019t always make people happy.', '', '金钱和名声并不总能让人快乐。'),
  m(9, 11, 'sentence', 'She said that the sad movie made her cry.', '', '她说那部悲伤的电影让她哭了。'),
].join('\n');

// -------- U12: Life is full of the unexpected. (Unexpected events) --------
const U12 = [
  m(9, 12, 'word', 'unexpected', '/ˌʌnɪkˈspektɪd/', 'adj. 出乎意料的；始料不及的'),
  m(9, 12, 'word', 'by the time ...', '/baɪ ðə taɪm/', '在…以前'),
  m(9, 12, 'word', 'backpack', '/ˈbækpæk/', 'n. 背包；旅行包'),
  m(9, 12, 'word', 'oversleep', '/ˌoʊvərˈsliːp/', 'v. (overslept, overslept) 睡过头；睡得太久'),
  m(9, 12, 'word', 'give ... a lift', '/ɡɪv ə lɪft/', '捎…一程'),
  m(9, 12, 'word', 'block', '/blɑːk/', 'n. 街区'),
  m(9, 12, 'word', 'in line with', '/ɪn laɪn wɪð/', '与…成一排'),
  m(9, 12, 'word', 'worker', '/ˈwɜːrkər/', 'n. 工作者；工人'),
  m(9, 12, 'word', 'stare', '/ster/', 'v. 盯着看；凝视'),
  m(9, 12, 'word', 'disbelief', '/ˌdɪsbɪˈliːf/', 'n. 不信；怀疑'),
  m(9, 12, 'word', 'above', '/əˈbʌv/', 'prep. 在…上面 adv. 在上面'),
  m(9, 12, 'word', 'burn', '/bɜːrn/', 'v. (burnt/bɜːrnt/, burnt/bɜːrnt/) 着火；燃烧'),
  m(9, 12, 'word', 'burning', '/ˈbɜːrnɪŋ/', 'adj. 着火的；燃烧的'),
  m(9, 12, 'word', 'alive', '/əˈlaɪv/', 'adj. 活着；有生气的'),
  m(9, 12, 'word', 'airport', '/ˈerpɔːrt/', 'n. 机场'),
  m(9, 12, 'word', 'till', '/tɪl/', 'prep. & conj. 到；直到'),
  m(9, 12, 'word', 'west', '/west/', 'adv. 向西；朝西 adj. 向西的；西部的 n. 西；西方'),
  m(9, 12, 'word', 'dead', '/ded/', 'adj. 死的；失去生命的'),
  m(9, 12, 'word', 'cream', '/kriːm/', 'n. 奶油；乳脂'),
  m(9, 12, 'word', 'workday', '/ˈwɜːrkdeɪ/', 'n. 工作日'),
  m(9, 12, 'word', 'show up', '/ʃoʊ ʌp/', '赶到；露面'),
  m(9, 12, 'word', 'bean', '/biːn/', 'n. 豆；豆荚'),
  m(9, 12, 'word', 'market', '/ˈmɑːrkɪt/', 'n. 市场；集市'),
  m(9, 12, 'word', 'fool', '/fuːl/', 'n. 蠢人；傻瓜 v. 愚弄'),
  m(9, 12, 'word', 'costume', '/ˈkɑːstjuːm/', 'n. (特定场合穿的) 服装；装束'),
  m(9, 12, 'word', 'embarrassed', '/ɪmˈbærəst/', 'adj. 窘迫的；害羞的'),
  m(9, 12, 'word', 'costume party', '/ˈkɑːstjuːm ˌpɑːrti/', '化装舞会'),
  m(9, 12, 'word', 'announce', '/əˈnaʊns/', 'v. 宣布；宣告'),
  m(9, 12, 'word', 'spaghetti', '/spəˈɡeti/', 'n. 意大利面条'),
  m(9, 12, 'word', 'hoax', '/hoʊks/', 'n. 骗局；恶作剧'),
  m(9, 12, 'word', 'sell out', '/sel aʊt/', '卖光'),
  m(9, 12, 'word', 'discovery', '/dɪˈskʌvri/', 'n. 发现；发觉'),
  m(9, 12, 'word', 'lady', '/ˈleɪdi/', 'n. 女士；女子'),
  m(9, 12, 'word', 'cancel', '/ˈkænsl/', 'v. 取消；终止'),
  m(9, 12, 'word', 'officer', '/ˈɔːfɪsər/', 'n. 军官；官员'),
  m(9, 12, 'word', 'believable', '/bɪˈliːvəbl/', 'adj. 可相信的；可信任的'),
  m(9, 12, 'word', 'disappear', '/ˌdɪsəˈpɪr/', 'v. 消失；不见'),
  m(9, 12, 'word', 'embarrassing', '/ɪmˈbærəsɪŋ/', 'adj. 使人害羞的（难堪的或惭愧的）'),
  m(9, 12, 'word', 'New Zealand', '/nuː ˈziːlənd/', 'n. 新西兰'),
  m(9, 12, 'word', 'Italy', '/ˈɪtəli/', 'n. 意大利'),
  m(9, 12, 'word', 'Mars', '/mɑːrz/', 'n. 火星'),
  m(9, 12, 'sentence', 'When I got to school, I realized that I had left my backpack at home.', '', '当我到学校时，我意识到我把背包忘在家里了。'),
  m(9, 12, 'sentence', 'By the time I got back to school, the bell had rung.', '', '等我回到学校时，铃已经响了。'),
  m(9, 12, 'sentence', 'Before I got to the bus stop, the bus had already left.', '', '在我到公交车站之前，公共汽车已经开走了。'),
  m(9, 12, 'sentence', 'As I was waiting in line with the other office workers, I heard a loud sound.', '', '当我和别的上班族一起排队等候时，我听到一声巨响。'),
  m(9, 12, 'sentence', 'Life is full of the unexpected.', '', '生活充满了意外。'),
].join('\n');

// -------- U13: We\u2019re trying to save the earth! (Protecting the environment) --------
const U13 = [
  m(9, 13, 'word', 'litter', '/ˈlɪtər/', 'v. 乱扔 n. 垃圾；废弃物'),
  m(9, 13, 'word', 'ship', '/ʃɪp/', 'n. (大) 船；舰 v. 船运；运输'),
  m(9, 13, 'word', 'coal', '/koʊl/', 'n. 煤；煤块'),
  m(9, 13, 'word', 'ugly', '/ˈʌɡli/', 'adj. 丑陋的；难看的'),
  m(9, 13, 'word', 'advantage', '/ədˈvæntɪdʒ/', 'n. 优点；有利条件'),
  m(9, 13, 'word', 'cost', '/kɔːst/', 'v. (cost, cost) 花费 n. 花费；价钱'),
  m(9, 13, 'word', 'wooden', '/ˈwʊdn/', 'adj. 木制的；木头的'),
  m(9, 13, 'word', 'plastic', '/ˈplæstɪk/', 'adj. 塑料的 n. 塑料；塑胶'),
  m(9, 13, 'word', 'takeaway', '/ˈteɪkəweɪ/', 'n. 外卖食物'),
  m(9, 13, 'word', 'bin', '/bɪn/', 'n. 垃圾箱'),
  m(9, 13, 'word', 'fin', '/fɪn/', 'n. (鱼) 鳍'),
  m(9, 13, 'word', 'cruel', '/ˈkruːəl/', 'adj. 残酷的；残忍的'),
  m(9, 13, 'word', 'harmful', '/ˈhɑːrmfl/', 'adj. 有害的'),
  m(9, 13, 'word', 'be harmful to', '/biː ˈhɑːrmfl tuː/', '对…有害'),
  m(9, 13, 'word', 'at the top of', '/æt ðə tɑːp ɒv/', '在…顶部或顶端'),
  m(9, 13, 'word', 'chain', '/tʃeɪn/', 'n. 链子；链条'),
  m(9, 13, 'word', 'food chain', '/fuːd tʃeɪn/', '食物链'),
  m(9, 13, 'word', 'ecosystem', '/ˈiːkoʊsɪstəm/', 'n. 生态系统'),
  m(9, 13, 'word', 'industry', '/ˈɪndəstri/', 'n. 工业；行业'),
  m(9, 13, 'word', 'law', '/lɔː/', 'n. 法律；法规'),
  m(9, 13, 'word', 'scientific', '/ˌsaɪənˈtɪfɪk/', 'adj. 科学上的；科学的'),
  m(9, 13, 'word', 'present', '/ˈpreznt/', 'adj. 现在的；n. 现在；礼物'),
  m(9, 13, 'word', 'take part in', '/teɪk pɑːrt ɪn/', '参加'),
  m(9, 13, 'word', 'afford', '/əˈfɔːrd/', 'v. 承担得起（后果）；买得起'),
  m(9, 13, 'word', 'turn off', '/tɜːrn ɔːf/', '关掉'),
  m(9, 13, 'word', 'reusable', '/ˌriːˈjuːzəbl/', 'adj. 可重复使用的；可再次使用的'),
  m(9, 13, 'word', 'pay for', '/peɪ fɔːr/', '付费；付出代价'),
  m(9, 13, 'word', 'take action', '/teɪk ˈækʃn/', '采取行动'),
  m(9, 13, 'word', 'transportation', '/ˌtrænspɔːrˈteɪʃn/', 'n. 运输业；交通运输'),
  m(9, 13, 'word', 'recycle', '/ˌriːˈsaɪkl/', 'v. 回收利用；再利用'),
  m(9, 13, 'word', 'napkin', '/ˈnæpkɪn/', 'n. 餐巾；餐巾纸'),
  m(9, 13, 'word', 'throw away', '/θroʊ əˈweɪ/', '扔掉；抛弃'),
  m(9, 13, 'word', 'put sth. to good use', '/pʊt tuː ɡʊd juːs/', '好好利用某物'),
  m(9, 13, 'word', 'pull ... down', '/pʊl daʊn/', '拆下；摧毁'),
  m(9, 13, 'word', 'upside down', '/ˈʌpsaɪd daʊn/', '上下颠倒；倒转'),
  m(9, 13, 'word', 'gate', '/ɡeɪt/', 'n. 大门'),
  m(9, 13, 'word', 'bottle', '/ˈbɑːtl/', 'n. 瓶子'),
  m(9, 13, 'word', 'president', '/ˈprezɪdənt/', 'n. 负责人；主席；总统'),
  m(9, 13, 'word', 'inspiration', '/ˌɪnspəˈreɪʃn/', 'n. 灵感；鼓舞人心的人（故事等）'),
  m(9, 13, 'word', 'iron', '/ˈaɪərn/', 'n. 铁'),
  m(9, 13, 'word', 'work', '/wɜːrk/', 'n. (音乐、艺术) 作品'),
  m(9, 13, 'word', 'metal', '/ˈmetl/', 'n. 金属'),
  m(9, 13, 'word', 'bring back', '/brɪŋ bæk/', '恢复；使想起；归还'),
  m(9, 13, 'word', 'creativity', '/ˌkriːeɪˈtɪvəti/', 'n. 创造力；独创性'),
  m(9, 13, 'word', 'WildAid', '/ˈwaɪldeɪd/', '野生救援协会（美国）'),
  m(9, 13, 'word', 'WWF', '/ˌdʌbljuː dʌbljuː ˈef/', '世界自然基金会'),
  m(9, 13, 'sentence', 'We\u2019re trying to save the earth.', '', '我们在努力拯救地球。'),
  m(9, 13, 'sentence', 'The river used to be so clean.', '', '这条河过去很干净。'),
  m(9, 13, 'sentence', 'The air is badly polluted.', '', '空气被严重污染了。'),
  m(9, 13, 'sentence', 'No scientific studies have shown that shark fins are good for health.', '', '没有科学研究表明鱼翅有益健康。'),
].join('\n');

// -------- U14: I remember meeting all of you in Grade 7. (School days) --------
const U14 = [
  m(9, 14, 'word', 'survey', '/ˈsɜːrveɪ/', 'n. 调查'),
  m(9, 14, 'word', 'standard', '/ˈstændərd/', 'n. 标准；水平'),
  m(9, 14, 'word', 'row', '/roʊ/', 'n. 一排；一列；一行'),
  m(9, 14, 'word', 'in a row', '/ɪn ə roʊ/', '连续几次地'),
  m(9, 14, 'word', 'keyboard', '/ˈkiːbɔːrd/', 'n. 键盘式电子乐器；键盘'),
  m(9, 14, 'word', 'method', '/ˈmeθəd/', 'n. 方法；措施'),
  m(9, 14, 'word', 'instruction', '/ɪnˈstrʌkʃn/', 'n. 指示；命令'),
  m(9, 14, 'word', 'double', '/ˈdʌbl/', 'v. 加倍；是…的两倍 adj. 两倍的；加倍的'),
  m(9, 14, 'word', 'shall', '/ʃæl/', 'modal v. 将要；将会'),
  m(9, 14, 'word', 'look back at', '/lʊk bæk æt/', '回首（往事）；回忆；回顾'),
  m(9, 14, 'word', 'overcome', '/ˌoʊvərˈkʌm/', 'v. (overcame, overcome) 克服；战胜'),
  m(9, 14, 'word', 'make a mess', '/meɪk ə mes/', '弄得一团糟（一塌糊涂）'),
  m(9, 14, 'word', 'graduate', '/ˈɡrædʒueɪt/', 'v. 毕业；获得学位'),
  m(9, 14, 'word', 'keep one\u2019s cool', '/kiːp wʌnz kuːl/', '沉住气；保持冷静'),
  m(9, 14, 'word', 'caring', '/ˈkerɪŋ/', 'adj. 体贴人的；关心他人的'),
  m(9, 14, 'word', 'ours', '/aʊərz/', 'pron. 我们的'),
  m(9, 14, 'word', 'senior', '/ˈsiːniər/', 'adj. 级别（或地位）高的；高中 senior high (school) 高中'),
  m(9, 14, 'word', 'text', '/tekst/', 'n. 课文；文本'),
  m(9, 14, 'word', 'go by', '/ɡoʊ baɪ/', '(时间) 逝去；过去'),
  m(9, 14, 'word', 'level', '/ˈlevl/', 'n. 水平'),
  m(9, 14, 'word', 'degree', '/dɪˈɡriː/', 'n. (大学) 学位；度数；程度'),
  m(9, 14, 'word', 'manager', '/ˈmænɪdʒər/', 'n. 经理；经营者'),
  m(9, 14, 'word', 'believe in', '/bɪˈliːv ɪn/', '信任；信赖'),
  m(9, 14, 'word', 'gentleman', '/ˈdʒentlmən/', 'n. 先生；绅士'),
  m(9, 14, 'word', 'graduation', '/ˌɡrædʒuˈeɪʃn/', 'n. 毕业'),
  m(9, 14, 'word', 'ceremony', '/ˈserəmoʊni/', 'n. 典礼；仪式'),
  m(9, 14, 'word', 'first of all', '/fɜːrst ɒv ɔːl/', '首先'),
  m(9, 14, 'word', 'congratulate', '/kənˈɡrætʃuleɪt/', 'v. 祝贺'),
  m(9, 14, 'word', 'thirsty', '/ˈθɜːrsti/', 'adj. 渴望的；口渴的'),
  m(9, 14, 'word', 'be thirsty for', '/biː ˈθɜːrsti fɔːr/', '渴望；渴求'),
  m(9, 14, 'word', 'thankful', '/ˈθæŋkfl/', 'adj. 感谢；感激'),
  m(9, 14, 'word', 'be thankful to sb.', '/biː ˈθæŋkfl tuː/', '对某人心存感激'),
  m(9, 14, 'word', 'lastly', '/ˈlæstli/', 'adv. 最后'),
  m(9, 14, 'word', 'task', '/tæsk/', 'n. 任务；工作'),
  m(9, 14, 'word', 'ahead', '/əˈhed/', 'adv. 向前面；在前面'),
  m(9, 14, 'word', 'ahead of', '/əˈhed ɒv/', '在…前面'),
  m(9, 14, 'word', 'along with', '/əˈlɔːŋ wɪð/', '连同；除…以外还'),
  m(9, 14, 'word', 'responsible', '/rɪˈspɑːnsəbl/', 'adj. 有责任心的；负责的'),
  m(9, 14, 'word', 'be responsible for', '/biː rɪˈspɑːnsəbl fɔːr/', '对…有责任；负责'),
  m(9, 14, 'word', 'separate', '/ˈsepərət/', 'adj. 单独的；分离的 /ˈsepəreɪt/ v. 分开；分离'),
  m(9, 14, 'word', 'set out', '/set aʊt/', '出发；启程'),
  m(9, 14, 'word', 'separate from', '/ˈsepəreɪt frɒm/', '分离；隔开'),
  m(9, 14, 'word', 'wing', '/wɪŋ/', 'n. 翅膀；翼'),
  m(9, 14, 'sentence', 'I think that I\u2019ll have to study much harder for exams.', '', '我想我将不得不更努力学习以应对考试。'),
  m(9, 14, 'sentence', 'I\u2019m going to join the school volleyball team.', '', '我打算加入学校排球队。'),
  m(9, 14, 'sentence', 'I remember being a volunteer.', '', '我记得我曾是一名志愿者。'),
  m(9, 14, 'sentence', 'I\u2019m looking forward to going to senior high school.', '', '我盼望着去高中。'),
].join('\n');

// ===== 5. 组装 NEW_BLOCK =====
const HEAD = `  // ==================== 九年级（PEP Go for it! 旧版全一册 U1-14） ====================
  // 来源：用户 2026-09-05 拍 25 张截图（含 Contents / Words in Each Unit）
  // 教材版本：2014 旧版（全一册 14 单元；U13=U13 We're trying to save the earth / U14=School days）
`;

const NEW_BLOCK = HEAD
  + block(1,  'How can we become good learners 学习方法', U1)
  + block(2,  'I think that mooncakes are delicious! 节日', U2)
  + block(3,  'Could you please tell me where the restrooms are? 问路', U3)
  + block(4,  'I used to be afraid of the dark. 过去的习惯', U4)
  + block(5,  'What are the shirts made of? 材料与产地', U5)
  + block(6,  'When was it invented? 发明', U6)
  + block(7,  'Teenagers should be allowed to choose their own clothes. 规则与选择', U7)
  + block(8,  'It must belong to Carla. 推测', U8)
  + block(9,  'I like music that I can dance to. 定语从句', U9)
  + block(10, 'You\u2019re supposed to shake hands. 风俗', U10)
  + block(11, 'Sad movies make me cry. 情绪与感受', U11)
  + block(12, 'Life is full of the unexpected. 过去完成时', U12)
  + block(13, 'We\u2019re trying to save the earth! 保护环境', U13)
  + block(14, 'I remember meeting all of you in Grade 7. 校园生活', U14);

// ===== 6. 拼接：before + NEW_BLOCK + OLD_END_MARK + after =====
const before = text.slice(0, startIdx);
const after  = text.slice(endIdx + OLD_END_MARK.length);

const next = before + NEW_BLOCK + OLD_END_MARK + after;

fs.writeFileSync(TARGET, next, 'utf8');

console.log('✅ patched G9 → U1-U14 (旧版全一册完整)');
console.log('  OLD 区段: 行', Math.floor(text.slice(0, startIdx).split('\n').length),
            '→ 行', Math.floor(text.slice(0, endIdx).split('\n').length));
console.log('  OLD len:', endIdx - startIdx + OLD_END_MARK.length, '字节');
console.log('  NEW_BLOCK 字节:', NEW_BLOCK.length);
console.log('  最后 unit: U14');
