// scripts/patch_g7x.mjs
// PEP 2024 秋新版七年级下册（初一下）整段重做
// 用户 2026-09-05 拍 13 张截图：
//   - 2 张 CONTENTS（II-V + V-底部，8 Unit 标题 + 附录页码）
//   - 8 张 Vocabulary in Each Unit P97-105（U1-U8 全部词条，含专有名词）
// 旧结构（Go for it 2012 旧版）：G7U10/11/12（精简版，每单元 10 词）
// 新结构（PEP 2024 秋新版）：8 个正式 Unit
//   U1  Animal Friends
//   U2  No Rules, No Order
//   U3  Keep Fit
//   U4  Eat Well
//   U5  Here and Now
//   U6  Rain or Shine
//   U7  A Day to Remember
//   U8  Once upon a Time
//
// 单元编号延续 G7 上：上册 U1-U10 ⇒ 下册 U11-U18。
// 旧 G7 下段 3 个 unit (U10/11/12) ⇒ 新 8 个 unit (U11-U18)。
//
// OLD_END_MARK 设计原则（用上轮 G7 patch 教训）：
//   仅含衔接处下段注释起点（不含闭合括号）；NEW_BLOCK 末尾自带 \n  },\n

import fs from 'node:fs';

const FILE = 'src/data/grades4to9.ts';
const OLD_START_MARK = `  // ==================== 七年级下（Go for it 七下 U1-3） ====================
`;
const OLD_END_MARK = `  // ==================== 八年级上（Go for it 八上全册） ====================
`;

const NEW_BLOCK = `  // ==================== 七年级下（PEP 2024 秋新版 · 8 Unit） ====================
  // 数据来源：用户 2026-09-05 拍 13 张（CONTENTS II-V + Vocabulary in Each Unit P97-105）
  // 旧版（Go for it 2012）精简版 3 个 unit 整体替换为新版 8 个 unit
  {
    grade: 7,
    unit: 11,
    title: "Animal Friends 动物朋友们",
    entries: [
      mk(7, 11, "word", "fox", "/fɑːks/", "n. 狐狸"),
      mk(7, 11, "word", "giraffe", "/dʒəˈræf/", "n. 长颈鹿"),
      mk(7, 11, "word", "eagle", "/ˈiːɡəl/", "n. 雕；鹰"),
      mk(7, 11, "word", "wolf", "/wʊlf/", "n. (pl wolves) 狼"),
      mk(7, 11, "word", "penguin", "/ˈpeŋɡwɪn/", "n. 企鹅"),
      mk(7, 11, "word", "care", "/ker/", "n. 照顾；护理；v. 关心；在乎"),
      mk(7, 11, "phrase", "take care of", "/teɪk ker əv/", "照顾；处理"),
      mk(7, 11, "word", "sandwich", "/ˈsænwɪtʃ/", "n. 三明治"),
      mk(7, 11, "word", "snake", "/sneɪk/", "n. 蛇"),
      mk(7, 11, "word", "scary", "/ˈskeri/", "adj. 吓人的；恐怖的"),
      mk(7, 11, "word", "neck", "/nek/", "n. 脖子"),
      mk(7, 11, "word", "guess", "/ɡes/", "v. 猜测；估计"),
      mk(7, 11, "word", "shark", "/ʃɑːrk/", "n. 鲨鱼"),
      mk(7, 11, "word", "whale", "/weɪl/", "n. 鲸"),
      mk(7, 11, "word", "huge", "/hjuːdʒ/", "adj. 巨大的；极多的"),
      mk(7, 11, "word", "dangerous", "/ˈdeɪndʒərəs/", "adj. 危险的；有危害的"),
      mk(7, 11, "word", "save", "/seɪv/", "v. 救；储蓄；保存"),
      mk(7, 11, "word", "luck", "/lʌk/", "n. 幸运；运气"),
      mk(7, 11, "word", "Thai", "/taɪ/", "adj. 泰国的；泰国人的；n. 泰国人；泰语"),
      mk(7, 11, "word", "trunk", "/trʌŋk/", "n. 象鼻"),
      mk(7, 11, "word", "pick", "/pɪk/", "v. 捡；摘"),
      mk(7, 11, "phrase", "pick up", "/pɪk ʌp/", "捡起；举起；搭载"),
      mk(7, 11, "word", "carry", "/ˈkæri/", "v. 拿；提；搬"),
      mk(7, 11, "word", "playful", "/ˈpleɪfəl/", "adj. 爱嬉戏的；爱玩的"),
      mk(7, 11, "word", "swimmer", "/ˈswɪmər/", "n. 游泳者"),
      mk(7, 11, "phrase", "one another", "/wʌn əˈnʌðər/", "互相"),
      mk(7, 11, "phrase", "look after", "/lʊk ˈæftər/", "照顾"),
      mk(7, 11, "word", "culture", "/ˈkʌltʃər/", "n. 文化；文明"),
      mk(7, 11, "word", "however", "/haʊˈevər/", "adv. 然而；不过"),
      mk(7, 11, "word", "danger", "/ˈdeɪndʒər/", "n. 危险"),
      mk(7, 11, "phrase", "in danger", "/ɪn ˈdeɪndʒər/", "处于危险之中"),
      mk(7, 11, "word", "forest", "/ˈfɔːrɪst/", "n. 森林"),
      mk(7, 11, "phrase", "cut down", "/kʌt daʊn/", "砍伐；减少"),
      mk(7, 11, "phrase", "too many", "/tuː ˈmeni/", "太多"),
      mk(7, 11, "word", "kill", "/kɪl/", "v. 杀死；弄死"),
      mk(7, 11, "word", "ivory", "/ˈaɪvəri/", "n. 象牙"),
      mk(7, 11, "phrase", "made of", "/meɪd əv/", "由……制成的"),
      mk(7, 11, "word", "friendly", "/ˈfrendli/", "adj. 友好的"),
      mk(7, 11, "word", "quite", "/kwaɪt/", "adv. 相当；完全"),
      mk(7, 11, "phrase", "quite a", "/kwaɪt ə/", "相当；非寻常"),
      mk(7, 11, "phrase", "not ... at all", "/nɑːt ... ət ɔːl/", "一点也不；完全不"),
      mk(7, 11, "word", "fur", "/fɜːr/", "n. (动物柔厚的) 软毛"),
      mk(7, 11, "word", "blind", "/blaɪnd/", "adj. 瞎的；失明的"),
      mk(7, 11, "word", "hearing", "/ˈhɪrɪŋ/", "n. 听力；听觉"),
      mk(7, 11, "word", "Antarctica", "/ænˈtɑːrktɪkə/", "n. 南极洲"),
      mk(7, 11, "word", "Africa", "/ˈæfrɪkə/", "n. 非洲"),
      mk(7, 11, "word", "Malee", "/mɑːˈliː/", "n. 马利"),
      mk(7, 11, "word", "Thailand", "/ˈtaɪlænd/", "n. 泰国"),
    ],
  },
  {
    grade: 7,
    unit: 12,
    title: "No Rules, No Order 没有规矩，不成方圆",
    entries: [
      mk(7, 12, "word", "rule", "/ruːl/", "n. 规则；规章"),
      mk(7, 12, "word", "order", "/ˈɔːrdər/", "n. 秩序；命令；v. 点菜；命令"),
      mk(7, 12, "word", "follow", "/ˈfɑːloʊ/", "v. 遵循；跟随"),
      mk(7, 12, "phrase", "late for", "/leɪt fɔːr/", "迟到"),
      mk(7, 12, "word", "arrive", "/əˈraɪv/", "v. 到达"),
      mk(7, 12, "phrase", "on time", "/ɑːn taɪm/", "准时"),
      mk(7, 12, "word", "hallway", "/ˈhɔːlweɪ/", "n. 走廊"),
      mk(7, 12, "word", "uniform", "/ˈjuːnɪfɔːrm/", "n. 校服；制服"),
      mk(7, 12, "word", "litter", "/ˈlɪtər/", "n. 乱扔；v. 乱扔；n. 垃圾"),
      mk(7, 12, "word", "polite", "/pəˈlaɪt/", "adj. 有礼貌的"),
      mk(7, 12, "word", "treat", "/triːt/", "v. 对待；招待；治疗；n. 款待"),
      mk(7, 12, "word", "respect", "/rɪˈspekt/", "n. & v. 尊敬"),
      mk(7, 12, "word", "if", "/ɪf/", "conj. 如果"),
      mk(7, 12, "word", "jacket", "/ˈdʒækɪt/", "n. 夹克衫；短上衣"),
      mk(7, 12, "phrase", "have to", "/hæv tuː/", "不得不"),
      mk(7, 12, "word", "everything", "/ˈevriθɪŋ/", "pron. 每件事；一切"),
      mk(7, 12, "word", "lend", "/lend/", "v. 借给；借出"),
      mk(7, 12, "word", "sweet", "/swiːt/", "n. 糖果；adj. 甜的"),
      mk(7, 12, "word", "snack", "/snæk/", "n. 点心；小吃"),
      mk(7, 12, "phrase", "of course", "/əv kɔːrs/", "当然"),
      mk(7, 12, "word", "mobile", "/ˈmoʊbəl/", "adj. 可移动的"),
      mk(7, 12, "word", "mobile phone", "/ˈmoʊbəl foʊn/", "手机"),
      mk(7, 12, "phrase", "turn off", "/tɜːrn ɔːf/", "关掉（水、电或煤气）"),
      mk(7, 12, "word", "queue", "/kjuː/", "n. 队"),
      mk(7, 12, "phrase", "jump the queue", "/dʒʌmp ðə kjuː/", "插队"),
      mk(7, 12, "word", "feed", "/fiːd/", "v. 喂养；饲养"),
      mk(7, 12, "word", "leave", "/liːv/", "v. 离开；留下"),
      mk(7, 12, "word", "absent", "/ˈæbsənt/", "adj. 缺席的；不在的"),
      mk(7, 12, "phrase", "absent from", "/ˈæbsənt frəm/", "缺席；不在"),
      mk(7, 12, "word", "shh", "/ʃ/", "(= sh) interj. 嘘（用以让别人安静下来）"),
      mk(7, 12, "word", "quietly", "/ˈkwaɪətli/", "adv. 轻声地；安静地"),
      mk(7, 12, "phrase", "put on", "/pʊt ɑːn/", "穿上；戴上；增加"),
      mk(7, 12, "word", "belt", "/belt/", "n. 安全带；腰带；皮带"),
      mk(7, 12, "word", "noise", "/nɔɪz/", "n. 声音；噪声"),
      mk(7, 12, "word", "unhappy", "/ʌnˈhæpi/", "adj. 不快乐的"),
      mk(7, 12, "word", "Dr", "/dɑːktər/", "(= doctor) n. 博士；医生"),
      mk(7, 12, "phrase", "make one's bed", "/meɪk wʌnz bed/", "整理床铺；铺床"),
      mk(7, 12, "word", "either", "/ˈaɪðər/", "adv. 也（用于否定句组后）"),
      mk(7, 12, "word", "practise", "/ˈpræktɪs/", "v. 训练；练习"),
      mk(7, 12, "word", "hang", "/hæŋ/", "v. 悬挂"),
      mk(7, 12, "phrase", "hang out", "/hæŋ aʊt/", "闲逛；带去某处"),
      mk(7, 12, "word", "weekday", "/ˈwiːkdeɪ/", "n. 工作日（星期一至星期五的任何一天）"),
      mk(7, 12, "word", "awful", "/ˈɔːfəl/", "adj. 糟糕的；讨厌的"),
      mk(7, 12, "word", "become", "/bɪˈkʌm/", "v. 变成；成为"),
      mk(7, 12, "word", "better", "/ˈbetər/", "adj. 较好的；adv. 更好地"),
      mk(7, 12, "word", "person", "/ˈpɜːrsən/", "n. 人"),
      mk(7, 12, "word", "focus", "/ˈfoʊkəs/", "v. 集中（注意力、精力等）；聚焦"),
      mk(7, 12, "phrase", "focus on", "/ˈfoʊkəs ɑːn/", "集中（注意力、精力等）于"),
      mk(7, 12, "word", "build", "/bɪld/", "v. 建造；建筑"),
      mk(7, 12, "word", "spirit", "/ˈspɪrɪt/", "n. 精神；情绪"),
      mk(7, 12, "phrase", "think about", "/θɪŋk əˈbaʊt/", "思考；考虑"),
      mk(7, 12, "word", "relax", "/rɪˈlæks/", "v. 放松；休息"),
      mk(7, 12, "word", "advice", "/ədˈvaɪs/", "n. 建议；意见"),
      mk(7, 12, "word", "understand", "/ˌʌndərˈstænd/", "v. 理解；领会"),
      mk(7, 12, "word", "untidy", "/ʌnˈtaɪdi/", "adj. 不整洁的"),
      mk(7, 12, "word", "Mary", "/ˈmeri/", "n. 玛丽"),
      mk(7, 12, "word", "Tony", "/ˈtoʊni/", "n. 托尼"),
      mk(7, 12, "word", "Anne", "/æn/", "n. 安妮"),
      mk(7, 12, "word", "Eric", "/ˈerɪk/", "n. 埃里克"),
    ],
  },
  {
    grade: 7,
    unit: 13,
    title: "Keep Fit 保持健康",
    entries: [
      mk(7, 13, "word", "fit", "/fɪt/", "adj. 健康的；健壮的；v. 适合"),
      mk(7, 13, "word", "baseball", "/ˈbeɪsbɔːl/", "n. 棒球（运动）"),
      mk(7, 13, "word", "glove", "/ɡlʌv/", "n. (手指分开的) 手套"),
      mk(7, 13, "word", "mat", "/mæt/", "n. 垫子"),
      mk(7, 13, "word", "rope", "/roʊp/", "n. 绳子；粗绳"),
      mk(7, 13, "phrase", "jump rope", "/dʒʌmp roʊp/", "跳绳用的绳子；跳绳（运动）"),
      mk(7, 13, "word", "racket", "/ˈrækɪt/", "n. (网球、羽毛球等的) 球拍"),
      mk(7, 13, "word", "hardly", "/ˈhɑːrdli/", "adv. 几乎不；几乎没有"),
      mk(7, 13, "word", "ever", "/ˈevər/", "adv. 在任何时候；曾经；从来"),
      mk(7, 13, "phrase", "hardly ever", "/ˈhɑːrdli ˈevər/", "几乎从不"),
      mk(7, 13, "word", "once", "/wʌns/", "adv. 一次；曾经；conj. 一旦"),
      mk(7, 13, "word", "twice", "/twaɪs/", "adv. 两次；两倍"),
      mk(7, 13, "word", "mine", "/maɪn/", "pron. 我的（所有物）"),
      mk(7, 13, "word", "hers", "/hɜːrz/", "pron. 她的（所有物）"),
      mk(7, 13, "word", "maybe", "/ˈmeɪbi/", "adv. 也许；大概"),
      mk(7, 13, "word", "well-used", "/ˌwel ˈjuːzd/", "adj. 使用得多的"),
      mk(7, 13, "word", "practice", "/ˈpræktɪs/", "n. 练习；实践"),
      mk(7, 13, "word", "perfect", "/ˈpɜːrfɪkt/", "adj. 完美的；极好的"),
      mk(7, 13, "word", "seldom", "/ˈseldəm/", "adv. 很少；不常"),
      mk(7, 13, "word", "badminton", "/ˈbædmɪntən/", "n. 羽毛球运动"),
      mk(7, 13, "word", "double", "/ˈdʌbəl/", "n. 双打（doubles）；两倍；adj. 成双的；两倍的"),
      mk(7, 13, "word", "sometime", "/ˈsʌmtaɪm/", "adv. 在某个时候"),
      mk(7, 13, "word", "volleyball", "/ˈvɑːlibɔːl/", "n. 排球（运动）"),
      mk(7, 13, "word", "theirs", "/ðerz/", "pron. 他们的，她们的，它们的（所有物）"),
      mk(7, 13, "word", "ours", "/aʊərz/", "pron. 我们的（所有物）"),
      mk(7, 13, "word", "jog", "/dʒɑːɡ/", "v. 慢跑"),
      mk(7, 13, "word", "few", "/fjuː/", "adj. (表示否定的) 很少的；几乎没有的"),
      mk(7, 13, "phrase", "a few", "/ə fjuː/", "少数；几个"),
      mk(7, 13, "word", "excuse", "/ɪkˈskjuːs/", "v. 原谅；宽恕；n. 借口"),
      mk(7, 13, "phrase", "excuse me", "/ɪkˈskjuːs miː/", "劳驾；请原谅"),
      mk(7, 13, "phrase", "over there", "/ˈoʊvər ðer/", "在那一边"),
      mk(7, 13, "word", "just", "/dʒʌst/", "adv. 只是；正好"),
      mk(7, 13, "word", "T-shirt", "/ˈtiː ʃɜːrt/", "n. T恤衫"),
      mk(7, 13, "word", "belong", "/bɪˈlɔːŋ/", "v. 应在（某处）"),
      mk(7, 13, "phrase", "belong to", "/bɪˈlɔːŋ tuː/", "属于（某人）"),
      mk(7, 13, "word", "working", "/ˈwɜːrkɪŋ/", "adj. 工作的"),
      mk(7, 13, "phrase", "working day", "/ˈwɜːrkɪŋ deɪ/", "工作日"),
      mk(7, 13, "phrase", "full of", "/fʊl əv/", "有许多；充满"),
      mk(7, 13, "word", "energy", "/ˈenərdʒi/", "n. 精力；能量"),
      mk(7, 13, "word", "group", "/ɡruːp/", "n. 组；群"),
      mk(7, 13, "word", "skateboard", "/ˈskeɪtbɔːrd/", "n. 滑板"),
      mk(7, 13, "word", "encourage", "/ɪnˈkɜːrɪdʒ/", "v. 鼓励；激励"),
      mk(7, 13, "word", "trick", "/trɪk/", "n. 技巧；戏法"),
      mk(7, 13, "word", "succeed", "/səkˈsiːd/", "v. 成功；达到目标"),
      mk(7, 13, "word", "skateboarding", "/ˈskeɪtbɔːrdɪŋ/", "n. 滑板运动"),
      mk(7, 13, "word", "goal", "/ɡoʊl/", "n. 目标；目的"),
      mk(7, 13, "word", "sit-up", "/ˈsɪt ʌp/", "n. 仰卧起坐"),
      mk(7, 13, "phrase", "work out", "/wɜːrk aʊt/", "锻炼"),
      mk(7, 13, "word", "app", "/æp/", "(= application) n. 应用程序"),
      mk(7, 13, "word", "progress", "/ˈprɑːɡres/", "n. 进步；进展"),
      mk(7, 13, "word", "match", "/mætʃ/", "n. 比赛；竞赛"),
      mk(7, 13, "word", "team", "/tiːm/", "n. 队；组"),
      mk(7, 13, "word", "lose", "/luːz/", "v. 输掉；丢失"),
      mk(7, 13, "word", "teenager", "/ˈtiːneɪdʒər/", "n. 青少年"),
      mk(7, 13, "word", "Steve", "/stiːv/", "n. 史蒂夫"),
    ],
  },
  {
    grade: 7,
    unit: 14,
    title: "Eat Well 吃得健康",
    entries: [
      mk(7, 14, "word", "watermelon", "/ˈwɔːtərˌmelən/", "n. 西瓜"),
      mk(7, 14, "word", "cabbage", "/ˈkæbɪdʒ/", "n. 卷心菜"),
      mk(7, 14, "word", "mutton", "/ˈmʌtən/", "n. 羊肉"),
      mk(7, 14, "word", "cookie", "/ˈkʊki/", "n. 曲奇饼"),
      mk(7, 14, "word", "onion", "/ˈʌnjən/", "n. 洋葱；葱头"),
      mk(7, 14, "word", "dumpling", "/ˈdʌmplɪŋ/", "n. 饺子"),
      mk(7, 14, "word", "coffee", "/ˈkɔːfi/", "n. 咖啡"),
      mk(7, 14, "word", "bean", "/biːn/", "n. 豆"),
      mk(7, 14, "word", "chip", "/tʃɪp/", "n. 炸薯条"),
      mk(7, 14, "phrase", "fish and chips", "/fɪʃ ənd tʃɪps/", "炸鱼薯条"),
      mk(7, 14, "word", "salad", "/ˈsæləd/", "n. 沙拉；色拉"),
      mk(7, 14, "word", "porridge", "/ˈpɔːrɪdʒ/", "n. 粥；麦片粥"),
      mk(7, 14, "word", "waiter", "/ˈweɪtər/", "n. (男) 服务员"),
      mk(7, 14, "phrase", "What about ...?", "/wʌt əˈbaʊt/", "……怎么样？"),
      mk(7, 14, "word", "taste", "/teɪst/", "v. 有……味道；尝；n. 味道"),
      mk(7, 14, "word", "anything", "/ˈeniθɪŋ/", "pron. 某事物；任何事物"),
      mk(7, 14, "word", "dish", "/dɪʃ/", "n. 道菜；盘子"),
      mk(7, 14, "word", "choice", "/tʃɔɪs/", "n. 选择"),
      mk(7, 14, "word", "meal", "/miːl/", "n. 一餐所吃的食物；一顿"),
      mk(7, 14, "word", "pork", "/pɔːrk/", "n. 猪肉"),
      mk(7, 14, "word", "strawberry", "/ˈstrɔːberi/", "n. 草莓"),
      mk(7, 14, "word", "menu", "/ˈmenjuː/", "n. 菜单"),
      mk(7, 14, "word", "customer", "/ˈkʌstəmər/", "n. 顾客"),
      mk(7, 14, "word", "serve", "/sɜːrv/", "v. 提供；服务"),
      mk(7, 14, "word", "waitress", "/ˈweɪtrəs/", "n. 女服务员"),
      mk(7, 14, "word", "sir", "/sɜːr/", "n. 先生"),
      mk(7, 14, "word", "bill", "/bɪl/", "n. 账单；钞票"),
      mk(7, 14, "phrase", "go with", "/ɡoʊ wɪð/", "搭配；相配"),
      mk(7, 14, "word", "instead", "/ɪnˈsted/", "adv. 反而；代替"),
      mk(7, 14, "word", "pear", "/per/", "n. 梨"),
      mk(7, 14, "phrase", "too much", "/tuː mʌtʃ/", "太多"),
      mk(7, 14, "word", "sugar", "/ˈʃʊɡər/", "n. 糖"),
      mk(7, 14, "word", "newsletter", "/ˈnuːzˌletər/", "n. 内部通讯；简讯"),
      mk(7, 14, "word", "improve", "/ɪmˈpruːv/", "v. 改进；改善"),
      mk(7, 14, "word", "habit", "/ˈhæbɪt/", "n. 习惯"),
      mk(7, 14, "phrase", "fast food", "/fæst fuːd/", "快餐"),
      mk(7, 14, "word", "salt", "/sɔːlt/", "n. 盐"),
      mk(7, 14, "word", "fat", "/fæt/", "n. 脂肪；adj. 肥胖的"),
      mk(7, 14, "word", "weight", "/weɪt/", "n. 体重；重量"),
      mk(7, 14, "word", "hamburger", "/ˈhæmbɜːrɡər/", "n. 汉堡包"),
      mk(7, 14, "word", "cause", "/kɔːz/", "v. 造成；导致"),
      mk(7, 14, "word", "heart", "/hɑːrt/", "n. 心脏；中心"),
      mk(7, 14, "word", "balanced", "/ˈbælənst/", "adj. 均衡的；平衡的"),
      mk(7, 14, "phrase", "too ... to ...", "/tuː ... tuː/", "太……以至于不能"),
      mk(7, 14, "word", "sleepy", "/ˈsliːpi/", "adj. 困倦的；想睡的"),
      mk(7, 14, "phrase", "after all", "/ˈæftər ɔːl/", "毕竟；终究"),
      mk(7, 14, "word", "away", "/əˈweɪ/", "adv. 离开；在别处"),
      mk(7, 14, "word", "poor", "/pʊr/", "adj. 不好的；贫穷的；可怜的"),
      mk(7, 14, "word", "result", "/rɪˈzʌlt/", "n. 后果；结果"),
      mk(7, 14, "word", "article", "/ˈɑːrtɪkəl/", "n. 文章；冠词"),
      mk(7, 14, "word", "common", "/ˈkɑːmən/", "adj. 共同的；普通的"),
      mk(7, 14, "word", "among", "/əˈmʌŋ/", "prep. 在……中；……之一"),
      mk(7, 14, "word", "soft", "/sɔːft/", "adj. 柔和的；柔软的"),
      mk(7, 14, "phrase", "soft drink", "/sɔːft drɪŋk/", "软饮料（不含酒精）"),
      mk(7, 14, "word", "enough", "/ɪˈnʌf/", "adj. 足够的；充足的；adv. 足够地；充分地；pron. 足够；充分"),
      mk(7, 14, "word", "thirsty", "/ˈθɜːrsti/", "adj. 渴的"),
      mk(7, 14, "word", "Gongbao chicken", "/ˈɡʌŋbaʊ ˈtʃɪkɪn/", "宫保鸡丁"),
      mk(7, 14, "word", "America", "/əˈmerɪkə/", "n. 美国；美洲"),
      mk(7, 14, "word", "Dongpo pork", "/ˈdɑːŋpoʊ pɔːrk/", "东坡肉"),
      mk(7, 14, "word", "Joy Clinic", "/dʒɔɪ ˈklɪnɪk/", "快乐诊所"),
    ],
  },
  {
    grade: 7,
    unit: 15,
    title: "Here and Now 此刻此地",
    entries: [
      mk(7, 15, "phrase", "right now", "/raɪt naʊ/", "现在；立刻"),
      mk(7, 15, "word", "ride", "/raɪd/", "v. 骑；n. 旅程"),
      mk(7, 15, "word", "moment", "/ˈmoʊmənt/", "n. 某个时刻；片刻；瞬间"),
      mk(7, 15, "phrase", "at the moment", "/ət ðə ˈmoʊmənt/", "现在；此刻"),
      mk(7, 15, "phrase", "work on", "/wɜːrk ɑːn/", "做；从事"),
      mk(7, 15, "word", "dragon", "/ˈdræɡən/", "n. 龙"),
      mk(7, 15, "word", "festival", "/ˈfestɪvəl/", "n. 节日"),
      mk(7, 15, "word", "hold", "/hoʊld/", "v. 拿着；抓住"),
      mk(7, 15, "phrase", "hold on", "/hoʊld ɑːn/", "别挂断电话；等一等"),
      mk(7, 15, "word", "voice", "/vɔɪs/", "n. 嗓音；声音"),
      mk(7, 15, "word", "race", "/reɪs/", "n. 比赛；竞赛"),
      mk(7, 15, "word", "darling", "/ˈdɑːrlɪŋ/", "n. 亲爱的；宝贝"),
      mk(7, 15, "word", "somebody", "/ˈsʌmbɑːdi/", "pron. 某人；有人"),
      mk(7, 15, "word", "could", "/kʊd/", "modal v. 能；可以"),
      mk(7, 15, "word", "message", "/ˈmesɪdʒ/", "n. 消息；信息"),
      mk(7, 15, "phrase", "take a message", "/teɪk ə ˈmesɪdʒ/", "捎个口信"),
      mk(7, 15, "phrase", "leave a message", "/liːv ə ˈmesɪdʒ/", "留个口信"),
      mk(7, 15, "phrase", "call back", "/kɔːl bæk/", "回电话"),
      mk(7, 15, "word", "kick", "/kɪk/", "v. 踢；踹"),
      mk(7, 15, "word", "wow", "/waʊ/", "interj. 哇；呀"),
      mk(7, 15, "word", "online", "/ˈɑːnˌlaɪn/", "adj. 在线的"),
      mk(7, 15, "word", "shuttlecock", "/ˈʃʌtlkɑːk/", "n. 羽毛球"),
      mk(7, 15, "word", "sight", "/saɪt/", "n. 名胜；景象；视力"),
      mk(7, 15, "word", "exam", "/ɪɡˈzæm/", "(= examination) n. 考试"),
      mk(7, 15, "word", "hope", "/hoʊp/", "v. & n. 希望"),
      mk(7, 15, "word", "forward", "/ˈfɔːrwərd/", "adv. 向前"),
      mk(7, 15, "phrase", "look forward to", "/lʊk ˈfɔːrwərd tuː/", "盼望"),
      mk(7, 15, "word", "Adam", "/ˈædəm/", "n. 亚当"),
      mk(7, 15, "word", "Dragon Boat Festival", "/ˈdræɡən boʊt ˈfestɪvəl/", "端午节"),
      mk(7, 15, "word", "Beth", "/beθ/", "n. 贝丝"),
    ],
  },
  {
    grade: 7,
    unit: 16,
    title: "Rain or Shine 不论晴雨",
    entries: [
      mk(7, 16, "phrase", "rain or shine", "/reɪn ɔːr ʃaɪn/", "不论是雨或是晴；不管发生什么事"),
      mk(7, 16, "word", "affect", "/əˈfekt/", "v. 影响"),
      mk(7, 16, "word", "dry", "/draɪ/", "adj. 干的；干旱的"),
      mk(7, 16, "word", "lightning", "/ˈlaɪtnɪŋ/", "n. 闪电"),
      mk(7, 16, "word", "stormy", "/ˈstɔːrmi/", "adj. 有暴风雨（或暴风雪）的"),
      mk(7, 16, "word", "north", "/nɔːrθ/", "n. 北部；北；北方"),
      mk(7, 16, "word", "west", "/west/", "n. 西部；西；西方"),
      mk(7, 16, "word", "south", "/saʊθ/", "n. 南部；南；南方"),
      mk(7, 16, "word", "east", "/iːst/", "n. 东部；东；东方"),
      mk(7, 16, "phrase", "stay in", "/steɪ ɪn/", "待在家里；没有外出"),
      mk(7, 16, "word", "lucky", "/ˈlʌki/", "adj. 运气好的；带来好运的"),
      mk(7, 16, "phrase", "lucky you", "/ˈlʌki juː/", "你真幸运"),
      mk(7, 16, "word", "sunbathe", "/ˈsʌnbeɪð/", "v. 沐日光浴；晒太阳"),
      mk(7, 16, "phrase", "some day", "/sʌm deɪ/", "将来；有一天"),
      mk(7, 16, "word", "temperature", "/ˈtemprətʃər/", "n. 温度"),
      mk(7, 16, "word", "snowman", "/ˈsnoʊmæn/", "n. (pl snowmen) 雪人"),
      mk(7, 16, "word", "heavily", "/ˈhevɪli/", "adv. 大量地；沉重地"),
      mk(7, 16, "word", "snowy", "/ˈsnoʊi/", "adj. 下雪的；雪白的"),
      mk(7, 16, "word", "beach volleyball", "/biːtʃ ˈvɑːlibɔːl/", "沙滩排球"),
      mk(7, 16, "word", "high", "/haɪ/", "adv. & adj. 高"),
      mk(7, 16, "word", "freezing", "/ˈfriːzɪŋ/", "adj. 极冷的；冰冻的"),
      mk(7, 16, "word", "tourist", "/ˈtʊrɪst/", "n. 旅行者；观光客"),
      mk(7, 16, "word", "mount", "/maʊnt/", "n. (在现代英语里仅用于地名) 山；山峰"),
      mk(7, 16, "word", "cloud", "/klaʊd/", "n. 云；云彩"),
      mk(7, 16, "phrase", "feel like", "/fiːl laɪk/", "感觉像"),
      mk(7, 16, "word", "magical", "/ˈmædʒɪkəl/", "adj. 魔法的；神奇的"),
      mk(7, 16, "word", "rock", "/rɑːk/", "n. 岩石"),
      mk(7, 16, "word", "rest", "/rest/", "n. 休息；剩余部分"),
      mk(7, 16, "word", "area", "/ˈeriə/", "n. 场地；地区"),
      mk(7, 16, "phrase", "rest area", "/rest ˈeriə/", "休息区"),
      mk(7, 16, "phrase", "make progress", "/meɪk ˈprɑːɡres/", "取得进展"),
      mk(7, 16, "word", "although", "/ɔːlˈðoʊ/", "conj. 虽然；尽管"),
      mk(7, 16, "word", "still", "/stɪl/", "adv. 还；仍然"),
      mk(7, 16, "phrase", "in high spirits", "/ɪn haɪ ˈspɪrɪts/", "情绪高涨；兴高采烈"),
      mk(7, 16, "word", "experience", "/ɪkˈspɪriəns/", "n. 经历；经验；v. 经历"),
      mk(7, 16, "word", "through", "/θruː/", "prep. 穿过；凭借"),
      mk(7, 16, "word", "glad", "/ɡlæd/", "adj. 高兴的"),
      mk(7, 16, "word", "peak", "/piːk/", "n. 山顶；顶点"),
      mk(7, 16, "word", "grey", "/ɡreɪ/", "(AmE gray) adj. 灰色的"),
      mk(7, 16, "phrase", "because of", "/bɪˈkɔːz əv/", "因为"),
      mk(7, 16, "word", "fog", "/fɔːɡ/", "n. 雾"),
      mk(7, 16, "word", "ground", "/ɡraʊnd/", "n. 地面"),
      mk(7, 16, "word", "wet", "/wet/", "adj. 湿的"),
      mk(7, 16, "word", "tiring", "/ˈtaɪrɪŋ/", "adj. 令人疲倦的；累人的"),
      mk(7, 16, "word", "seem", "/siːm/", "v. 似乎；好像"),
      mk(7, 16, "word", "sunlight", "/ˈsʌnlaɪt/", "n. 阳光；日光"),
      mk(7, 16, "phrase", "at the top", "/ət ðə tɑːp/", "在顶部；在顶端"),
      mk(7, 16, "word", "description", "/dɪˈskrɪpʃən/", "n. 描述；说明"),
      mk(7, 16, "word", "mountain", "/ˈmaʊntən/", "n. 山；高山"),
      mk(7, 16, "phrase", "at the start", "/ət ðə stɑːrt/", "开始；起初"),
      mk(7, 16, "word", "end", "/end/", "n. 末尾；结束"),
      mk(7, 16, "phrase", "at the end", "/ət ðə end/", "最后；在末尾"),
      mk(7, 16, "word", "storm", "/stɔːrm/", "n. 暴风雨；暴风雪"),
      mk(7, 16, "word", "pour", "/pɔːr/", "v. 倾倒；倒出"),
      mk(7, 16, "word", "wind", "/wɪnd/", "n. 风"),
      mk(7, 16, "word", "shout", "/ʃaʊt/", "v. & n. 喊叫；呼唤"),
      mk(7, 16, "phrase", "run after", "/rʌn ˈæftər/", "追逐"),
      mk(7, 16, "word", "Anna", "/ˈænə/", "n. 安娜"),
      mk(7, 16, "word", "John", "/dʒɑːn/", "n. 约翰"),
      mk(7, 16, "word", "Stockholm", "/ˈstɑːkhoʊm/", "n. 斯德哥尔摩（瑞典首都）"),
      mk(7, 16, "word", "Mount Huangshan", "/maʊnt ˈhwɑːŋʃɑːn/", "n. 黄山"),
      mk(7, 16, "word", "Bright Peak", "/braɪt piːk/", "n. 光明顶"),
    ],
  },
  {
    grade: 7,
    unit: 17,
    title: "A Day to Remember 难忘的一天",
    entries: [
      mk(7, 17, "phrase", "meet up", "/miːt ʌp/", "碰头；相聚"),
      mk(7, 17, "word", "museum", "/mjuˈziəm/", "n. 博物馆"),
      mk(7, 17, "word", "exhibition", "/ˌeksɪˈbɪʃən/", "n. 展览"),
      mk(7, 17, "word", "direction", "/dəˈrekʃən/", "n. 方向"),
      mk(7, 17, "word", "trip", "/trɪp/", "n. 旅行"),
      mk(7, 17, "word", "wastewater", "/ˈweɪstˌwɔːtər/", "n. 废水"),
      mk(7, 17, "word", "plant", "/plænt/", "n. 工厂；v. 种植"),
      mk(7, 17, "word", "into", "/ˈɪntuː/", "prep. 到……里面；进入"),
      mk(7, 17, "word", "screen", "/skriːn/", "n. 滤网；隔板；屏障"),
      mk(7, 17, "word", "remove", "/rɪˈmuːv/", "v. 移开；拿走"),
      mk(7, 17, "word", "piece", "/piːs/", "n. 片；块"),
      mk(7, 17, "word", "waste", "/weɪst/", "n. 废弃物；v. 浪费"),
      mk(7, 17, "word", "machine", "/məˈʃiːn/", "n. 机器"),
      mk(7, 17, "word", "germ", "/dʒɜːrm/", "n. 微生物；细菌"),
      mk(7, 17, "word", "step", "/step/", "n. 步骤；脚步"),
      mk(7, 17, "phrase", "used to", "/juːst tuː/", "过去常常（做）"),
      mk(7, 17, "word", "realize", "/ˈriːəlaɪz/", "(= realise) v. 认识到；实现"),
      mk(7, 17, "word", "inside", "/ɪnˈsaɪd/", "prep. 在……里面；adv. 在里面"),
      mk(7, 17, "phrase", "go on a trip", "/ɡoʊ ɑːn ə trɪp/", "去旅行"),
      mk(7, 17, "word", "process", "/ˈprɑːses/", "n. 过程"),
      mk(7, 17, "word", "theatre", "/ˈθiːətər/", "n. 戏院；剧场；电影院"),
      mk(7, 17, "word", "factory", "/ˈfæktri/", "n. 工厂"),
      mk(7, 17, "word", "terrible", "/ˈterəbəl/", "adj. 糟糕的"),
      mk(7, 17, "word", "actor", "/ˈæktər/", "n. 演员"),
      mk(7, 17, "word", "gun", "/ɡʌn/", "n. 枪"),
      mk(7, 17, "phrase", "try on", "/traɪ ɑːn/", "试穿"),
      mk(7, 17, "word", "along", "/əˈlɔːŋ/", "prep. 沿着；顺着"),
      mk(7, 17, "word", "road", "/roʊd/", "n. 道路"),
      mk(7, 17, "word", "create", "/kriˈeɪt/", "v. 创造"),
      mk(7, 17, "word", "record", "/rɪˈkɔːrd/", "v. 记录；/ˈrekɔːrd/ n. 记录"),
      mk(7, 17, "word", "thought", "/θɔːt/", "n. 想法"),
      mk(7, 17, "word", "skill", "/skɪl/", "n. 技能"),
      mk(7, 17, "phrase", "write down", "/raɪt daʊn/", "写下；记下"),
      mk(7, 17, "word", "explore", "/ɪkˈsplɔːr/", "v. 探索"),
      mk(7, 17, "word", "tent", "/tent/", "n. 帐篷"),
      mk(7, 17, "word", "cucumber", "/ˈkjuːkʌmbər/", "n. 黄瓜"),
      mk(7, 17, "phrase", "from ... to ...", "/frəm ... tuː/", "从……到……"),
      mk(7, 17, "word", "straight", "/streɪt/", "adv. 直接；立即；adj. 直的；笔直地"),
      mk(7, 17, "word", "fill", "/fɪl/", "v. 装满；盛满"),
      mk(7, 17, "word", "basket", "/ˈbæskɪt/", "n. 篮子；筐"),
      mk(7, 17, "word", "teach", "/tiːtʃ/", "v. (taught) 教"),
      mk(7, 17, "word", "branch", "/bræntʃ/", "n. 分支；树枝"),
      mk(7, 17, "word", "leaf", "/liːf/", "n. (pl leaves) 叶；叶子"),
      mk(7, 17, "word", "finally", "/ˈfaɪnəli/", "adv. 终于"),
      mk(7, 17, "phrase", "think of", "/θɪŋk əv/", "考虑；想起"),
      mk(7, 17, "word", "grain", "/ɡreɪn/", "n. 谷物；谷粒"),
      mk(7, 17, "word", "fresh", "/freʃ/", "adj. 新鲜的"),
      mk(7, 17, "word", "certainly", "/ˈsɜːrtənli/", "adv. 肯定；当然"),
      mk(7, 17, "word", "diary", "/ˈdaɪəri/", "n. 日记；日记本"),
      mk(7, 17, "word", "entry", "/ˈentri/", "n. (日记的) 一则；入口"),
      mk(7, 17, "word", "agree", "/əˈɡriː/", "v. 赞成；同意"),
      mk(7, 17, "phrase", "agree with", "/əˈɡriː wɪð/", "赞成；同意"),
    ],
  },
  {
    grade: 7,
    unit: 18,
    title: "Once upon a Time 从前",
    entries: [
      mk(7, 18, "word", "upon", "/əˈpɑːn/", "prep. 在……上"),
      mk(7, 18, "phrase", "once upon a time", "/wʌns əˈpɑːn ə taɪm/", "从前；很久以前"),
      mk(7, 18, "word", "bite", "/baɪt/", "v. (bit) 咬；咬伤"),
      mk(7, 18, "phrase", "bite through", "/baɪt θruː/", "咬穿"),
      mk(7, 18, "word", "net", "/net/", "n. 网；网状物"),
      mk(7, 18, "word", "hunter", "/ˈhʌntər/", "n. 猎人；搜寻者"),
      mk(7, 18, "word", "promise", "/ˈprɑːmɪs/", "n. 承诺；保证；v. 承诺"),
      mk(7, 18, "phrase", "long ago", "/lɔːŋ əˈɡoʊ/", "很久以前"),
      mk(7, 18, "word", "war", "/wɔːr/", "n. 战争"),
      mk(7, 18, "word", "neighbour", "/ˈneɪbər/", "n. 邻居"),
      mk(7, 18, "word", "wise", "/waɪz/", "adj. 明智的；高明的"),
      mk(7, 18, "word", "emperor", "/ˈempərər/", "n. 皇帝"),
      mk(7, 18, "word", "lie", "/laɪ/", "v. 撒谎；n. 谎言"),
      mk(7, 18, "word", "pretend", "/prɪˈtend/", "v. 假装；伪装"),
      mk(7, 18, "word", "official", "/əˈfɪʃəl/", "n. 官员；高级职员"),
      mk(7, 18, "word", "silly", "/ˈsɪli/", "adj. 愚蠢的；傻的"),
      mk(7, 18, "word", "decide", "/dɪˈsaɪd/", "v. 决定"),
      mk(7, 18, "word", "praise", "/preɪz/", "v. & n. 赞美；表扬"),
      mk(7, 18, "word", "afraid", "/əˈfreɪd/", "adj. 害怕的；担心的"),
      mk(7, 18, "word", "suddenly", "/ˈsʌdənli/", "adv. 突然地；出乎意料地"),
      mk(7, 18, "phrase", "at first", "/ət fɜːrst/", "起初；最初"),
      mk(7, 18, "word", "truth", "/truːθ/", "n. 真相；事实"),
      mk(7, 18, "phrase", "tell the truth", "/tel ðə truːθ/", "说实话"),
      mk(7, 18, "phrase", "make money", "/meɪk ˈmʌni/", "赚钱"),
      mk(7, 18, "word", "true", "/truː/", "adj. 符合事实的；真正的"),
      mk(7, 18, "word", "hate", "/heɪt/", "v. 不喜欢；厌恶；讨厌"),
      mk(7, 18, "phrase", "get out", "/ɡet aʊt/", "逃脱；离开"),
      mk(7, 18, "word", "king", "/kɪŋ/", "n. 君主；国王"),
      mk(7, 18, "word", "artist", "/ˈɑːrtɪst/", "n. 美术家；艺术家"),
      mk(7, 18, "word", "quickly", "/ˈkwɪkli/", "adv. 快速地；很快"),
      mk(7, 18, "word", "smile", "/smaɪl/", "v. 微笑；n. 微笑；笑容"),
      mk(7, 18, "phrase", "all over", "/ɔːl ˈoʊvər/", "到处；遍及"),
      mk(7, 18, "word", "ugly", "/ˈʌɡli/", "adj. 丑陋的；难看的"),
      mk(7, 18, "word", "duckling", "/ˈdʌklɪŋ/", "n. 小鸭子"),
      mk(7, 18, "word", "real", "/riːəl/", "adj. 真的；真正的"),
      mk(7, 18, "phrase", "laugh at", "/læf æt/", "嘲笑"),
      mk(7, 18, "phrase", "go away", "/ɡoʊ əˈweɪ/", "走开"),
      mk(7, 18, "word", "search", "/sɜːrtʃ/", "v. 寻找；搜寻"),
      mk(7, 18, "phrase", "search for", "/sɜːrtʃ fɔːr/", "寻找"),
      mk(7, 18, "word", "hen", "/hen/", "n. 母鸡"),
      mk(7, 18, "word", "hopefully", "/ˈhoʊpfəli/", "adv. 有希望地"),
      mk(7, 18, "word", "purr", "/pɜːr/", "v. (猫) 发出呼噜声"),
      mk(7, 18, "word", "lay", "/leɪ/", "v. (laid) 下（蛋）；放置；搁"),
      mk(7, 18, "word", "swan", "/swɑːn/", "n. 天鹅"),
      mk(7, 18, "word", "feather", "/ˈfeðər/", "n. 羽毛"),
      mk(7, 18, "phrase", "to one's surprise", "/tuː wʌnz sərˈpraɪz/", "出乎某人的意料"),
      mk(7, 18, "word", "size", "/saɪz/", "n. 大小；尺寸"),
      mk(7, 18, "phrase", "only if", "/ˈoʊnli ɪf/", "只有"),
      mk(7, 18, "word", "fisherman", "/ˈfɪʃərmən/", "n. (pl fishermen) 渔夫"),
      mk(7, 18, "word", "fishing", "/ˈfɪʃɪŋ/", "n. 钓鱼；捕鱼"),
      mk(7, 18, "phrase", "come out", "/kʌm aʊt/", "出现；盛开"),
      mk(7, 18, "word", "genie", "/ˈdʒiːni/", "n. 妖怪；鬼"),
      mk(7, 18, "word", "die", "/daɪ/", "v. 死亡；消失"),
      mk(7, 18, "phrase", "make a promise", "/meɪk ə ˈprɑːmɪs/", "许下诺言"),
      mk(7, 18, "word", "someone", "/ˈsʌmwʌn/", "pron. 某人；有人"),
      mk(7, 18, "word", "set", "/set/", "v. 使处于某种状况；使开始"),
      mk(7, 18, "phrase", "set ... free", "/set ... friː/", "释放"),
      mk(7, 18, "word", "rich", "/rɪtʃ/", "adj. 富裕的；富含……的"),
      mk(7, 18, "word", "powerful", "/ˈpaʊərfəl/", "adj. 强大的；有影响力的"),
      mk(7, 18, "word", "anyone", "/ˈeniwʌn/", "pron. 任何人；某个人"),
      mk(7, 18, "word", "instead", "/ɪnˈsted/", "adv. 而不是；代替"),
      mk(7, 18, "phrase", "succeed in doing sth", "/səkˈsiːd ɪn ˈduːɪŋ sʌmθɪŋ/", "成功做成某事"),
      mk(7, 18, "word", "himself", "/hɪmˈself/", "pron. 他自己；他本人"),
      mk(7, 18, "phrase", "in the end", "/ɪn ði end/", "最后；终究"),
      mk(7, 18, "word", "Hans Christian Andersen", "/hɑːnz ˈkrɪstʃən ˈændərsən/", "汉斯·克里斯蒂安·安徒生"),
    ],
  },
` + OLD_END_MARK;

const src = fs.readFileSync(FILE, 'utf8');
const startIdx = src.indexOf(OLD_START_MARK);
if (startIdx === -1) { console.error('OLD_START_MARK not found'); process.exit(1); }
const endIdx = src.indexOf(OLD_END_MARK, startIdx);
if (endIdx === -1) { console.error('OLD_END_MARK not found'); process.exit(1); }

const before = src.slice(0, startIdx);
const after = src.slice(endIdx + OLD_END_MARK.length);  // 必加长度，否则 OLD_END_MARK 自身残留
const next = before + NEW_BLOCK + after;
fs.writeFileSync(FILE, next);
console.log('patched. before chars:', before.length, '/ after chars:', after.length, '/ total delta:', next.length - src.length);
