/**
 * 一次性替换 G6U1-6 为 PEP 六上 2024 秋新版。
 * OLD_START_MARK = G6 起点注释；OLD_END_MARK = "六年级下" 注释（保留 G6U7-10 不动）。
 */
import { readFileSync, writeFileSync } from "node:fs";

const NEW_BLOCK = `  // ==================== 六年级上（PEP 六上 2024 秋新版） ====================
  //   6 Unit + Appendix 2/3/4/5 (Songs/Irregular verbs 本轮未录)
  //   2026-09-04 用户按官方教材逐词录入。
  {
    grade: 6,
    unit: 1,
    title: "Amazing places 神奇的地方",
    entries: [
      mk(6, 1, "word", "was", "/wɒz/", "v. be 的第一和第三人称单数过去式"),
      mk(6, 1, "word", "climb", "/klaɪm/", "v. 攀登；爬"),
      mk(6, 1, "word", "kilometre", "/kɪˈlɒmɪtə(r)/", "n. (=km) 千米；公里"),
      mk(6, 1, "phrase", "gingerbread house", "/ˈdʒɪndʒəbred haʊs/", "姜饼屋"),
      mk(6, 1, "word", "send", "/send/", "v. 邮寄；发送"),
      mk(6, 1, "word", "go", "/ɡəʊ/", "v. (过去式 went) 去；走"),
      mk(6, 1, "word", "thousand", "/ˈθaʊznd/", "num. 一千"),
      mk(6, 1, "word", "clay", "/kleɪ/", "n. 黏土；陶土"),
      mk(6, 1, "word", "see", "/siː/", "v. (过去式 saw) 看见"),
      mk(6, 1, "word", "village", "/ˈvɪlɪdʒ/", "n. 村庄；村镇"),
      mk(6, 1, "word", "eat", "/iːt/", "v. (过去式 ate) 吃"),
      mk(6, 1, "word", "dry", "/draɪ/", "adj. 干的"),
      mk(6, 1, "word", "take", "/teɪk/", "v. (过去式 took) 做（某个动作）；和名词连用代替某个动词"),
      mk(6, 1, "word", "view", "/vjuː/", "n. 景色"),
      mk(6, 1, "word", "inspiring", "/ɪnˈspaɪərɪŋ/", "adj. 鼓舞人心的"),
      mk(6, 1, "word", "bamboo", "/ˌbæmˈbuː/", "n. 竹；竹子"),
      mk(6, 1, "word", "pumpkin", "/ˈpʌmpkɪn/", "n. 南瓜"),
      mk(6, 1, "word", "restaurant", "/ˈrestrɒnt/", "n. 餐馆；餐厅"),
      mk(6, 1, "word", "airport", "/ˈeəpɔːt/", "n. 机场"),
      mk(6, 1, "word", "New Zealand", "/ˌnjuː ˈziːlənd/", "n. 新西兰"),
      mk(6, 1, "phrase", "Hong Kong-Zhuhai-Macao Bridge", "/ˈhɒŋ ˈkɒŋ-ˈzuːˌhaɪ məˈkaʊ ˈbrɪdʒ/", "港珠澳大桥"),
      mk(6, 1, "word", "Paris", "/ˈpærɪs/", "n. 巴黎"),
      mk(6, 1, "phrase", "Eiffel Tower", "/ˈaɪfl ˈtaʊə(r)/", "埃菲尔铁塔"),
      mk(6, 1, "phrase", "Terracotta Warriors", "/ˌterəˈkɒtə ˈwɒriəz/", "兵马俑"),
      mk(6, 1, "phrase", "Jinggangshan Revolution Museum", "/dʒɪŋˌɡæŋʃɑːn ˌrevəˈluːʃn mjuːˈziːəm/", "井冈山革命博物馆"),
      mk(6, 1, "word", "the Red Army", "/ðə red ˈɑːmi/", "红军"),
      mk(6, 1, "sentence", "How was your weekend?", "", "你周末过得怎么样？"),
      mk(6, 1, "sentence", "It was great! I climbed the Great Wall.", "", "非常棒！我去爬长城了。"),
      mk(6, 1, "sentence", "What did you do, Leo?", "", "你做什么了，利奥？"),
      mk(6, 1, "sentence", "I visited the \\"Gingerbread House\\" last Saturday.", "", "我上个星期六去参观\\"姜饼屋\\"了。"),
      mk(6, 1, "sentence", "Where did you go over the summer holidays, Binbin?", "", "你暑假去哪儿了，斌斌？"),
      mk(6, 1, "sentence", "I went to Xi'an with my family.", "", "我和家人去西安了。"),
      mk(6, 1, "sentence", "What did you do there?", "", "你们在那儿做了些什么？"),
      mk(6, 1, "sentence", "We went to see the Terracotta Warriors.", "", "我们去看兵马俑了。"),
      mk(6, 1, "sentence", "What else did you do?", "", "你们还做什么了？"),
      mk(6, 1, "sentence", "It was great!", "", "非常棒！"),
      mk(6, 1, "sentence", "Did you take a trip?", "", "你们去旅行了吗？"),
      mk(6, 1, "sentence", "No, we didn't.", "", "不，我们没有。"),
      mk(6, 1, "sentence", "Did you eat mooncakes?", "", "你们吃月饼了吗？"),
      mk(6, 1, "sentence", "Yes, we did.", "", "是的，我们吃了。"),
      mk(6, 1, "sentence", "My mother and I went to a marathon on Sunday.", "", "我和妈妈上周日去看了一场马拉松比赛。"),
      mk(6, 1, "sentence", "What did you like about it?", "", "你喜欢它哪一点？"),
      mk(6, 1, "sentence", "I liked watching the runners.", "", "我喜欢看参赛者（跑步）。"),
      mk(6, 1, "sentence", "What did you do last weekend?", "", "你上周末做什么了？"),
    ],
  },
  {
    grade: 6,
    unit: 2,
    title: "Getting together 相聚",
    entries: [
      mk(6, 2, "word", "paste", "/peɪst/", "v. 粘贴"),
      mk(6, 2, "word", "dress", "/dres/", "v. 穿衣服"),
      mk(6, 2, "word", "gala", "/ˈɡɑːlə/", "n. 演出；庆典"),
      mk(6, 2, "phrase", "count down", "/kaʊnt daʊn/", "倒计时"),
      mk(6, 2, "word", "marathon", "/ˈmærəθən/", "n. 马拉松赛跑"),
      mk(6, 2, "word", "as", "/æz/", "prep. 作为"),
      mk(6, 2, "word", "race", "/reɪs/", "n. 赛跑；速度竞赛"),
      mk(6, 2, "word", "run", "/rʌn/", "v. (过去式 ran) 跑；奔跑"),
      mk(6, 2, "word", "cheer", "/tʃɪə(r)/", "v. 欢呼；加油"),
      mk(6, 2, "phrase", "book fair", "/bʊk feə(r)/", "书市"),
      mk(6, 2, "word", "writer", "/ˈraɪtə(r)/", "n. 作家；作者"),
      mk(6, 2, "word", "read", "/riːd/", "v. (过去式 read) 阅读"),
      mk(6, 2, "word", "make", "/meɪk/", "v. (过去式 made) 做；使出现"),
      mk(6, 2, "word", "sing", "/sɪŋ/", "v. (过去式 sang) 唱（歌）；演唱"),
      mk(6, 2, "word", "wear", "/weə(r)/", "v. (过去式 wore) 穿；戴"),
      mk(6, 2, "word", "yesterday", "/ˈjestədeɪ/", "adv. 昨天"),
      mk(6, 2, "word", "notice", "/ˈnəʊtɪs/", "n. 通知"),
      mk(6, 2, "word", "wake", "/weɪk/", "v. (过去式 woke) 醒；醒来"),
      mk(6, 2, "word", "later", "/ˈleɪtə(r)/", "adv. 随后；后来"),
      mk(6, 2, "word", "judge", "/dʒʌdʒ/", "n. 裁判"),
      mk(6, 2, "word", "begin", "/bɪˈɡɪn/", "v. (过去式 began) 开始"),
      mk(6, 2, "word", "win", "/wɪn/", "v. (过去式 won) 获胜"),
      mk(6, 2, "word", "winner", "/ˈwɪnə(r)/", "n. 获胜的人（或队）；成功者"),
      mk(6, 2, "word", "ever", "/ˈevə(r)/", "adv. (进行比较时用于加强语气) 往任何时候"),
      mk(6, 2, "word", "exciting", "/ɪkˈsaɪtɪŋ/", "adj. 令人激动的"),
      mk(6, 2, "sentence", "How was your Mid-Autumn Festival holiday, Binbin?", "", "你中秋假期过得怎么样，斌斌？"),
      mk(6, 2, "sentence", "Did you have a nice school trip?", "", "你们学校旅行愉快吗？"),
      mk(6, 2, "sentence", "I want to write about the book fair.", "", "我想写关于书市的内容。"),
      mk(6, 2, "sentence", "Did you buy anything?", "", "你买了什么东西吗？"),
      mk(6, 2, "sentence", "I bought some books and a poster.", "", "我买了几本书和一张海报。"),
      mk(6, 2, "sentence", "The writer wrote a lot of famous stories.", "", "这位作家写了很多著名的故事。"),
      mk(6, 2, "sentence", "I can't wait to read them.", "", "我迫不及待要读它们。"),
      mk(6, 2, "sentence", "The gala started at eight o'clock in the evening.", "", "晚会晚上八点开始。"),
    ],
  },
  {
    grade: 6,
    unit: 3,
    title: "Healthy life 健康生活",
    entries: [
      mk(6, 3, "word", "cold", "/kəʊld/", "n. 感冒"),
      mk(6, 3, "word", "ill", "/ɪl/", "adj. 不舒服；生病的"),
      mk(6, 3, "word", "head", "/hed/", "n. 头；头部"),
      mk(6, 3, "phrase", "runny nose", "/ˈrʌni nəʊz/", "流鼻涕"),
      mk(6, 3, "word", "soon", "/suːn/", "adv. 很快；马上"),
      mk(6, 3, "word", "fever", "/ˈfiːvə(r)/", "n. 发烧；发热"),
      mk(6, 3, "word", "cough", "/kɒf/", "n. 咳嗽"),
      mk(6, 3, "word", "discuss", "/dɪˈskʌs/", "v. 讨论；商量"),
      mk(6, 3, "word", "diet", "/ˈdaɪət/", "n. 日常饮食"),
      mk(6, 3, "phrase", "stay up", "/steɪ ʌp/", "熬夜"),
      mk(6, 3, "word", "cry", "/kraɪ/", "v. 哭；哭泣"),
      mk(6, 3, "word", "another", "/əˈnʌðə(r)/", "adj. 另一个；不同的（人或事物）"),
      mk(6, 3, "word", "call", "/kɔːl/", "v. (给……) 打电话"),
      mk(6, 3, "word", "email", "/ˈiːmeɪl/", "n. 电子邮件"),
      mk(6, 3, "word", "unhappy", "/ʌnˈhæpi/", "adj. 不快乐的；难过的"),
      mk(6, 3, "word", "glass", "/ɡlɑːs/", "n. 一杯（的量）；玻璃"),
      mk(6, 3, "word", "may", "/meɪ/", "modal v. 也许；可能"),
      mk(6, 3, "word", "add", "/æd/", "v. 补充说；增加"),
      mk(6, 3, "word", "video", "/ˈvɪdiəʊ/", "n. 视频；录像"),
      mk(6, 3, "word", "better", "/ˈbetə(r)/", "adj. 舒畅些的；（病势）好转的"),
      mk(6, 3, "sentence", "How do you feel?", "", "你感觉怎么样？"),
      mk(6, 3, "sentence", "I feel ill. My head hurts and I have a runny nose.", "", "我感觉不舒服。我头疼还流鼻涕。"),
      mk(6, 3, "sentence", "I'm sorry to hear that. Maybe you should see a doctor.", "", "对此我感到难过。也许你应该去看医生。"),
      mk(6, 3, "sentence", "How can we live a healthy life?", "", "我们怎样才能过健康的生活？"),
      mk(6, 3, "sentence", "We need to eat healthy food. We should exercise too.", "", "我们需要吃健康的食物。我们还需要运动。"),
      mk(6, 3, "sentence", "Have a healthy diet.", "", "（保持）健康的饮食。"),
      mk(6, 3, "sentence", "Don't stay up late.", "", "不要熬夜。"),
      mk(6, 3, "sentence", "Think about happy things.", "", "想开心的事情。"),
      mk(6, 3, "sentence", "Join clubs and teams.", "", "加入俱乐部和团队。"),
      mk(6, 3, "sentence", "Drink more water.", "", "多喝水。"),
      mk(6, 3, "sentence", "I hope you feel better soon.", "", "我希望你很快好起来。"),
    ],
  },
  {
    grade: 6,
    unit: 4,
    title: "Managing money well 管好零花钱",
    entries: [
      mk(6, 4, "word", "money", "/ˈmʌni/", "n. 钱"),
      mk(6, 4, "phrase", "pocket money", "/ˈpɒkɪt ˈmʌni/", "零花钱"),
      mk(6, 4, "word", "schoolbag", "/ˈskuːlbæɡ/", "n. 书包"),
      mk(6, 4, "word", "goods", "/ɡʊdz/", "n. 商品"),
      mk(6, 4, "word", "drink", "/drɪŋk/", "n. 饮料"),
      mk(6, 4, "word", "service", "/ˈsɜːvɪs/", "n. 服务"),
      mk(6, 4, "word", "haircut", "/ˈheəkʌt/", "n. 理发；发型"),
      mk(6, 4, "word", "microscope", "/ˈmaɪkrəskəʊp/", "n. 显微镜"),
      mk(6, 4, "word", "lucky", "/ˈlʌki/", "adj. 幸运的"),
      mk(6, 4, "word", "half", "/hɑːf/", "n. 一半"),
      mk(6, 4, "phrase", "save up", "/seɪv ʌp/", "攒钱"),
      mk(6, 4, "word", "sale", "/seɪl/", "n. 特价销售；出售"),
      mk(6, 4, "word", "ticket", "/ˈtɪkɪt/", "n. 票"),
      mk(6, 4, "word", "manage", "/ˈmænɪdʒ/", "v. 管理"),
      mk(6, 4, "word", "sell", "/sel/", "v. 出售；售卖"),
      mk(6, 4, "word", "jar", "/dʒɑː(r)/", "n. 罐子"),
      mk(6, 4, "phrase", "for example", "/fə(r) ɪɡˈzɑːmpl/", "例如"),
      mk(6, 4, "sentence", "How are you going to spend it?", "", "你打算怎么花（这些钱）？"),
      mk(6, 4, "sentence", "I'm going to buy a schoolbag.", "", "我打算买一个书包。"),
      mk(6, 4, "sentence", "I also want to buy some animal books.", "", "我还想买一些动物类书籍。"),
      mk(6, 4, "sentence", "What else are you going to buy?", "", "你还打算买什么？"),
      mk(6, 4, "sentence", "I'm going to buy a pair of sunglasses for Grandpa.", "", "我打算给爷爷买一副太阳镜。"),
      mk(6, 4, "sentence", "I also want to buy a microscope.", "", "我还想买一个显微镜。"),
      mk(6, 4, "sentence", "You can save up for it.", "", "你可以为它攒钱。"),
    ],
  },
  {
    grade: 6,
    unit: 5,
    title: "Exploring space 探索太空",
    entries: [
      mk(6, 5, "word", "planet", "/ˈplænɪt/", "n. 行星"),
      mk(6, 5, "word", "earth", "/ɜːθ/", "n. (also Earth) 地球"),
      mk(6, 5, "word", "sky", "/skaɪ/", "n. 天；天空"),
      mk(6, 5, "word", "daytime", "/ˈdeɪtaɪm/", "n. 白天"),
      mk(6, 5, "word", "cloud", "/klaʊd/", "n. 云"),
      mk(6, 5, "word", "moon", "/muːn/", "n. (also the Moon) 月球；月亮；卫星"),
      mk(6, 5, "word", "star", "/stɑː(r)/", "n. 恒星；星"),
      mk(6, 5, "word", "space", "/speɪs/", "n. 太空；空间"),
      mk(6, 5, "phrase", "outer space", "/ˈaʊtə(r) speɪs/", "外太空"),
      mk(6, 5, "phrase", "space station", "/speɪs ˈsteɪʃn/", "空间站"),
      mk(6, 5, "word", "ocean", "/ˈəʊʃn/", "n. 大海；海洋"),
      mk(6, 5, "word", "marble", "/ˈmɑːbl/", "n. (玻璃) 弹子"),
      mk(6, 5, "word", "satellite", "/ˈsætəlaɪt/", "n. 人造卫星"),
      mk(6, 5, "word", "soil", "/sɔɪl/", "n. 土壤"),
      mk(6, 5, "word", "alien", "/ˈeɪliən/", "n. 外星生物"),
      mk(6, 5, "word", "sunrise", "/ˈsʌnraɪz/", "n. 日出"),
      mk(6, 5, "word", "rover", "/ˈrəʊvə(r)/", "n. 探测器"),
      mk(6, 5, "word", "into", "/ˈɪntə/", "prep. 朝；进入"),
      mk(6, 5, "word", "telescope", "/ˈtelɪskəʊp/", "n. 望远镜"),
      mk(6, 5, "word", "astronaut", "/ˈæstrənɔːt/", "n. 航天员；宇航员"),
      mk(6, 5, "word", "spaceship", "/ˈspeɪsʃɪp/", "n. 宇宙飞船"),
      mk(6, 5, "word", "month", "/mʌnθ/", "n. 月；月份"),
      mk(6, 5, "word", "taikonaut", "/ˈtaɪkənɔːt/", "n. 中国航天员"),
      mk(6, 5, "word", "cloth", "/klɒθ/", "n. (一块) 布；织物"),
      mk(6, 5, "word", "toothpaste", "/ˈtuːθpeɪst/", "n. 牙膏"),
      mk(6, 5, "word", "question", "/ˈkwestʃən/", "n. 问题"),
      mk(6, 5, "word", "sunset", "/ˈsʌnset/", "n. 日落"),
      mk(6, 5, "word", "time", "/taɪm/", "n. 次；回"),
      mk(6, 5, "word", "Mars", "/mɑːz/", "n. 火星"),
      mk(6, 5, "sentence", "What can you see in the sky?", "", "你能在天空中看到什么？"),
      mk(6, 5, "sentence", "We can see the Sun and clouds.", "", "我们能看到太阳和云。"),
      mk(6, 5, "sentence", "At night, we can see the Moon and the stars.", "", "在晚上，我们能看到月亮和星星。"),
      mk(6, 5, "sentence", "Is there any water on Mars?", "", "火星上有水吗？"),
      mk(6, 5, "sentence", "Yes, there is. There is soil too.", "", "是，有的。那里还有土壤。"),
      mk(6, 5, "sentence", "Are there any aliens?", "", "那儿有外星生物吗？"),
      mk(6, 5, "sentence", "I don't think so. They say there aren't any living things.", "", "我不这样认为。据说那里没有生物。"),
      mk(6, 5, "sentence", "China put a rover on Mars.", "", "中国在火星上放置了探测器。"),
      mk(6, 5, "sentence", "The taikonauts get up early in the morning.", "", "中国航天员很早就起床。"),
      mk(6, 5, "sentence", "I want to be an astronaut one day.", "", "我想有一天成为宇航员。"),
    ],
  },
  {
    grade: 6,
    unit: 6,
    title: "Energy, nature and us 能源、自然与我们",
    entries: [
      mk(6, 6, "word", "power", "/ˈpaʊə(r)/", "n. 能；能量"),
      mk(6, 6, "word", "electricity", "/ɪˌlekˈtrɪsəti/", "n. 电"),
      mk(6, 6, "word", "solar", "/ˈsəʊlə(r)/", "adj. 太阳的"),
      mk(6, 6, "word", "type", "/taɪp/", "n. 类型；种类"),
      mk(6, 6, "word", "energy", "/ˈenədʒi/", "n. 能源"),
      mk(6, 6, "word", "light", "/laɪt/", "v. 照亮"),
      mk(6, 6, "word", "heat", "/hiːt/", "v. 加热；（使）变暖 n. 热量"),
      mk(6, 6, "word", "cool", "/kuːl/", "v. (使) 变凉，冷却"),
      mk(6, 6, "word", "run", "/rʌn/", "v. (使) 运转"),
      mk(6, 6, "word", "resource", "/rɪˈsɔːs/", "n. 资源"),
      mk(6, 6, "phrase", "run out", "/rʌn aʊt/", "用完"),
      mk(6, 6, "word", "change", "/tʃeɪndʒ/", "v. (使) 不同；改变"),
      mk(6, 6, "word", "quick", "/kwɪk/", "adj. 迅速的；快的"),
      mk(6, 6, "word", "shower", "/ˈʃaʊə(r)/", "n. 淋浴"),
      mk(6, 6, "word", "unplug", "/ʌnˈplʌɡ/", "v. 拔掉……的电源插头"),
      mk(6, 6, "word", "difference", "/ˈdɪfrəns/", "n. 差别；不同（之处）"),
      mk(6, 6, "word", "reduce", "/rɪˈdjuːs/", "v. 减少"),
      mk(6, 6, "phrase", "air conditioner", "/eə(r) kənˌdɪʃənə(r)/", "空调机"),
      mk(6, 6, "word", "drive", "/draɪv/", "v. 驾驶；开车"),
      mk(6, 6, "word", "reuse", "/ˌriːˈjuːz/", "v. 再次使用；重复使用"),
      mk(6, 6, "word", "own", "/əʊn/", "adj. 自己的"),
      mk(6, 6, "word", "market", "/ˈmɑːkɪt/", "n. 集市；市场"),
      mk(6, 6, "word", "bottle", "/ˈbɒtl/", "n. 瓶子"),
      mk(6, 6, "word", "top", "/tɒp/", "adj. (位置、级别或程度) 最高的"),
      mk(6, 6, "word", "useful", "/ˈjuːsfl/", "adj. 有用的；有益的"),
      mk(6, 6, "word", "dirty", "/ˈdɜːti/", "adj. 脏的"),
      mk(6, 6, "word", "side", "/saɪd/", "n. 一面；一边"),
      mk(6, 6, "sentence", "What do you know about it?", "", "关于它你知道些什么？"),
      mk(6, 6, "sentence", "Running water can make electricity.", "", "流水可以发电。"),
      mk(6, 6, "sentence", "What else do you want to know about water?", "", "关于水你还想了解些什么？"),
      mk(6, 6, "sentence", "Where does water come from?", "", "水从哪儿来？"),
      mk(6, 6, "sentence", "Wind power, solar power and water power are types of green energy.", "", "风能、太阳能和水能是不同类型的绿色能源。"),
      mk(6, 6, "sentence", "But many resources are running out.", "", "但是很多资源快要耗尽了。"),
      mk(6, 6, "sentence", "What should we do?", "", "我们应该怎么办？"),
      mk(6, 6, "sentence", "How can we save energy?", "", "我们怎样才能节约能源？"),
      mk(6, 6, "sentence", "We can take quick showers.", "", "我们可以快速淋浴。"),
      mk(6, 6, "sentence", "We can also use LED lighting.", "", "我们还可以使用 LED 照明。"),
      mk(6, 6, "sentence", "We should use air conditioners less.", "", "我们应该少用空调。"),
    ],
  },
`;

const OLD_START_MARK = "// ==================== 六年级上（PEP 六上） ====================";
const OLD_END_MARK = "// ==================== 六年级下（PEP 六下） ====================";

const FILE = "src/data/grades4to9.ts";
const target = readFileSync(FILE, "utf8");

const startIdx = target.indexOf(OLD_START_MARK);
if (startIdx < 0) {
  console.error("OLD_START_MARK not found");
  process.exit(2);
}
const endIdx = target.indexOf(OLD_END_MARK, startIdx);
if (endIdx < 0) {
  console.error("OLD_END_MARK not found");
  process.exit(2);
}

const before = target.slice(0, startIdx);
const after = target.slice(endIdx + OLD_END_MARK.length);
const next = before + NEW_BLOCK + "\n  " + after;

writeFileSync(FILE, next);
console.log(`[OK] G6U1-6 replaced. file lines: ${next.split("\n").length}`);
console.log(`[OK] OLD_START_MARK at ${startIdx}, OLD_END_MARK at ${endIdx}`);
console.log(`[OK] NEW_BLOCK length: ${NEW_BLOCK.length}`);
