// scripts/patch_g8x.mjs
// PEP 2024 秋新版八年级下册（初二下）整段重做
// 用户 2026-09-05 拍 15 张截图：
//   - 3 张 CONTENTS（II-V，8 Unit 标题 + Section A/B + Project + 附录页码）
//   - 12 张 Vocabulary in Each Unit P113-P124（U1-U8 全部词条 + 专有名词）
// 旧结构（Go for it 2012 旧版）：G8X U1-2（精简版，每单元 10 词）
// 新结构（PEP 2024 秋新版 2026 春启用）：8 个正式 Unit
//   U27 Time to Relax              放松时间
//   U28 Stay Healthy               保持健康
//   U29 Growing Up                 成长
//   U30 The Wonders of Nature      大自然奇观
//   U31 Nature's Temper            大自然的脾气
//   U32 Crossing Cultures          跨越文化
//   U33 A Good Read                一本好书
//   U34 Making a Difference        有所作为
//
// 单元编号延续 G8S：七上 U1-10 + 七下 U11-18 + 八上 U19-U26 + 八下 U27-U34。
//
// 设计原则（patch_unit_template）：
//   OLD_END_MARK 仅含下段注释起点（不含闭合括号）；NEW_BLOCK 末尾自带 \n  },\n

import fs from 'node:fs';

const FILE = 'src/data/grades4to9.ts';
const FILE_CONTENT = fs.readFileSync(FILE, 'utf8');
const OLD_START_MARK = `  // ==================== 八年级下（Go for it 八下 U1-2） ====================
`;
const OLD_END_MARK = `  // ==================== 九年级（Go for it 全一册 U1-12） ====================
`;

const NEW_BLOCK = `  // ==================== 八年级下（PEP 2024 秋新版 · 8 Unit） ====================
  // 数据来源：用户 2026-09-05 拍 15 张（CONTENTS II-V + Vocabulary in Each Unit P113-P124）
  // 旧版（Go for it 2012）精简版 2 个 unit 整体替换为新版 8 个 unit
  {
    grade: 8,
    unit: 27,
    title: "Time to Relax 放松时间",
    entries: [
      mk(8, 27, "word", "calligraphy", "/kəˈlɪɡrəfi/", "n. 书法"),
      mk(8, 27, "word", "ski", "/skiː/", "v. 滑雪"),
      mk(8, 27, "word", "program", "/ˈprəʊɡræm/", "v. 编写程序；n. 程序；（=programme）节目；项目"),
      mk(8, 27, "word", "express", "/ɪkˈspres/", "v. 表达；表示"),
      mk(8, 27, "phrase", "ice skating", "/ˈaɪs ˌskeɪtɪŋ/", "滑冰；溜冰"),
      mk(8, 27, "word", "instructor", "/ɪnˈstrʌktər/", "n. 教练；指导者"),
      mk(8, 27, "phrase", "give up", "/ɡɪv ʌp/", "放弃"),
      mk(8, 27, "word", "scared", "/skerd/", "adj. 害怕的；对……感到惊慌的"),
      mk(8, 27, "phrase", "scared of", "/skerd əv/", "害怕；恐惧"),
      mk(8, 27, "word", "fear", "/fɪr/", "n. & v. 害怕；担忧"),
      mk(8, 27, "phrase", "get over", "/ɡet ˈoʊvər/", "克服（困难）；解决（问题）"),
      mk(8, 27, "phrase", "up to", "/ʌp tuː/", "正在做；由某人决定"),
      mk(8, 27, "word", "poem", "/ˈpoʊəm/", "n. 诗"),
      mk(8, 27, "word", "single", "/ˈsɪŋɡl/", "adj. 单个的；单身的"),
      mk(8, 27, "word", "stroke", "/stroʊk/", "n. 笔画；击球"),
      mk(8, 27, "word", "ink", "/ɪŋk/", "n. 墨水"),
      mk(8, 27, "word", "return", "/rɪˈtɜːrn/", "n. & v. 回来；归还"),
      mk(8, 27, "phrase", "in return", "/ɪn rɪˈtɜːrn/", "作为回报"),
      mk(8, 27, "word", "deal", "/diːl/", "n. 交易；协议；v. (dealt /delt/, dealt) 对付"),
      mk(8, 27, "word", "manage", "/ˈmænɪdʒ/", "v. 完成（困难的事）；管理"),
      mk(8, 27, "phrase", "ice-skate", "/ˈaɪs skeɪt/", "v. 滑冰；溜冰"),
      mk(8, 27, "phrase", "get into", "/ɡet ˈɪntuː/", "开始做某事；进入"),
      mk(8, 27, "phrase", "give it a go", "/ɡɪv ɪt ə ɡoʊ/", "试一试某事"),
      mk(8, 27, "word", "kung fu", "/ˌkʌŋ ˈfuː/", "n. 功夫"),
      mk(8, 27, "word", "push", "/pʊʃ/", "v. 鞭策；推；n. 推"),
      mk(8, 27, "phrase", "once in a while", "/wʌns ɪn ə waɪl/", "偶尔；间或"),
      mk(8, 27, "word", "chat", "/tʃæt/", "v. & n. 闲聊"),
      mk(8, 27, "word", "outing", "/ˈaʊtɪŋ/", "n. 出外游玩；远足"),
      mk(8, 27, "phrase", "go on an outing", "/ɡoʊ ɑːn ən ˈaʊtɪŋ/", "出外游玩"),
      mk(8, 27, "word", "reduce", "/rɪˈduːs/", "v. 减少"),
      mk(8, 27, "word", "stress", "/stres/", "n. 精神压力；紧张"),
      mk(8, 27, "word", "yoga", "/ˈjoʊɡə/", "n. 瑜伽"),
      mk(8, 27, "word", "object", "/ˈɑːbdʒɪkt/", "n. 物品；宾语"),
      mk(8, 27, "word", "Italian", "/ɪˈtæliən/", "adj. 意大利的；意大利人的；n. 意大利人；意大利语"),
      mk(8, 27, "word", "programmer", "/ˈproʊɡræmər/", "n. 程序设计员"),
      mk(8, 27, "word", "allow", "/əˈlaʊ/", "v. 使……成为可能；允许"),
      mk(8, 27, "word", "achievement", "/əˈtʃiːvmənt/", "n. 成就"),
      mk(8, 27, "word", "coin", "/kɔɪn/", "n. 硬币"),
      mk(8, 27, "word", "stamp", "/stæmp/", "n. 邮票"),
      mk(8, 27, "word", "teenage", "/ˈtiːneɪdʒ/", "adj. 青少年的"),
      mk(8, 27, "word", "postcard", "/ˈpoʊstkɑːrd/", "n. 明信片"),
      mk(8, 27, "word", "rather", "/ˈræðər/", "adv. 相宜；更准确地说"),
      mk(8, 27, "word", "old-fashioned", "/ˌoʊld ˈfæʃənd/", "adj. 过时的；守旧的"),
      mk(8, 27, "word", "foreign", "/ˈfɔːrən/", "adj. 外国的；国外的"),
      mk(8, 27, "phrase", "dream of", "/driːm əv/", "梦想；希望"),
      mk(8, 27, "word", "suggestion", "/səˈdʒestʃən/", "n. 建议；提议"),
      mk(8, 27, "word", "failure", "/ˈfeɪljər/", "n. 失败"),
      mk(8, 27, "word", "inspiration", "/ˌɪnspəˈreɪʃn/", "n. 鼓舞人心或启发灵感的人（或事物）；灵感"),
      mk(8, 27, "word", "strict", "/strɪkt/", "adj. 严厉的；严格的"),
      mk(8, 27, "word", "surprising", "/sərˈpraɪzɪŋ/", "adj. 出人意料地；惊人地"),
      mk(8, 27, "phrase", "so far", "/soʊ fɑːr/", "到目前为止"),
      mk(8, 27, "word", "stage", "/steɪdʒ/", "n. 舞台；阶段"),
      mk(8, 27, "word", "importantly", "/ɪmˈpɔːrtntli/", "adv. 重要地"),
      mk(8, 27, "word", "Luca", "/ˈluːkə/", "n. 卢卡"),
      mk(8, 27, "word", "Bruno", "/ˈbruːnoʊ/", "n. 布鲁诺"),
      mk(8, 27, "word", "India", "/ˈɪndiə/", "n. 印度"),
      mk(8, 27, "word", "Maya", "/ˈmaɪə/", "n. 玛娅"),
      mk(8, 27, "word", "Badal", "/bəˈdɑːl/", "n. 巴达尔"),
      mk(8, 27, "word", "Mogao Caves", "/ˈməʊɡaʊ keɪvz/", "n. 莫高窟"),
    ],
  },
  {
    grade: 8,
    unit: 28,
    title: "Stay Healthy 保持健康",
    entries: [
      mk(8, 28, "word", "ourselves", "/ɑːrˈselvz/", "pron. 我们自己"),
      mk(8, 28, "word", "sore", "/sɔːr/", "adj. 疼痛的；酸痛的"),
      mk(8, 28, "word", "throat", "/θroʊt/", "n. 喉咙"),
      mk(8, 28, "word", "stomachache", "/ˈstʌməkeɪk/", "n. 胃痛；肚子疼"),
      mk(8, 28, "word", "headache", "/ˈhedeɪk/", "n. 头痛"),
      mk(8, 28, "word", "toothache", "/ˈtuːθeɪk/", "n. 牙痛"),
      mk(8, 28, "word", "backache", "/ˈbækeɪk/", "n. 背痛；腰痛"),
      mk(8, 28, "word", "suffer", "/ˈsʌfər/", "v. 变苦；遭受"),
      mk(8, 28, "phrase", "suffer from", "/ˈsʌfər frɒm/", "受苦；受折磨"),
      mk(8, 28, "word", "press", "/pres/", "v. 压；按"),
      mk(8, 28, "word", "nosebleed", "/ˈnoʊzbliːd/", "n. 鼻出血"),
      mk(8, 28, "word", "dentist", "/ˈdentɪst/", "n. 牙科医生"),
      mk(8, 28, "word", "fever", "/ˈfiːvər/", "n. 发烧"),
      mk(8, 28, "word", "stomach", "/ˈstʌmək/", "n. 胃；腹部"),
      mk(8, 28, "word", "avoid", "/əˈvɔɪd/", "v. 避免；防止"),
      mk(8, 28, "word", "gas", "/ɡæs/", "n. 气体；燃气"),
      mk(8, 28, "word", "ache", "/eɪk/", "n. & v. 疼痛"),
      mk(8, 28, "word", "X-ray", "/ˈeksreɪ/", "n. X 射线检查；X 射线"),
      mk(8, 28, "word", "careless", "/ˈkerləs/", "adj. 不小心的；粗心的"),
      mk(8, 28, "word", "runny", "/ˈrʌni/", "adj. 流鼻涕的；流眼泪的"),
      mk(8, 28, "word", "cough", "/kɔːf/", "n. & v. 咳嗽"),
      mk(8, 28, "word", "bruised", "/bruːzd/", "adj. 受了瘀伤的"),
      mk(8, 28, "phrase", "take a seat", "/teɪk ə siːt/", "坐下"),
      mk(8, 28, "phrase", "take sb's temperature", "/teɪk ˌsʌmbədiz ˈtemprətʃər/", "给某人量体温"),
      mk(8, 28, "word", "test", "/test/", "n. & v. 检查；测验"),
      mk(8, 28, "word", "flu", "/fluː/", "n. 流行性感冒"),
      mk(8, 28, "word", "medicine", "/ˈmedsn/", "n. 药；医学"),
      mk(8, 28, "word", "mask", "/mæsk/", "n. 口罩"),
      mk(8, 28, "phrase", "stop ... from doing", "/stɑːp ... frəm ˈduːɪŋ/", "防止……；阻止……"),
      mk(8, 28, "word", "virus", "/ˈvaɪrəs/", "n. 病毒"),
      mk(8, 28, "word", "description", "/dɪˈskrɪpʃn/", "n. 描写；形容"),
      mk(8, 28, "word", "patient", "/ˈpeɪʃnt/", "n. 病人；adj. 有耐心的"),
      mk(8, 28, "word", "injury", "/ˈɪndʒəri/", "n. 伤害；损伤"),
      mk(8, 28, "word", "illness", "/ˈɪlnəs/", "n. 疾病"),
      mk(8, 28, "word", "knife", "/naɪf/", "n. (pl. knives /naɪvz/) 刀"),
      mk(8, 28, "word", "safety", "/ˈseɪfti/", "n. 安全；安全处所"),
      mk(8, 28, "word", "clear", "/klɪr/", "adj. 清晰的；清楚的；v. 清扫"),
      mk(8, 28, "word", "pain", "/peɪn/", "n. 疼痛；痛苦"),
      mk(8, 28, "phrase", "what's more", "/wʌts mɔːr/", "更为重要的是"),
      mk(8, 28, "word", "brightness", "/ˈbraɪtnəs/", "n. 亮度"),
      mk(8, 28, "word", "environment", "/ɪnˈvaɪrənmənt/", "n. 环境"),
      mk(8, 28, "word", "cross", "/krɔːs/", "v. 穿越；横过；交叉"),
      mk(8, 28, "phrase", "catch fire", "/kætʃ ˈfaɪər/", "着火"),
      mk(8, 28, "word", "themselves", "/ðəmˈselvz/", "pron. 他（或她、它）们自己"),
      mk(8, 28, "word", "fry", "/fraɪ/", "v. 油炸；油煎；油炒"),
      mk(8, 28, "phrase", "turn on", "/tɜːrn ɑːn/", "接通（电流、煤气、水等）；打开"),
      mk(8, 28, "word", "stove", "/stoʊv/", "n. 厨房灶具；炉子"),
      mk(8, 28, "word", "happily", "/ˈhæpɪli/", "adv. 快乐地；高兴地"),
      mk(8, 28, "phrase", "no way", "/noʊ weɪ/", "不可能；没门"),
      mk(8, 28, "word", "burn", "/bɜːrn/", "v. (burnt /bɜːrnt/, burnt) 燃烧；着火；n. 烧伤"),
      mk(8, 28, "phrase", "on fire", "/ɑːn ˈfaɪər/", "着火；起火"),
      mk(8, 28, "word", "flame", "/fleɪm/", "n. 火焰"),
      mk(8, 28, "word", "panic", "/ˈpænɪk/", "n. 惊恐；恐慌"),
      mk(8, 28, "word", "onto", "/ˈɑːntuː/", "prep. 到；朝"),
      mk(8, 28, "word", "throw", "/θroʊ/", "v. (threw /θruː/, thrown /θroʊn/) 猛动（身体部位）；扔；抛"),
      mk(8, 28, "word", "roll", "/roʊl/", "v. (使) 翻滚；滚动"),
      mk(8, 28, "word", "quick", "/kwɪk/", "adj. 快的；迅速的；adv. 迅速地；快速地"),
      mk(8, 28, "phrase", "be about to", "/bi əˈbaʊt tuː/", "即将；正要（（做某事）)"),
      mk(8, 28, "phrase", "stop short", "/stɑːp ʃɔːrt/", "突然停住"),
      mk(8, 28, "word", "aid", "/eɪd/", "n. & v. 帮助；援助"),
      mk(8, 28, "phrase", "first aid", "/fɜːrst eɪd/", "急救"),
      mk(8, 28, "word", "extinguisher", "/ɪkˈstɪŋɡwɪʃər/", "n. 灭火器"),
      mk(8, 28, "phrase", "eat out", "/iːt aʊt/", "上馆子吃饭；在外用餐"),
      mk(8, 28, "word", "tonight", "/təˈnaɪt/", "adv. 在今晚；n. 今夜；今晚"),
      mk(8, 28, "word", "sadly", "/ˈsædli/", "adv. 伤心地；令人遗憾地"),
      mk(8, 28, "word", "smoke", "/smoʊk/", "n. & v. 吸烟；冒烟"),
      mk(8, 28, "word", "luckily", "/ˈlʌkɪli/", "adv. 幸运地"),
      mk(8, 28, "word", "badly", "/ˈbædli/", "adv. (worse /wɜːrs/, worst /wɜːrst/) 严重地"),
      mk(8, 28, "word", "harm", "/hɑːrm/", "n. & v. 伤害；损害"),
      mk(8, 28, "word", "pill", "/pɪl/", "n. 药丸；药片"),
      mk(8, 28, "word", "harmful", "/ˈhɑːrmfl/", "adj. 有害的"),
      mk(8, 28, "word", "hit", "/hɪt/", "v. (hit, hit) 碰撞；击；打；n. 打；击；击中"),
      mk(8, 28, "word", "shock", "/ʃɑːk/", "n. 震惊；令人震惊的事；v. 使震惊；使惊愕"),
      mk(8, 28, "word", "bleed", "/bliːd/", "v. (bled /bled/, bled) 流血；出血"),
      mk(8, 28, "word", "check", "/tʃek/", "v. 检查；查明；n. 检查；调查"),
      mk(8, 28, "word", "tight", "/taɪt/", "adj. 紧的；紧的；牢固的"),
      mk(8, 28, "word", "peanut", "/ˈpiːnʌt/", "n. 花生"),
      mk(8, 28, "word", "nervously", "/ˈnɜːrvəsli/", "adv. 紧张不安地"),
      mk(8, 28, "word", "allergic", "/əˈlɜːrdʒɪk/", "adj. 过敏的"),
      mk(8, 28, "phrase", "from now on", "/frəm naʊ ɑːn/", "从现在起"),
      mk(8, 28, "word", "Ben", "/ben/", "n. 本"),
      mk(8, 28, "word", "Nancy", "/ˈnænsi/", "n. 南希"),
      mk(8, 28, "word", "Jeff", "/dʒef/", "n. 杰夫"),
      mk(8, 28, "word", "James", "/ˈdʒeɪmz/", "n. 詹姆斯"),
      mk(8, 28, "word", "Allen", "/ˈælən/", "n. 艾伦"),
      mk(8, 28, "word", "Kelly", "/ˈkeli/", "n. 凯莉"),
      mk(8, 28, "word", "Cooper", "/ˈkuːpər/", "n. 库珀"),
    ],
  },
  {
    grade: 8,
    unit: 29,
    title: "Growing Up 成长",
    entries: [
      mk(8, 29, "phrase", "deal with", "/diːl wɪð/", "处理；对付"),
      mk(8, 29, "word", "emotion", "/ɪˈmoʊʃn/", "n. 情绪；情感"),
      mk(8, 29, "word", "upset", "/ʌpˈset/", "adj. 难过的；沮丧的"),
      mk(8, 29, "word", "lonely", "/ˈloʊnli/", "adj. 孤独的；寂寞的"),
      mk(8, 29, "word", "shocked", "/ʃɑːkt/", "adj. 震惊的"),
      mk(8, 29, "word", "advise", "/ədˈvaɪz/", "v. 建议；劝告"),
      mk(8, 29, "word", "hurtful", "/ˈhɜːrtfl/", "adj. 伤感情的"),
      mk(8, 29, "word", "control", "/kənˈtroʊl/", "v. & n. 控制"),
      mk(8, 29, "word", "anger", "/ˈæŋɡər/", "n. 怒气"),
      mk(8, 29, "phrase", "in future", "/ɪn ˈfjuːtʃər/", "今后；从今以后"),
      mk(8, 29, "word", "forgive", "/fərˈɡɪv/", "v. (forgave /fərˈɡeɪv/, forgiven /fərˈɡɪvn/) 原谅；宽恕"),
      mk(8, 29, "word", "fault", "/fɔːlt/", "n. 过错；责任"),
      mk(8, 29, "phrase", "so that", "/soʊ ðæt/", "为了；因此"),
      mk(8, 29, "phrase", "clear the air", "/klɪr ði er/", "尽释前嫌"),
      mk(8, 29, "word", "present", "/ˈpreznt/", "n. 礼物；v. 赠送；陈述"),
      mk(8, 29, "word", "standard", "/ˈstændərd/", "n. 标准；水平；adj. 标准的"),
      mk(8, 29, "word", "award", "/əˈwɔːrd/", "n. 奖；奖品"),
      mk(8, 29, "phrase", "look on the bright side", "/lʊk ɑːn ðə braɪt saɪd/", "从好的方面想；抱乐观态度"),
      mk(8, 29, "phrase", "get across", "/ɡet əˈkrɔːs/", "解释清楚；传达"),
      mk(8, 29, "word", "clearly", "/ˈklɪrli/", "adv. 清楚地"),
      mk(8, 29, "word", "pressure", "/ˈpreʃər/", "n. 压力"),
      mk(8, 29, "word", "purpose", "/ˈpɜːrpəs/", "n. 目的；意图"),
      mk(8, 29, "phrase", "on purpose", "/ɑːn ˈpɜːrpəs/", "故意；有意地"),
      mk(8, 29, "phrase", "cut ... in half", "/kʌt ... ɪn hæf/", "切成两半"),
      mk(8, 29, "phrase", "put oneself in sb's shoes", "/pʊt wʌnˈself ɪn sʌmbədiz ʃuːz/", "设身处地；处于某人的境地"),
      mk(8, 29, "word", "shut", "/ʃʌt/", "v. (shut, shut) 关闭；合上"),
      mk(8, 29, "phrase", "shut ... away", "/ʃʌt ... əˈweɪ/", "把……关（藏）起来；隔离"),
      mk(8, 29, "word", "lastly", "/ˈlæstli/", "adv. 最后"),
      mk(8, 29, "word", "plenty", "/ˈplenti/", "pron. 充足；丰富；大量"),
      mk(8, 29, "phrase", "plenty of", "/ˈplenti əv/", "充足的；大量的"),
      mk(8, 29, "phrase", "feel blue", "/fiːl bluː/", "感到忧郁"),
      mk(8, 29, "phrase", "on top of the world", "/ɑːn tɑːp əv ðə wɜːrld/", "欢天喜地"),
      mk(8, 29, "phrase", "all smiles", "/ɔːl smaɪlz/", "笑容满面"),
      mk(8, 29, "phrase", "in low spirits", "/ɪn loʊ ˈspɪrɪts/", "情绪低落；精神不振"),
      mk(8, 29, "word", "ring", "/rɪŋ/", "v. (rang /ræŋ/, rung /rʌŋ/) 响铃；鸣响；给……打电话"),
      mk(8, 29, "word", "enter", "/ˈentər/", "v. 进入"),
      mk(8, 29, "word", "dare", "/der/", "v. & modal v. 敢于"),
      mk(8, 29, "phrase", "let down", "/let daʊn/", "使失望"),
      mk(8, 29, "word", "everybody", "/ˈevribɑːdi/", "pron. 每人；所有人"),
      mk(8, 29, "phrase", "be hard on", "/bi hɑːrd ɑːn/", "对……苛刻或过分严厉"),
      mk(8, 29, "word", "player", "/ˈpleɪər/", "n. 运动员；选手"),
      mk(8, 29, "word", "referee", "/ˌrefəˈriː/", "n. 裁判"),
      mk(8, 29, "phrase", "take back", "/teɪk bæk/", "收回；收回"),
      mk(8, 29, "word", "decision", "/dɪˈsɪʒn/", "n. 决定"),
      mk(8, 29, "word", "score", "/skɔːr/", "n. 得分；分数；v. 得分"),
      mk(8, 29, "word", "proud", "/praʊd/", "adj. 骄傲的；自豪的"),
      mk(8, 29, "phrase", "proud of", "/praʊd əv/", "为……感到骄傲的"),
      mk(8, 29, "word", "coach", "/koʊtʃ/", "n. 教练"),
      mk(8, 29, "phrase", "as well", "/æz wel/", "也；又"),
      mk(8, 29, "word", "bit", "/bɪt/", "n. 有点儿；稍微"),
      mk(8, 29, "phrase", "a bit", "/ə bɪt/", "有点儿；稍微"),
      mk(8, 29, "word", "repeat", "/rɪˈpiːt/", "v. 重复"),
      mk(8, 29, "phrase", "pull together", "/pʊl təˈɡeðər/", "齐心协力；通力合作"),
      mk(8, 29, "word", "solution", "/səˈluːʃn/", "n. 解决办法；解决"),
      mk(8, 29, "word", "though", "/ðoʊ/", "conj. 虽然；尽管"),
      mk(8, 29, "phrase", "even though", "/ˈiːvn ðoʊ/", "即使；虽然"),
      mk(8, 29, "word", "apologize", "/əˈpɑːlədʒaɪz/", "(=apologise) v. 道歉"),
      mk(8, 29, "phrase", "go wrong", "/ɡoʊ rɔːŋ/", "出现问题；发生故障；搞错"),
      mk(8, 29, "word", "joyful", "/ˈdʒɔɪfl/", "adj. 高兴的；令人愉快的"),
      mk(8, 29, "word", "thankful", "/ˈθæŋkfl/", "adj. 感谢的；感激的"),
      mk(8, 29, "word", "negative", "/ˈneɡətɪv/", "adj. 否定的；消极的"),
      mk(8, 29, "word", "bully", "/ˈbʊli/", "v. 霸凌；恐吓；n. 恶霸"),
      mk(8, 29, "phrase", "shout at", "/ʃaʊt æt/", "冲……吼叫"),
      mk(8, 29, "word", "behave", "/bɪˈheɪv/", "v. 表现；举止得体"),
      mk(8, 29, "word", "differently", "/ˈdɪfrəntli/", "adv. 不同地"),
      mk(8, 29, "word", "physics", "/ˈfɪzɪks/", "n. 物理；物理学"),
      mk(8, 29, "word", "lie", "/laɪ/", "v. (lay /leɪ/, lain /leɪn/) 平躺；平放"),
      mk(8, 29, "word", "awake", "/əˈweɪk/", "adj. 醒着的"),
      mk(8, 29, "phrase", "wake up", "/weɪk ʌp/", "醒来"),
      mk(8, 29, "word", "relaxed", "/rɪˈlækst/", "adj. 放松的；镇定的"),
      mk(8, 29, "word", "normal", "/ˈnɔːrml/", "adj. 正常的；普通的"),
      mk(8, 29, "phrase", "from time to time", "/frəm taɪm tu taɪm/", "不时；偶尔"),
      mk(8, 29, "word", "mad", "/mæd/", "adj. 很生气；疯狂的"),
      mk(8, 29, "word", "mean", "/miːn/", "adj. 刻薄的；吝啬的"),
      mk(8, 29, "word", "deep", "/diːp/", "adj. 深的；有……深的"),
      mk(8, 29, "phrase", "take a deep breath", "/teɪk ə diːp breθ/", "深呼吸"),
      mk(8, 29, "phrase", "pass away", "/pæs əˈweɪ/", "去世（委婉说法）"),
      mk(8, 29, "word", "anybody", "/ˈenibɑːdi/", "pron. 任何人"),
      mk(8, 29, "word", "remain", "/rɪˈmeɪn/", "v. 继续存在；保持不变"),
      mk(8, 29, "phrase", "not only ... but also ...", "/nɑːt ˈoʊnli ... bʌt ˈɔːlsoʊ .../", "不但……而且……"),
      mk(8, 29, "word", "Thompson", "/ˈtɑːmpsən/", "n. 汤普森"),
    ],
  },
  {
    grade: 8,
    unit: 30,
    title: "The Wonders of Nature 大自然奇观",
    entries: [
      mk(8, 30, "word", "wonder", "/ˈwʌndər/", "n. 奇观；惊叹；v. 琢磨；想知道；感到诧异"),
      mk(8, 30, "word", "desert", "/ˈdezərt/", "n. 沙漠；荒原"),
      mk(8, 30, "word", "measurement", "/ˈmeʒərmənt/", "n. 数量；测量"),
      mk(8, 30, "phrase", "square kilometre", "/skwer ˈkɪləmiːtər/", "平方千米"),
      mk(8, 30, "word", "below", "/bɪˈloʊ/", "prep. & adv. 在（……）下面；低于"),
      mk(8, 30, "word", "level", "/ˈlevl/", "n. 高度；水平；程度"),
      mk(8, 30, "phrase", "sea level", "/siː ˈlevl/", "海平面"),
      mk(8, 30, "word", "surface", "/ˈsɜːrfɪs/", "n. 表面；表层"),
      mk(8, 30, "word", "depth", "/depθ/", "n. 深（度）；纵深"),
      mk(8, 30, "word", "dive", "/daɪv/", "v. & n. 潜水；跳水；俯冲"),
      mk(8, 30, "word", "submersible", "/səbˈmɜːrsəbl/", "n. 潜水艇"),
      mk(8, 30, "word", "unusual", "/ʌnˈjuːʒuəl/", "adj. 特别的；不寻常的"),
      mk(8, 30, "word", "bottom", "/ˈbɑːtəm/", "n. 底部；最下部"),
      mk(8, 30, "word", "waterfall", "/ˈwɔːtərfɔːl/", "n. 瀑布"),
      mk(8, 30, "word", "civilization", "/ˌsɪvələˈzeɪʃn/", "(=civilisation) n. 文明"),
      mk(8, 30, "phrase", "at all costs", "/æt ɔːl kɔːsts/", "不惜任何代价"),
      mk(8, 30, "word", "development", "/dɪˈveləpmənt/", "n. 发展；壮大"),
      mk(8, 30, "word", "cubic", "/ˈkjuːbɪk/", "adj. 立方的"),
      mk(8, 30, "phrase", "cubic metre", "/ˈkjuːbɪk ˈmiːtər/", "立方米"),
      mk(8, 30, "word", "mile", "/maɪl/", "n. 英里"),
      mk(8, 30, "word", "pool", "/puːl/", "n. 水池；水坑"),
      mk(8, 30, "word", "climber", "/ˈklaɪmər/", "n. 攀登者；登山者"),
      mk(8, 30, "word", "northern", "/ˈnɔːrðərn/", "adj. 北部的；向北的"),
      mk(8, 30, "word", "distance", "/ˈdɪstəns/", "n. 距离；遥远"),
      mk(8, 30, "word", "survive", "/sərˈvaɪv/", "v. 生存；存活；艰难度过"),
      mk(8, 30, "word", "condition", "/kənˈdɪʃn/", "n. 环境；条件；状态"),
      mk(8, 30, "word", "degree", "/dɪˈɡriː/", "n. 度数；程度"),
      mk(8, 30, "word", "cliff", "/klɪf/", "n. 悬崖；峭壁"),
      mk(8, 30, "word", "changeable", "/ˈtʃeɪndʒəbl/", "adj. 可能变化的；易变的；带变的"),
      mk(8, 30, "word", "death", "/deθ/", "n. 死亡；毁灭；毁灭"),
      mk(8, 30, "word", "determined", "/dɪˈtɜːrmɪnd/", "adj. 有决心的；坚决的"),
      mk(8, 30, "word", "above", "/əˈbʌv/", "prep. & adv. 在（……）上方；高于"),
      mk(8, 30, "word", "teammate", "/ˈtiːmmeɪt/", "n. 同队队员；队友"),
      mk(8, 30, "word", "shoulder", "/ˈʃoʊldər/", "n. 肩膀；肩部"),
      mk(8, 30, "phrase", "bit by bit", "/bɪt baɪ bɪt/", "一点一点地；逐渐地"),
      mk(8, 30, "word", "ladder", "/ˈlædər/", "n. 梯子；阶梯；途径"),
      mk(8, 30, "word", "measure", "/ˈmeʒər/", "v. 测量；量度为；n. 措施；度量单位"),
      mk(8, 30, "word", "successfully", "/səkˈsesfəli/", "adv. 成功地；顺利地"),
      mk(8, 30, "word", "risk", "/rɪsk/", "v. 使……冒风险（或面临危险）；n. 危险；风险"),
      mk(8, 30, "word", "curiosity", "/ˌkjʊriˈɑːsəti/", "n. 好奇心；求知欲"),
      mk(8, 30, "word", "ambition", "/æmˈbɪʃn/", "n. 追求的目标；野心；雄心"),
      mk(8, 30, "word", "explorer", "/ɪkˈsplɔːrər/", "n. 探险者；勘探者"),
      mk(8, 30, "word", "simply", "/ˈsɪmpli/", "adv. 仅仅；只；简单地"),
      mk(8, 30, "word", "risky", "/ˈrɪski/", "adj. 有危险（或风险）的"),
      mk(8, 30, "word", "southern", "/ˈsʌðərn/", "adj. 南部的；向南的"),
      mk(8, 30, "word", "located", "/ˈloʊkeɪtɪd/", "adj. 位于；坐落在"),
      mk(8, 30, "word", "freshwater", "/ˈfreʃwɔːtər/", "adj. 淡水的；淡水中生长的"),
      mk(8, 30, "word", "type", "/taɪp/", "n. 类型；种类"),
      mk(8, 30, "word", "attract", "/əˈtrækt/", "v. 吸引；招引"),
      mk(8, 30, "word", "curious", "/ˈkjʊriəs/", "adj. 好奇的；求知欲强的"),
      mk(8, 30, "word", "traveller", "/ˈtrævələr/", "(=traveler) n. 旅行者；游客"),
      mk(8, 30, "word", "natural", "/ˈnætʃərəl/", "adj. 自然的；天然的；天生的"),
      mk(8, 30, "word", "reef", "/riːf/", "n. 礁；礁脉"),
      mk(8, 30, "word", "underwater", "/ˌʌndərˈwɔːtər/", "adj. 水下的；用于水下的；adv. 在水下"),
      mk(8, 30, "word", "northeastern", "/ˌnɔːrˈθiːstərn/", "adj. 东北的；东北方向的"),
      mk(8, 30, "word", "coast", "/koʊst/", "n. 海岸；海滨"),
      mk(8, 30, "word", "coral", "/ˈkɔːrəl/", "n. 珊瑚；珊瑚虫"),
      mk(8, 30, "word", "include", "/ɪnˈkluːd/", "v. 包含；包括"),
      mk(8, 30, "word", "sand", "/sænd/", "n. 沙子"),
      mk(8, 30, "word", "alive", "/əˈlaɪv/", "adj. 活着；在世；有活力"),
      mk(8, 30, "word", "structure", "/ˈstrʌktʃər/", "n. 结构（体）；构造；体系"),
      mk(8, 30, "word", "turtle", "/ˈtɜːrtl/", "n. 海龟；龟"),
      mk(8, 30, "word", "lifetime", "/ˈlaɪftaɪm/", "n. 一生；终身"),
      mk(8, 30, "word", "Nile", "/naɪl/", "n. River 尼罗河"),
      mk(8, 30, "word", "Angel", "/ˈeɪndʒl/", "n. Falls 安赫尔瀑布"),
      mk(8, 30, "word", "Mount Qomolangma", "/ˌtʃəʊmoʊ lɑːŋmə/", "n. 珠穆朗玛峰"),
      mk(8, 30, "word", "Dead Sea", "/ded siː/", "n. 死海"),
      mk(8, 30, "word", "Sahara", "/səˈhærə/", "n. Desert 撒哈拉沙漠"),
      mk(8, 30, "word", "Mariana", "/mæriˈænə/", "n. Trench 马里亚纳海沟"),
      mk(8, 30, "word", "Titanic", "/taɪˈtænɪk/", "n. 泰坦尼克号"),
      mk(8, 30, "word", "Yangtze", "/ˈjæŋtsi/", "n. River 长江"),
      mk(8, 30, "word", "Egypt", "/ˈiːdʒɪpt/", "n. 埃及"),
      mk(8, 30, "word", "Taklimakan", "/ˌtæklɪməˈkɑːn/", "n. Desert 塔克拉玛干沙漠"),
      mk(8, 30, "word", "Mount Kilimanjaro", "/ˌkɪlmənˈdʒɑːroʊ/", "n. 乞力马扎罗山"),
      mk(8, 30, "word", "Inga", "/ˈɪŋɡə/", "n. Falls 英加瀑布"),
      mk(8, 30, "word", "East African Rift Valley", "/iːst ˈæfrɪkən rɪft ˈvæli/", "n. 东非大裂谷"),
      mk(8, 30, "word", "Victoria", "/vɪkˈtɔːriə/", "n. Falls 维多利亚瀑布"),
      mk(8, 30, "word", "George", "/ˈdʒɔːrdʒ/", "n. Mallory 乔治·马洛里"),
      mk(8, 30, "word", "Siberia", "/saɪˈbɪriə/", "n. 西伯利亚"),
      mk(8, 30, "word", "Lake Baikal", "/baɪˈkɑːl/", "n. 贝加尔湖"),
      mk(8, 30, "word", "Belgium", "/ˈbeldʒəm/", "n. 比利时"),
      mk(8, 30, "word", "Great Barrier", "/ˈbæriər/", "n. Reef 大堡礁"),
    ],
  },
  {
    grade: 8,
    unit: 31,
    title: "Nature's Temper 大自然的脾气",
    entries: [
      mk(8, 31, "word", "temper", "/ˈtempər/", "n. 脾气；怒气"),
      mk(8, 31, "word", "earthquake", "/ˈɜːrθkweɪk/", "n. 地震"),
      mk(8, 31, "word", "typhoon", "/taɪˈfuːn/", "n. 台风"),
      mk(8, 31, "word", "wildfire", "/ˈwaɪldfaɪər/", "n. 野火"),
      mk(8, 31, "word", "snowstorm", "/ˈsnoʊstɔːrm/", "n. 雪暴；暴风雪"),
      mk(8, 31, "word", "flood", "/flʌd/", "n. 水灾；洪水；v. 泛滥；淹没"),
      mk(8, 31, "word", "drought", "/draʊt/", "n. 旱灾；干旱"),
      mk(8, 31, "word", "warn", "/wɔːrn/", "v. 警告；提醒注意"),
      mk(8, 31, "phrase", "do chores", "/duː tʃɔːrz/", "做家务"),
      mk(8, 31, "word", "wave", "/weɪv/", "n. 波浪；波；挥手；v. 挥手；挥舞"),
      mk(8, 31, "word", "tsunami", "/tsuˈnɑːmi/", "n. 海啸"),
      mk(8, 31, "word", "interview", "/ˈɪntərvjuː/", "n. & v. 采访；面试"),
      mk(8, 31, "phrase", "slow down", "/sloʊ daʊn/", "（使）慢下来；（使）减速"),
      mk(8, 31, "word", "neighbourhood", "/ˈneɪbərhʊd/", "(=neighborhood) n. 街区；临近的地方"),
      mk(8, 31, "word", "roof", "/ruːf/", "n. 屋顶；顶部"),
      mk(8, 31, "word", "nearly", "/ˈnɪrli/", "adv. 几乎；差不多；将近"),
      mk(8, 31, "phrase", "come off", "/kʌm ɔːf/", "（从某物上）脱落；掉落"),
      mk(8, 31, "word", "report", "/rɪˈpɔːrt/", "n. & v. 报道；汇报"),
      mk(8, 31, "word", "trouble", "/ˈtrʌbl/", "n. 苦恼；困难；v. 使忧虑；苦恼；劳驾；麻烦"),
      mk(8, 31, "word", "relative", "/ˈrelətɪv/", "n. 亲戚；亲属"),
      mk(8, 31, "word", "truck", "/trʌk/", "n. 卡车"),
      mk(8, 31, "word", "supply", "/səˈplaɪ/", "n. 供应（量）；(pl. supplies) 补给（品）；v. 供应；供给"),
      mk(8, 31, "word", "preparation", "/ˌprepəˈreɪʃn/", "n. 准备（工作）；预备"),
      mk(8, 31, "phrase", "make preparations", "/meɪk ˌprepəˈreɪʃnz/", "作准备"),
      mk(8, 31, "word", "power", "/ˈpaʊər/", "n. 电力供应；能量；力量"),
      mk(8, 31, "word", "soundly", "/ˈsaʊndli/", "adv. （睡觉）酣畅地；可喜地；完全彻底地"),
      mk(8, 31, "word", "thick", "/θɪk/", "adj. 厚的；浓密的"),
      mk(8, 31, "word", "beat", "/biːt/", "v. (beat, beaten /ˈbiːtn/) 敲；打；敲击；跳动"),
      mk(8, 31, "word", "hide", "/haɪd/", "v. (hid /hɪd/, hidden /ˈhɪdn/) 躲避；隐藏"),
      mk(8, 31, "word", "tornado", "/tɔːrˈneɪdoʊ/", "n. 龙卷风；旋风"),
      mk(8, 31, "word", "worst", "/wɜːrst/", "adj. & adv. (bad 和 badly 的最高级) 最坏（的）；最糟（的）"),
      mk(8, 31, "word", "schoolgirl", "/ˈskuːlɡɜːrl/", "n. （学校的）女生"),
      mk(8, 31, "word", "froth", "/frɔːθ/", "n. 泡；泡沫"),
      mk(8, 31, "word", "unfortunately", "/ʌnˈfɔːrtʃənətli/", "adv. 不幸地；可惜地"),
      mk(8, 31, "word", "refuse", "/rɪˈfjuːz/", "v. 拒绝；退却"),
      mk(8, 31, "word", "security", "/sɪˈkjʊrəti/", "n. 安全；保卫；保安"),
      mk(8, 31, "word", "guard", "/ɡɑːrd/", "n. 卫兵；保卫；v. 保卫"),
      mk(8, 31, "phrase", "security guard", "/sɪˈkjʊrəti ɡɑːrd/", "保安人员"),
      mk(8, 31, "word", "nearby", "/ˌnɪrˈbaɪ/", "adj. 附近的；adv. 在附近"),
      mk(8, 31, "word", "scream", "/skriːm/", "v. 尖叫"),
      mk(8, 31, "word", "thankfully", "/ˈθæŋkfəli/", "adv. 幸亏；感激地"),
      mk(8, 31, "word", "knowledge", "/ˈnɑːlɪdʒ/", "n. 知识；学问"),
      mk(8, 31, "word", "thinking", "/ˈθɪŋkɪŋ/", "n. 思考；想法"),
      mk(8, 31, "phrase", "as soon as", "/æz suːn æz/", "……就……"),
      mk(8, 31, "word", "hero", "/ˈhɪroʊ/", "n. (pl. heroes) 英雄；男主角；偶像"),
      mk(8, 31, "word", "landslide", "/ˈlændslaɪd/", "n. 滑坡；塌方"),
      mk(8, 31, "word", "safeguard", "/ˈseɪfɡɑːrd/", "v. 保护；捍卫"),
      mk(8, 31, "word", "floodwater", "/ˈflʌdwɔːtər/", "n. 洪水"),
      mk(8, 31, "word", "manpower", "/ˈmænpaʊər/", "n. 劳动力；人力"),
      mk(8, 31, "word", "heartbeat", "/ˈhɑːrtbiːt/", "n. 心跳（声）"),
      mk(8, 31, "word", "rescue", "/ˈreskjuː/", "n. & v. 救援；营救"),
      mk(8, 31, "word", "heatwave", "/ˈhiːtweɪv/", "n. 热浪"),
      mk(8, 31, "word", "southwestern", "/ˌsaʊθˈwestərn/", "adj. 西南的；西南方向的"),
      mk(8, 31, "word", "firefighter", "/ˈfaɪərfaɪtər/", "n. 消防队员"),
      mk(8, 31, "word", "volunteer", "/ˌvɑːlənˈtɪr/", "n. 志愿者；自愿者；v. 自愿做；义务做"),
      mk(8, 31, "word", "terribly", "/ˈterəbli/", "adv. 非常糟糕地；非常"),
      mk(8, 31, "word", "alarm", "/əˈlɑːrm/", "n. 警报（器）；惊恐"),
      mk(8, 31, "phrase", "alarm clock", "/əˈlɑːrm klɑːk/", "闹钟"),
      mk(8, 31, "phrase", "go off", "/ɡoʊ ɔːf/", "（警报器等）发出响声"),
      mk(8, 31, "word", "review", "/rɪˈvjuː/", "v. 复习；回顾；复查；n. 回顾；审查"),
      mk(8, 31, "word", "sudden", "/ˈsʌdn/", "adj. 突然的；骤然"),
      mk(8, 31, "phrase", "all of a sudden", "/ɔːl əv ə ˈsʌdn/", "突然；猛地"),
      mk(8, 31, "word", "thunder", "/ˈθʌndər/", "n. 雷；雷声；v. 打雷；发出雷鸣般响声"),
      mk(8, 31, "phrase", "by the time", "/baɪ ðə taɪm/", "到……的时候"),
      mk(8, 31, "word", "usual", "/ˈjuːʒuəl/", "adj. 通常的；寻常的"),
      mk(8, 31, "phrase", "out of breath", "/aʊt əv breθ/", "上气不接下气"),
      mk(8, 31, "word", "rainstorm", "/ˈreɪnstɔːrm/", "n. 暴风雨"),
      mk(8, 31, "phrase", "as a result", "/æz ə rɪˈzʌlt/", "因此"),
      mk(8, 31, "word", "unlucky", "/ʌnˈlʌki/", "adj. 不幸的；不顺利的；不吉利的"),
      mk(8, 31, "word", "Tilly", "/ˈtɪli/", "n. 蒂莉"),
      mk(8, 31, "word", "Phuket", "/ˈpuːket/", "n. 普吉岛"),
      mk(8, 31, "word", "Indonesia", "/ˌɪndəˈniːʒə/", "n. 印度尼西亚"),
      mk(8, 31, "word", "Japan", "/dʒəˈpæn/", "n. 日本"),
    ],
  },
  {
    grade: 8,
    unit: 32,
    title: "Crossing Cultures 跨越文化",
    entries: [
      mk(8, 32, "word", "shake", "/ʃeɪk/", "v. (shook /ʃʊk/, shaken /ˈʃeɪkən/) 与（某人）握手；摇动；n. 摇动；奶昔"),
      mk(8, 32, "word", "bow", "/baʊ/", "v. & n. 鞠躬"),
      mk(8, 32, "word", "bump", "/bʌmp/", "v. 碰；撞；n. 碰撞；（撞击造成的）肿块"),
      mk(8, 32, "word", "fist", "/fɪst/", "n. 拳头"),
      mk(8, 32, "word", "rub", "/rʌb/", "v. 摩擦；揉"),
      mk(8, 32, "word", "kiss", "/kɪs/", "v. & n. 亲吻"),
      mk(8, 32, "word", "cheek", "/tʃiːk/", "n. 脸颊"),
      mk(8, 32, "word", "hug", "/hʌɡ/", "v. & n. 拥抱"),
      mk(8, 32, "word", "embarrassed", "/ɪmˈbærəst/", "adj. 尴尬的"),
      mk(8, 32, "word", "confused", "/kənˈfjuːzd/", "adj. 困惑的"),
      mk(8, 32, "word", "formal", "/ˈfɔːrml/", "adj. 正式的"),
      mk(8, 32, "word", "curry", "/ˈkɜːri/", "n. 咖喱菜"),
      mk(8, 32, "word", "rule", "/ruːl/", "n. 规章；规则"),
      mk(8, 32, "word", "uncommon", "/ʌnˈkɑːmən/", "adj. 罕见的；不寻常的"),
      mk(8, 32, "word", "palm", "/pɑːm/", "n. 手掌"),
      mk(8, 32, "word", "namaste", "/ˈnɑːmɑːsteɪ/", "interj. 有礼了（印度人行合十礼时口中所念之词）"),
      mk(8, 32, "word", "fork", "/fɔːrk/", "n. 叉子"),
      mk(8, 32, "word", "Indian", "/ˈɪndiən/", "adj. 印度的；印度人的；n. 印度人"),
      mk(8, 32, "word", "manner", "/ˈmænər/", "n. 方式；(pl. manners) 礼仪"),
      mk(8, 32, "phrase", "table manners", "/ˈteɪbl ˈmænərz/", "餐桌礼仪"),
      mk(8, 32, "word", "confusing", "/kənˈfjuːzɪŋ/", "adj. 令人困惑的；难以理解的"),
      mk(8, 32, "word", "unless", "/ənˈles/", "conj. 除非；如果不"),
      mk(8, 32, "word", "proper", "/ˈprɑːpər/", "adj. 恰当的；正确的"),
      mk(8, 32, "phrase", "sit up", "/sɪt ʌp/", "坐直"),
      mk(8, 32, "phrase", "keep ... off", "/kiːp ... ɔːf/", "使不碰触；使避开"),
      mk(8, 32, "word", "elbow", "/ˈelboʊ/", "n. 肘；肘部"),
      mk(8, 32, "word", "serving", "/ˈsɜːrvɪŋ/", "adj. 分菜用的；n. 一份食物"),
      mk(8, 32, "word", "chopstick", "/ˈtʃɑːpstɪk/", "n. (usually pl.) 筷子"),
      mk(8, 32, "phrase", "serving chopsticks", "/ˈsɜːrvɪŋ ˈtʃɑːpstɪks/", "公筷"),
      mk(8, 32, "word", "surprising", "/sərˈpraɪzɪŋ/", "adj. 出人意料的；令人吃惊的"),
      mk(8, 32, "word", "embarrassing", "/ɪmˈbærəsɪŋ/", "adj. 使人难堪的"),
      mk(8, 32, "phrase", "be used to", "/bi juːzd tuː/", "习惯于"),
      mk(8, 32, "word", "cultural", "/ˈkʌltʃərəl/", "adj. 与文化有关的；文化的"),
      mk(8, 32, "phrase", "hear from", "/hɪr frɒm/", "得到……消息"),
      mk(8, 32, "word", "custom", "/ˈkʌstəm/", "n. 习俗"),
      mk(8, 32, "word", "occasion", "/əˈkeɪʒn/", "n. 场合；重大活动"),
      mk(8, 32, "word", "nicely", "/ˈnaɪsli/", "adv. 漂亮地；令人愉悦地"),
      mk(8, 32, "word", "blouse", "/blaʊs/", "n. （女式）衬衫或短上衣"),
      mk(8, 32, "word", "private", "/ˈpraɪvət/", "adj. 不喜欢谈论私事的；私人的"),
      mk(8, 32, "word", "whether", "/ˈweðər/", "conj. 是否"),
      mk(8, 32, "word", "married", "/ˈmerid/", "adj. 已婚的；婚姻的"),
      mk(8, 32, "word", "merci", "/merˈsiː/", "interj. 谢谢（法语）"),
      mk(8, 32, "phrase", "go a long way", "/ɡoʊ ə lɔːŋ weɪ/", "帮助很大"),
      mk(8, 32, "word", "au revoir", "/ˌoʊ rəˈvwɑːr/", "interj. 再见（法语）"),
      mk(8, 32, "phrase", "get along", "/ɡet əˈlɔːŋ/", "相处融洽；进展"),
      mk(8, 32, "word", "correct", "/kəˈrekt/", "adj. 正确的；恰当的"),
      mk(8, 32, "word", "unsafe", "/ʌnˈseɪf/", "adj. 不安全的；危险的"),
      mk(8, 32, "word", "informal", "/ɪnˈfɔːrml/", "adj. 非正式的"),
      mk(8, 32, "word", "improper", "/ɪmˈprɑːpər/", "adj. 不合适的"),
      mk(8, 32, "word", "jeans", "/dʒiːnz/", "n. (pl.) 牛仔裤"),
      mk(8, 32, "word", "marry", "/ˈmeri/", "v. 结婚；娶；嫁"),
      mk(8, 32, "word", "congratulate", "/kənˈɡrætʃəleɪt/", "v. 祝贺"),
      mk(8, 32, "word", "Asian", "/ˈeɪʒn/", "adj. 亚洲的；n. 亚洲人"),
      mk(8, 32, "word", "tradition", "/trəˈdɪʃn/", "n. 传统"),
      mk(8, 32, "word", "firstly", "/ˈfɜːrstli/", "adv. 第一；首先"),
      mk(8, 32, "word", "secondly", "/ˈsekəndli/", "adv. 第二；其次"),
      mk(8, 32, "word", "thirdly", "/ˈθɜːrdli/", "adv. 第三"),
      mk(8, 32, "word", "correctly", "/kəˈrektli/", "adv. 正确地；恰当地"),
      mk(8, 32, "word", "receive", "/rɪˈsiːv/", "v. 收到"),
      mk(8, 32, "word", "sign-off", "/ˈsaɪnɔːf/", "n. （信件或广播的）结束语；收尾"),
      mk(8, 32, "word", "main", "/meɪn/", "adj. 主要的"),
      mk(8, 32, "word", "false", "/fɔːls/", "adj. 错误的；不真实的"),
      mk(8, 32, "word", "impression", "/ɪmˈpreʃn/", "n. 印象"),
      mk(8, 32, "word", "cheers", "/tʃɪrz/", "interj. 再见；干杯"),
      mk(8, 32, "word", "Ji-Hoon", "/ˈdʒiːˈhuːn/", "n. 智勋（朝鲜或韩国人名）"),
      mk(8, 32, "word", "Kaito", "/ˈkaɪtoʊ/", "n. 海斗（日本人名）"),
      mk(8, 32, "word", "Marie", "/məˈriː/", "n. 玛丽"),
      mk(8, 32, "word", "Türkiye", "/ˈtɜːrkijə/", "n. 土耳其"),
      mk(8, 32, "word", "Mexico", "/ˈmeksɪkoʊ/", "n. 墨西哥"),
      mk(8, 32, "word", "Peru", "/pəˈruː/", "n. 秘鲁"),
      mk(8, 32, "word", "Germany", "/ˈdʒɜːrməni/", "n. 德国"),
      mk(8, 32, "word", "Paris", "/ˈpærɪs/", "n. 巴黎（法国首都）"),
    ],
  },
  {
    grade: 8,
    unit: 33,
    title: "A Good Read 一本好书",
    entries: [
      mk(8, 33, "phrase", "a good read", "/ə ɡʊd riːd/", "好的读物；好书（或文章等）"),
      mk(8, 33, "word", "adventure", "/ədˈventʃər/", "n. 冒险；冒险经历"),
      mk(8, 33, "word", "fantasy", "/ˈfæntəsi/", "n. 幻想作品；幻想"),
      mk(8, 33, "word", "mystery", "/ˈmɪstri/", "n. 悬疑小说（或电影、戏剧）；神秘的事物；奥秘"),
      mk(8, 33, "word", "fiction", "/ˈfɪkʃn/", "n. 小说"),
      mk(8, 33, "word", "detective", "/dɪˈtektɪv/", "n. 侦探"),
      mk(8, 33, "word", "alien", "/ˈeɪliən/", "n. 外星人"),
      mk(8, 33, "word", "attack", "/əˈtæk/", "v. & n. 攻击；进攻"),
      mk(8, 33, "phrase", "hear of", "/hɪr əv/", "听说；得知"),
      mk(8, 33, "word", "kingdom", "/ˈkɪŋdəm/", "n. 王国"),
      mk(8, 33, "word", "historical", "/hɪˈstɔːrɪkl/", "adj. 历史的；有关历史的"),
      mk(8, 33, "word", "force", "/fɔːrs/", "v. 强迫；迫使；用力推动；n. 力；武力"),
      mk(8, 33, "word", "steal", "/stiːl/", "v. (stole /stoʊl/, stolen /ˈstoʊlən/) 偷；窃取"),
      mk(8, 33, "word", "punish", "/ˈpʌnɪʃ/", "v. 惩罚；处罚"),
      mk(8, 33, "word", "idiom", "/ˈɪdiəm/", "n. 习语；成语"),
      mk(8, 33, "word", "recently", "/ˈriːsntli/", "adv. 最近；不久前"),
      mk(8, 33, "word", "lost", "/lɔːst/", "adj. 迷路的；丢失的"),
      mk(8, 33, "phrase", "get lost", "/ɡet lɔːst/", "迷路"),
      mk(8, 33, "word", "recommend", "/ˌrekəˈmend/", "v. 推荐；建议"),
      mk(8, 33, "word", "society", "/səˈsaɪəti/", "n. 社会；社团"),
      mk(8, 33, "word", "literary", "/ˈlɪtəreri/", "adj. 文学的；文学上的"),
      mk(8, 33, "word", "base", "/beɪs/", "v. 以……为据点；n. 根据；基地；根据地"),
      mk(8, 33, "phrase", "base sth on sth", "/beɪs ˌsʌmˈθɪŋ ɑːn ˌsʌmˈθɪŋ/", "以……为基础（或根据）"),
      mk(8, 33, "word", "summary", "/ˈsʌməri/", "n. 总结；概要"),
      mk(8, 33, "word", "spoiled", "/spɔɪld/", "(=spoilt /spɔɪlt/) adj. 宠坏的；娇惯的"),
      mk(8, 33, "word", "selfish", "/ˈselfɪʃ/", "adj. 自私的"),
      mk(8, 33, "word", "painful", "/ˈpeɪnfl/", "adj. 令人痛苦的；（身体部位）疼痛的"),
      mk(8, 33, "word", "lock", "/lɑːk/", "v. & n. 锁；锁上"),
      mk(8, 33, "phrase", "lock up", "/lɑːk ʌp/", "锁好（建筑物的）门"),
      mk(8, 33, "word", "unlock", "/ʌnˈlɑːk/", "v. 开……的锁；发现；揭开"),
      mk(8, 33, "word", "hidden", "/ˈhɪdn/", "adj. 隐藏的；秘密的"),
      mk(8, 33, "word", "nobody", "/ˈnoʊbɑːdi/", "pron. 没有人；谁也不"),
      mk(8, 33, "word", "therefore", "/ˈðerfɔːr/", "adv. 因此；所以"),
      mk(8, 33, "word", "state", "/steɪt/", "n. 状态；国家；州；v. 陈述；说明"),
      mk(8, 33, "word", "weak", "/wiːk/", "adj. 虚弱的；（能力）弱的"),
      mk(8, 33, "word", "since", "/sɪns/", "prep., adv. & conj. 自……以后；从……以来；conj. 既然；由于"),
      mk(8, 33, "word", "secretly", "/ˈsiːkrətli/", "adv. 秘密地"),
      mk(8, 33, "word", "prove", "/pruːv/", "v. (proved, proved 或 proven /ˈpruːvn/) 证明；证实；显示是"),
      mk(8, 33, "phrase", "get to one's feet", "/ɡet tu wʌnz fiːt/", "站起身来"),
      mk(8, 33, "phrase", "day by day", "/deɪ baɪ deɪ/", "一天天；逐日"),
      mk(8, 33, "word", "build-up", "/ˈbɪldʌp/", "n. 准备期；准备过程"),
      mk(8, 33, "word", "climax", "/ˈklaɪmæks/", "n. 高潮；极点"),
      mk(8, 33, "word", "effect", "/ɪˈfekt/", "n. 影响；结果"),
      mk(8, 33, "phrase", "in time", "/ɪn taɪm/", "及时；来得及"),
      mk(8, 33, "word", "reader", "/ˈriːdər/", "n. 读者；简易读物"),
      mk(8, 33, "word", "librarian", "/laɪˈbreriən/", "n. 图书管理员；图书馆馆长"),
      mk(8, 33, "word", "consider", "/kənˈsɪdər/", "v. 认为；仔细考虑"),
      mk(8, 33, "word", "enemy", "/ˈenəmi/", "n. 敌人"),
      mk(8, 33, "word", "naughty", "/ˈnɔːti/", "adj. 淘气的"),
      mk(8, 33, "word", "gentle", "/ˈdʒentl/", "adj. 温柔的"),
      mk(8, 33, "word", "defeat", "/dɪˈfiːt/", "v. 击败；战胜；n. 失败；击败"),
      mk(8, 33, "word", "basic", "/ˈbeɪsɪk/", "adj. 基本的；初步的"),
      mk(8, 33, "word", "recommendation", "/ˌrekəmenˈdeɪʃn/", "n. 推荐；提议"),
      mk(8, 33, "word", "American", "/əˈmerɪkən/", "adj. 美国的；美洲的；n. 美国人；美洲人"),
      mk(8, 33, "word", "bone", "/boʊn/", "n. 骨头"),
      mk(8, 33, "word", "doubt", "/daʊt/", "v. 怀疑；n. 疑惑；不确定"),
      mk(8, 33, "word", "inspire", "/ɪnˈspaɪər/", "v. 激励；鼓舞"),
      mk(8, 33, "word", "destroy", "/dɪˈstrɔɪ/", "v. 破坏；摧毁"),
      mk(8, 33, "word", "introduction", "/ˌɪntrəˈdʌkʃn/", "n. 介绍；序言"),
      mk(8, 33, "word", "Journey to the West", "/ˈdʒɜːrni tu ðə west/", "《西游记》"),
      mk(8, 33, "word", "Harry Potter and the Philosopher's Stone", "/ˈhæri ˈpɑːtər ænd ðə fɪˈlɑːsəfərz stoʊn/", "《哈利·波特与魔法石》"),
      mk(8, 33, "word", "The Time Machine", "/ˈtʃiːm ˈmeɪʃn/", "《时间机器》"),
      mk(8, 33, "word", "The Final Problem", "/ˈfʌɪnəl ˈprɑːbləm/", "《最后一案》"),
      mk(8, 33, "word", "The Three-Body Problem", "/θriː ˈbɑːdi ˈprɑːbləm/", "《三体》"),
      mk(8, 33, "word", "Around the World in Eighty Days", "/əˈraʊnd ðə wɜːrld ɪn ˈeɪti deɪz/", "《八十天环游地球》"),
      mk(8, 33, "word", "Sherlock Holmes", "/ˈʃɜːrlɑːk hoʊmz/", "夏洛克·福尔摩斯"),
      mk(8, 33, "word", "The Romance of the Three Kingdoms", "/ˈroʊmæns əv ðə θriː ˈkɪŋdəmz/", "《三国演义》"),
      mk(8, 33, "word", "Oliver Twist", "/ˈɑːlɪvər twɪst/", "《雾都孤儿》"),
      mk(8, 33, "word", "Charles Dickens", "/tʃɑːrlz ˈdɪkɪnz/", "查尔斯·狄更斯"),
      mk(8, 33, "word", "Alice's Adventures in Wonderland", "/ˈælɪsɪz ədˈventʃərz ɪn ˈwʌndərlænd/", "《爱丽丝梦游仙境》"),
      mk(8, 33, "word", "Lewis Carroll", "/ˈluːɪs ˈkærəl/", "刘易斯·卡罗尔"),
      mk(8, 33, "word", "The Little Prince", "/ˈlɪtl prɪns/", "《小王子》"),
      mk(8, 33, "word", "The Little Match Girl", "/ˈlɪtl mætʃ ɡɜːrl/", "《卖火柴的小女孩》"),
      mk(8, 33, "word", "Outlaws of the Marsh", "/ˈaʊtlɔːz əv ðə mɑːrʃ/", "《水浒传》"),
      mk(8, 33, "word", "The Adventures of Tom Sawyer", "/ədˈventʃərz əv tɑːm ˈsɔːjər/", "《汤姆·索亚历险记》"),
      mk(8, 33, "word", "My Childhood", "/maɪ ˈtʃaɪldhʊd/", "《童年》"),
      mk(8, 33, "word", "The Wonderful Wizard of Oz", "/ˈwʌndərfl ˈwɪzərd əv ɑːz/", "《绿野仙踪》"),
      mk(8, 33, "word", "A Dream of Red Mansions", "/ə driːm əv red ˈmænʃənz/", "《红楼梦》"),
      mk(8, 33, "word", "Treasure Island", "/ˈtreʒər ˈaɪlənd/", "《金银岛》"),
      mk(8, 33, "word", "Red Star over China", "/red stɑːr ˈoʊvər ˈtʃaɪnə/", "《红星照耀中国》"),
      mk(8, 33, "word", "The Secret Garden", "/ðə ˈsiːkrət ˈɡɜːrn/", "《秘密花园》"),
      mk(8, 33, "word", "Frances Hodgson Burnett", "/ˈfrænsɪz ˈhɑːdʒsən bɜːrˈnet/", "弗朗西丝·霍奇森·伯内特"),
      mk(8, 33, "word", "Lennox", "/ˈlenəks/", "n. 伦诺克斯"),
      mk(8, 33, "word", "Craven", "/ˈkreɪvn/", "n. 克雷文"),
      mk(8, 33, "word", "Dickon", "/ˈdɪkən/", "n. 迪肯"),
      mk(8, 33, "word", "Colin", "/ˈkɑːlɪn/", "n. 科林"),
      mk(8, 33, "word", "The Old Man and the Sea", "/ˈoʊld mæn ænd ðə siː/", "《老人与海》"),
      mk(8, 33, "word", "Ernest Hemingway", "/ˈɜːrnɪst ˈhemɪŋweɪ/", "欧内斯特·海明威"),
      mk(8, 33, "word", "Pulitzer Prize", "/ˈpʊlɪtsər praɪz/", "普利策奖"),
    ],
  },
  {
    grade: 8,
    unit: 34,
    title: "Making a Difference 有所作为",
    entries: [
      mk(8, 34, "phrase", "make a difference", "/meɪk ə ˈdɪfrəns/", "有作用；有影响"),
      mk(8, 34, "word", "visitor", "/ˈvɪzɪtər/", "n. 参观者；来访者"),
      mk(8, 34, "word", "elderly", "/ˈeldərli/", "adj. 年纪较大的；上了年纪的"),
      mk(8, 34, "phrase", "the elderly", "/ði ˈeldərli/", "老人；上了年纪的人"),
      mk(8, 34, "word", "organization", "/ˌɔːrɡənəˈzeɪʃn/", "(=organisation) n. 组织；团体；机构"),
      mk(8, 34, "word", "stadium", "/ˈsteɪdiəm/", "n. 体育馆；运动场"),
      mk(8, 34, "word", "provide", "/prəˈvaɪd/", "v. 提供；给予"),
      mk(8, 34, "word", "can", "/kæn/", "n. (盛食品或饮料的) 金属罐；一罐（的量）"),
      mk(8, 34, "word", "owner", "/ˈoʊnər/", "n. 主人；物主"),
      mk(8, 34, "word", "cage", "/keɪdʒ/", "n. 笼子"),
      mk(8, 34, "word", "donation", "/doʊˈneɪʃn/", "n. 捐赠物；捐赠"),
      mk(8, 34, "word", "shelter", "/ˈʃeltər/", "n. 庇护所；居所"),
      mk(8, 34, "word", "interviewer", "/ˈɪntərvjuːər/", "n. 面试官；采访者"),
      mk(8, 34, "word", "youth", "/juːθ/", "n. 青年；青年时期"),
      mk(8, 34, "phrase", "nursing home", "/ˈnɜːrsɪŋ hoʊm/", "养老院"),
      mk(8, 34, "word", "active", "/ˈæktɪv/", "adj. 活跃的；积极的"),
      mk(8, 34, "phrase", "come along", "/kʌm əˈlɔːŋ/", "赶快；跟着来"),
      mk(8, 34, "word", "army", "/ˈɑːrmi/", "n. 军队"),
      mk(8, 34, "word", "soldier", "/ˈsoʊldʒər/", "n. 军人；士兵"),
      mk(8, 34, "word", "primary", "/ˈpraɪmeri/", "adj. 小学教育的；首要的"),
      mk(8, 34, "phrase", "help out", "/help aʊt/", "分担工作；帮忙做"),
      mk(8, 34, "word", "charity", "/ˈtʃærəti/", "n. 慈善机构（或组织）；慈善事业"),
      mk(8, 34, "word", "warmly", "/ˈwɔːrmli/", "adv. 热情地；温暖地"),
      mk(8, 34, "word", "lady", "/ˈleɪdi/", "n. 女士；淑女"),
      mk(8, 34, "word", "gentleman", "/ˈdʒentlmən/", "n. (pl. gentlemen /ˈdʒentlmən/) 先生；君子"),
      mk(8, 34, "word", "bark", "/bɑːrk/", "v. (狗) 吠叫；n. 狗叫声"),
      mk(8, 34, "phrase", "sign up", "/saɪn ʌp/", "报名"),
      mk(8, 34, "phrase", "ever since", "/ˈevər sɪns/", "自从；自……以后"),
      mk(8, 34, "word", "adult", "/ˈædʌlt/", "n. 成年人；adj. 成年的；成熟的"),
      mk(8, 34, "word", "missing", "/ˈmɪsɪŋ/", "adj. 失踪的；丢失的"),
      mk(8, 34, "word", "practical", "/ˈpræktɪkl/", "adj. 实用的；实际的"),
      mk(8, 34, "word", "life-saving", "/ˈlaɪfˌseɪvɪŋ/", "adj. 救命的；救生的"),
      mk(8, 34, "word", "teamwork", "/ˈtiːmwɜːrk/", "n. 团队合作"),
      mk(8, 34, "word", "successful", "/səkˈsesfl/", "adj. 成功的；有成就的"),
      mk(8, 34, "phrase", "most of all", "/moʊst əv ɔːl/", "最主要是"),
      mk(8, 34, "word", "value", "/ˈvæljuː/", "n. 重要作用；价值"),
      mk(8, 34, "word", "voluntary", "/ˈvɑːlənteri/", "adj. 自愿的；无偿的"),
      mk(8, 34, "word", "ordinary", "/ˈɔːrdneri/", "adj. 平凡的；普通的"),
      mk(8, 34, "word", "worth", "/wɜːrθ/", "adj. 值得；有价值"),
      mk(8, 34, "word", "audience", "/ˈɔːdiəns/", "n. 听众；观众"),
      mk(8, 34, "word", "willing", "/ˈwɪlɪŋ/", "adj. 乐意的；愿意的"),
      mk(8, 34, "phrase", "on the go", "/ɑːn ðə ɡoʊ/", "在忙碌中"),
      mk(8, 34, "phrase", "in need", "/ɪn niːd/", "需要帮助的；生活困难的"),
      mk(8, 34, "word", "completely", "/kəmˈpliːtli/", "adv. 完全地；彻底地"),
      mk(8, 34, "word", "success", "/səkˈses/", "n. 成功"),
      mk(8, 34, "word", "elder", "/ˈeldər/", "adj. （两人中）年纪较长的（尤指哥哥姐姐）"),
      mk(8, 34, "word", "donate", "/doʊˈneɪt/", "v. 捐赠；赠送"),
      mk(8, 34, "word", "pocket", "/ˈpɑːkɪt/", "n. 口袋"),
      mk(8, 34, "phrase", "pocket money", "/ˈpɑːkɪt ˈmʌni/", "零花钱"),
      mk(8, 34, "word", "effort", "/ˈefərt/", "n. 努力；艰难的尝试"),
      mk(8, 34, "phrase", "hand out", "/hænd aʊt/", "分发"),
      mk(8, 34, "phrase", "familiar with", "/fəˈmɪliər wɪð/", "通晓；熟悉"),
      mk(8, 34, "word", "etc.", "/et ˈsetərə/", "等等；以及诸如此类"),
      mk(8, 34, "word", "talent", "/ˈtælənt/", "n. 才能；天赋；天才"),
      mk(8, 34, "word", "madam", "/ˈmædəm/", "n. （正式、礼貌的称呼）女士；夫人"),
      mk(8, 34, "word", "advertisement", "/ədˈvɜːrtɪsmənt/", "(=ad /æd/) n. 广告；启事"),
      mk(8, 34, "word", "Robert", "/ˈrɑːbərt/", "n. 罗伯特"),
      mk(8, 34, "word", "Argentina", "/ˌɑːrdʒənˈtiːnə/", "n. 阿根廷"),
      mk(8, 34, "word", "Blue Sky Rescue", "/bluː skaɪ ˈreskjuː/", "蓝天救援队"),
      mk(8, 34, "word", "Philippines", "/ˈfɪlɪpiːnz/", "n. 菲律宾"),
    ],
  },
`;

// 旧 END_MARK 后接的换行符也属于 patch 范围以外：保留
const startIdx = FILE_CONTENT.indexOf(OLD_START_MARK);
if (startIdx < 0) throw new Error('OLD_START_MARK not found');
const endIdx = FILE_CONTENT.indexOf(OLD_END_MARK, startIdx);
if (endIdx < 0) throw new Error('OLD_END_MARK not found');

const before = FILE_CONTENT.slice(0, startIdx);
const after  = FILE_CONTENT.slice(endIdx + OLD_END_MARK.length);
const next = before + NEW_BLOCK + OLD_END_MARK + after;

fs.writeFileSync(FILE, next, 'utf8');
console.log(`patched G8X: ${FILE}`);
console.log(`old segment ${OLD_START_MARK.length + (endIdx - startIdx)} chars → new segment ${NEW_BLOCK.length} chars`);