// scripts/patch_g8s.mjs
// PEP 2024 秋新版八年级上册（初二上）整段重做
// 用户 2026-09-05 拍 16 张截图：
//   - 2 张 CONTENTS（II-V + IV-V，8 Unit 标题 + Section A/B + Project + 附录页码）
//   - 12 张 Vocabulary in Each Unit P111-122（U1-U8 全部词条 + 专有名词）
// 旧结构（Go for it 2012 旧版）：G8U1-10（精简版，每单元 10 词）
// 新结构（PEP 2024 秋新版）：8 个正式 Unit
//   U1  Happy Holiday
//   U2  Home Sweet Home
//   U3  Same or Different?
//   U4  Amazing Plants and Animals
//   U5  What a Delicious Meal!
//   U6  Plan for Yourself
//   U7  When Tomorrow Comes
//   U8  Let's Communicate!
//
// 单元编号延续 G7：七上 U1-10 + 七下 U11-18 + 八上 U19-U26。
//
// 设计原则（patch_unit_template）：
//   OLD_END_MARK 仅含下段注释起点（不含闭合括号）；NEW_BLOCK 末尾自带 \n  },\n

import fs from 'node:fs';

const FILE = 'src/data/grades4to9.ts';
const OLD_START_MARK = `  // ==================== 八年级上（Go for it 八上全册） ====================
`;
const OLD_END_MARK = `  // ==================== 八年级下（Go for it 八下 U1-2） ====================
`;

const NEW_BLOCK = `  // ==================== 八年级上（PEP 2024 秋新版 · 8 Unit） ====================
  // 数据来源：用户 2026-09-05 拍 16 张（CONTENTS II-V + Vocabulary in Each Unit P111-122）
  // 旧版（Go for it 2012）精简版 10 个 unit 整体替换为新版 8 个 unit
  {
    grade: 8,
    unit: 19,
    title: "Happy Holiday 愉快的假期",
    entries: [
      mk(8, 19, "word", "ancient", "/ˈeɪnʃənt/", "adj. 古代的；古老的"),
      mk(8, 19, "word", "camp", "/kæmp/", "n. 度假营；营地；v. 露营；宿营"),
      mk(8, 19, "word", "landscape", "/ˈlændskeɪp/", "n. 风景；景色"),
      mk(8, 19, "word", "strange", "/streɪndʒ/", "adj. 奇怪的；陌生的"),
      mk(8, 19, "word", "vacation", "/veɪˈkeɪʃən/", "n. 假期；度假"),
      mk(8, 19, "word", "fantastic", "/fænˈtæstɪk/", "adj. 极好的；吸引人的"),
      mk(8, 19, "word", "town", "/taʊn/", "n. 镇；商业区"),
      mk(8, 19, "word", "breath", "/breθ/", "n. 呼吸的空气；一口气"),
      mk(8, 19, "phrase", "take one's breath away", "/teɪk wʌnz breθ əˈweɪ/", "令人惊叹；让人叹绝"),
      mk(8, 19, "word", "especially", "/ɪˈspeʃəli/", "adv. 尤其；特别"),
      mk(8, 19, "phrase", "steamed chicken soup", "/stiːmd ˈtʃɪkɪn suːp/", "汽锅鸡"),
      mk(8, 19, "word", "anywhere", "/ˈeniwer/", "adv. & pron. 在任何地方；随便哪个地方"),
      mk(8, 19, "word", "nothing", "/ˈnʌθɪŋ/", "pron. 没有事；没有任何东西"),
      mk(8, 19, "word", "relaxing", "/rɪˈlæksɪŋ/", "adj. 轻松的；令人放松的"),
      mk(8, 19, "word", "guide", "/ɡaɪd/", "n. 导游；指南；手册；v. 给某人领路；指导"),
      mk(8, 19, "word", "scenery", "/ˈsiːnəri/", "n. 风景；景色"),
      mk(8, 19, "word", "silk", "/sɪlk/", "n. 丝绸；（蚕）丝"),
      mk(8, 19, "word", "scarf", "/skɑːrf/", "n. 围巾；披巾"),
      mk(8, 19, "word", "ready", "/ˈredi/", "adj. 准备好的；现成的；adv. 已就完；已完成"),
      mk(8, 19, "phrase", "ready to do sth", "/ˈredi tu duː sʌmθɪŋ/", "马上要（做某事）；愿意做（某事）"),
      mk(8, 19, "word", "somewhere", "/ˈsʌmwer/", "adv. 在某处；到某处；pron. 某处；某个地方"),
      mk(8, 19, "word", "myself", "/maɪˈself/", "pron. 我自己"),
      mk(8, 19, "phrase", "nothing but", "/ˈnʌθɪŋ bʌt/", "只有；只是"),
      mk(8, 19, "word", "hotel", "/hoʊˈtel/", "n. 旅馆；旅社"),
      mk(8, 19, "word", "comfortable", "/ˈkʌmftəbəl/", "adj. 使人舒服的；舒适的"),
      mk(8, 19, "word", "bored", "/bɔːrd/", "adj. 厌倦的；烦闷的"),
      mk(8, 19, "word", "sky", "/skaɪ/", "n. 天；天空"),
      mk(8, 19, "word", "towards", "/təˈwɔːrdz/", "(= toward) prep. 向；朝"),
      mk(8, 19, "word", "rainbow", "/ˈreɪnboʊ/", "n. 虹；彩虹"),
      mk(8, 19, "word", "square", "/skwer/", "n. 广场；正方形；adj. 正方形的；方的"),
      mk(8, 19, "word", "during", "/ˈdʊrɪŋ/", "prep. 在……期间"),
      mk(8, 19, "word", "victory", "/ˈvɪktəri/", "n. 胜利；成功"),
      mk(8, 19, "word", "Russian", "/ˈrʌʃən/", "adj. 俄罗斯的；俄罗斯人的；n. 俄罗斯人；俄语"),
      mk(8, 19, "word", "fight", "/faɪt/", "n. 战斗；搏斗；斗争；v. (fought) 打仗；打架"),
      mk(8, 19, "word", "against", "/əˈɡenst/", "prep. 反对；与……相反；紧靠"),
      mk(8, 19, "phrase", "fight against sb / sth", "/faɪt əˈɡenst/", "与……作战；与……作斗争"),
      mk(8, 19, "word", "artwork", "/ˈɑːrtwɜːrk/", "n. 艺术作品；插图"),
      mk(8, 19, "phrase", "thousands of", "/ˈθaʊzəndz əv/", "数以千计的；成千上万的"),
      mk(8, 19, "word", "tear", "/tɪr/", "n. 眼泪；泪水"),
      mk(8, 19, "word", "remind", "/rɪˈmaɪnd/", "v. 提醒；使想起"),
      mk(8, 19, "word", "peace", "/piːs/", "n. 和平；太平"),
      mk(8, 19, "word", "easily", "/ˈiːzəli/", "adv. 容易地；轻易地"),
      mk(8, 19, "word", "forget", "/fərˈɡet/", "v. (forgot) 忘记；遗忘"),
      mk(8, 19, "word", "noon", "/nuːn/", "n. 正午；中午"),
      mk(8, 19, "word", "sick", "/sɪk/", "adj. 恶心的；生病的"),
      mk(8, 19, "word", "metro", "/ˈmetroʊ/", "n. 地下轨道系统"),
      mk(8, 19, "word", "station", "/ˈsteɪʃən/", "n. 车站；所；局"),
      mk(8, 19, "word", "palace", "/ˈpæləs/", "n. 王宫；宫殿"),
      mk(8, 19, "word", "accordion", "/əˈkɔːrdiən/", "n. 手风琴"),
      mk(8, 19, "phrase", "get together", "/ɡet təˈɡeðər/", "聚会；相聚"),
      mk(8, 19, "phrase", "in the sun", "/ɪn ðə sʌn/", "在阳光下"),
      mk(8, 19, "word", "tower", "/ˈtaʊər/", "n. 塔；塔楼"),
      mk(8, 19, "word", "might", "/maɪt/", "modal v. 可能；可以"),
      mk(8, 19, "word", "budget", "/ˈbʌdʒɪt/", "n. 预算；v. 把……编入预算；精打细算"),
      mk(8, 19, "word", "passport", "/ˈpæspɔːrt/", "n. 护照"),
      mk(8, 19, "word", "forgetful", "/fərˈɡetfəl/", "adj. 健忘的；好忘事的"),
      mk(8, 19, "word", "faraway", "/ˈfɑːrəˌweɪ/", "adj. 远方的；遥远的"),
      mk(8, 19, "word", "regular", "/ˈreɡjələr/", "adj. 平常的；有规律的"),
      mk(8, 19, "word", "countryside", "/ˈkʌntriˌsaɪd/", "n. 乡村；农村"),
      mk(8, 19, "phrase", "turn around", "/tɜːrn əˈraʊnd/", "转身；翻转"),
      mk(8, 19, "word", "surprised", "/sərˈpraɪzd/", "adj. 惊奇的；惊讶的"),
      mk(8, 19, "word", "deer", "/dɪr/", "n. (pl deer) 鹿"),
      mk(8, 19, "word", "probably", "/ˈprɑːbəbli/", "adv. 很可能；大概"),
      mk(8, 19, "phrase", "look for", "/lʊk fɔːr/", "寻找"),
      mk(8, 19, "word", "Guest-Greeting Pine", "/ɡest ɡriːtɪŋ paɪn/", "迎客松"),
      mk(8, 19, "word", "Sea of Clouds", "/siː əv klaʊdz/", "云海"),
      mk(8, 19, "word", "Seattle", "/siˈætəl/", "n. 西雅图（美国城市）"),
      mk(8, 19, "word", "Red Square", "/red skwer/", "红场"),
      mk(8, 19, "word", "Alexander Garden", "/ˌælɪɡˈzændər ˈɡɑːrdən/", "亚历山大花园"),
      mk(8, 19, "word", "Vincent", "/ˈvɪnsənt/", "n. 文森特"),
      mk(8, 19, "word", "Moscow", "/ˈmɑːskaʊ/", "n. 莫斯科（俄罗斯首都）"),
      mk(8, 19, "word", "Russia", "/ˈrʌʃə/", "n. 俄罗斯"),
      mk(8, 19, "word", "the Victory Museum", "/ðə ˈvɪktəri mjuˈziəm/", "胜利博物馆"),
      mk(8, 19, "word", "Nazi", "/ˈnɑːtsi/", "n. 纳粹党人；纳粹分子"),
      mk(8, 19, "word", "World War II", "/wɜːrld wɔːr tuː/", "第二次世界大战"),
      mk(8, 19, "word", "Moscow Metro", "/ˈmɑːskaʊ ˈmetroʊ/", "莫斯科地铁"),
      mk(8, 19, "word", "Scotland", "/ˈskɑːtlənd/", "n. 苏格兰"),
    ],
  },
  {
    grade: 8,
    unit: 20,
    title: "Home Sweet Home 家，甜蜜的家",
    entries: [
      mk(8, 20, "word", "pack", "/pæk/", "v. 打包；收拾"),
      mk(8, 20, "phrase", "pack up", "/pæk ʌp/", "打包"),
      mk(8, 20, "word", "bathroom", "/ˈbæθruːm/", "n. 浴室；洗手间"),
      mk(8, 20, "word", "sort", "/sɔːrt/", "v. 把……分类；整理；n. 种类"),
      mk(8, 20, "word", "bedroom", "/ˈbedruːm/", "n. 卧室"),
      mk(8, 20, "word", "balcony", "/ˈbælkəni/", "n. 阳台"),
      mk(8, 20, "phrase", "hang up", "/hæŋ ʌp/", "挂起；挂断电话"),
      mk(8, 20, "word", "invite", "/ɪnˈvaɪt/", "v. 邀请"),
      mk(8, 20, "phrase", "living room", "/ˈlɪvɪŋ ruːm/", "客厅"),
      mk(8, 20, "word", "arrival", "/əˈraɪvəl/", "n. 到达"),
      mk(8, 20, "word", "yet", "/jet/", "adv. (用于否定句和疑问句) 还；conj. 但是"),
      mk(8, 20, "word", "add", "/æd/", "v. 添加；加"),
      mk(8, 20, "phrase", "add sth to sth", "/æd sʌmθɪŋ tuː sʌmθɪŋ/", "把……加入……"),
      mk(8, 20, "phrase", "go shopping", "/ɡoʊ ˈʃɑːpɪŋ/", "去购物"),
      mk(8, 20, "word", "biscuit", "/ˈbɪskɪt/", "n. 饼干"),
      mk(8, 20, "word", "borrow", "/ˈbɑːroʊ/", "v. 借"),
      mk(8, 20, "word", "plan", "/plæn/", "v. 筹划；打算；n. 计划；方案"),
      mk(8, 20, "word", "treasure", "/ˈtreʒər/", "n. 宝物；财富；v. 珍视"),
      mk(8, 20, "phrase", "treasure hunt", "/ˈtreʒər hʌnt/", "寻宝游戏"),
      mk(8, 20, "word", "hunt", "/hʌnt/", "n. 搜寻；狩猎；v. 搜寻；打猎"),
      mk(8, 20, "word", "lift", "/lɪft/", "n. 搭便车；电梯；v. 举起；抬起"),
      mk(8, 20, "phrase", "give sb a lift", "/ɡɪv sʌmwʌn ə lɪft/", "开车顺便送某人"),
      mk(8, 20, "word", "until", "/ənˈtɪl/", "prep. 到……时；直到……为止"),
      mk(8, 20, "phrase", "be careful with", "/bi ˈkerfəl wɪð/", "注意；当心"),
      mk(8, 20, "word", "movie", "/ˈmuːvi/", "n. 电影"),
      mk(8, 20, "phrase", "the movies", "/ðə ˈmuːviz/", "电影院；电影产业"),
      mk(8, 20, "word", "dead", "/ded/", "adj. 不运行的；死的"),
      mk(8, 20, "word", "note", "/noʊt/", "n. 笔记；记录；便条；v. 注意；指出"),
      mk(8, 20, "phrase", "take notes", "/teɪk noʊts/", "做笔记"),
      mk(8, 20, "phrase", "clean up", "/kliːn ʌp/", "清扫"),
      mk(8, 20, "word", "community", "/kəˈmjuːnəti/", "n. 社区；社团"),
      mk(8, 20, "word", "rubbish", "/ˈrʌbɪʃ/", "n. 垃圾"),
      mk(8, 20, "word", "almost", "/ˈɔːlmoʊst/", "adv. 差不多；几乎"),
      mk(8, 20, "word", "journey", "/ˈdʒɜːrni/", "n. 旅行；历程；v. 旅行"),
      mk(8, 20, "word", "pull", "/pʊl/", "v. & n. 拉；拖；拽"),
      mk(8, 20, "word", "luggage", "/ˈlʌɡɪdʒ/", "n. 行李"),
      mk(8, 20, "word", "ah", "/ɑː/", "/ə/ interj. (表示高兴、惊奇等)"),
      mk(8, 20, "phrase", "share sth with sb", "/ʃer sʌmθɪŋ wɪð sʌmwʌn/", "把……分享"),
      mk(8, 20, "word", "mm", "/mː/", "(= mmm) interj. 嗯（表示喜欢、同意等）"),
      mk(8, 20, "word", "familiar", "/fəˈmɪliər/", "adj. 熟悉的"),
      mk(8, 20, "word", "joke", "/dʒoʊk/", "n. 笑话；v. 开玩笑"),
      mk(8, 20, "word", "several", "/ˈsevərəl/", "pron. 几个；一些"),
      mk(8, 20, "word", "nod", "/nɑːd/", "v. & n. 点头"),
      mk(8, 20, "word", "writer", "/ˈraɪtər/", "n. 作者"),
      mk(8, 20, "word", "text", "/tekst/", "n. 正文；文本；v. (用手机给某人) 发短信"),
      mk(8, 20, "word", "describe", "/dɪˈskraɪb/", "v. 描述；形容"),
      mk(8, 20, "word", "wherever", "/werˈevər/", "adv. & conj. 无论去哪里；在任何地方"),
      mk(8, 20, "word", "matter", "/ˈmætər/", "v. 要紧；n. 问题"),
      mk(8, 20, "phrase", "no matter", "/noʊ ˈmætər/", "不论；不要紧"),
      mk(8, 20, "word", "perhaps", "/pərˈhæps/", "adv. 也许；可能"),
      mk(8, 20, "word", "plate", "/pleɪt/", "n. 盘子；碟子"),
      mk(8, 20, "word", "freshly", "/ˈfreʃli/", "adv. 刚刚"),
      mk(8, 20, "word", "smell", "/smel/", "v. 发觉；闻到；n. 气味；臭味"),
      mk(8, 20, "word", "joy", "/dʒɔɪ/", "n. 喜悦；乐趣"),
      mk(8, 20, "word", "apartment", "/əˈpɑːrtmənt/", "n. 房间；公寓套房"),
      mk(8, 20, "word", "block", "/blɑːk/", "n. 大楼；街区；大块；v. 阻挡；堵塞"),
      mk(8, 20, "word", "decorate", "/ˈdekəreɪt/", "v. 装饰；装潢"),
      mk(8, 20, "word", "cover", "/ˈkʌvər/", "v. 遮盖；包括；n. 遮盖物；封皮"),
      mk(8, 20, "word", "poster", "/ˈpoʊstər/", "n. 海报"),
      mk(8, 20, "word", "scissors", "/ˈsɪzərz/", "n. (pl) 剪刀"),
      mk(8, 20, "word", "glue", "/ɡluː/", "n. 胶水；v. 粘贴"),
      mk(8, 20, "word", "paper-cut", "/ˈpeɪpər kʌt/", "n. 剪纸"),
    ],
  },
  {
    grade: 8,
    unit: 21,
    title: "Same or Different? 相同还是不同？",
    entries: [
      mk(8, 21, "word", "compare", "/kəmˈper/", "v. 比较；对比"),
      mk(8, 21, "word", "shy", "/ʃaɪ/", "adj. 害羞的"),
      mk(8, 21, "word", "lazy", "/ˈleɪzi/", "adj. 懒惰的；懒洋洋的"),
      mk(8, 21, "word", "loud", "/laʊd/", "adv. 响亮地；adj. 大声的"),
      mk(8, 21, "word", "outgoing", "/ˈaʊtˌɡoʊɪŋ/", "adj. 外向的"),
      mk(8, 21, "word", "hard-working", "/ˌhɑːrd ˈwɜːrkɪŋ/", "adj. 勤奋的"),
      mk(8, 21, "word", "perform", "/pərˈfɔːrm/", "v. 表演；执行"),
      mk(8, 21, "word", "alone", "/əˈloʊn/", "adv. & adj. 独自；单独"),
      mk(8, 21, "word", "solve", "/sɑːlv/", "v. 解决；解答"),
      mk(8, 21, "word", "flute", "/fluːt/", "n. 长笛"),
      mk(8, 21, "word", "congratulation", "/kənˌɡrætʃəˈleɪʃən/", "n. 祝贺；恭喜"),
      mk(8, 21, "phrase", "Congratulations (on ...)!", "/kənˌɡrætʃəˈleɪʃənz ɑːn/", "（对……表示）祝贺！"),
      mk(8, 21, "word", "prize", "/praɪz/", "n. 奖；奖励"),
      mk(8, 21, "word", "attend", "/əˈtend/", "v. 参加；出席"),
      mk(8, 21, "phrase", "as ... as ...", "/æz ... æz/", "像……一样"),
      mk(8, 21, "word", "besides", "/bɪˈsaɪdz/", "prep. 除……之外（还）；adv. 而且"),
      mk(8, 21, "word", "spare", "/sper/", "adj. 空闲的；备用的；v. 抽出；拨出"),
      mk(8, 21, "phrase", "spare time", "/sper taɪm/", "空闲时间"),
      mk(8, 21, "word", "pleasure", "/ˈpleʒər/", "n. 乐事；愉快；荣幸"),
      mk(8, 21, "phrase", "have sth in common", "/hæv sʌmθɪŋ ɪn ˈkɑːmən/", "有共同之处"),
      mk(8, 21, "word", "appearance", "/əˈpɪrəns/", "n. 外表；露面"),
      mk(8, 21, "word", "personality", "/ˌpɜːrsəˈnæləti/", "n. 性格；品质"),
      mk(8, 21, "word", "serious", "/ˈsɪriəs/", "adj. 严肃的；严重的"),
      mk(8, 21, "word", "strength", "/streŋθ/", "n. 优势；力量"),
      mk(8, 21, "word", "slim", "/slɪm/", "adj. 苗条的；薄的"),
      mk(8, 21, "word", "fact", "/fækt/", "n. 事实；现实"),
      mk(8, 21, "word", "population", "/ˌpɑːpjəˈleɪʃən/", "n. 人口"),
      mk(8, 21, "word", "km", "/keɪləmɪtər/", "(= kilometre) 千米；公里"),
      mk(8, 21, "word", "average", "/ˈævərɪdʒ/", "adj. 平均的；平常的；n. 平均数；平均水平"),
      mk(8, 21, "word", "rainfall", "/ˈreɪnfɔːl/", "n. 降雨量"),
      mk(8, 21, "word", "per", "/pər/", "prep. 每"),
      mk(8, 21, "word", "mm", "/mɪlɪmiːtər/", "(= millimetre) 毫米"),
      mk(8, 21, "word", "pleasant", "/ˈplezənt/", "adj. 宜人的；友好的"),
      mk(8, 21, "word", "forum", "/ˈfɔːrəm/", "n. 论坛；讨论会"),
      mk(8, 21, "word", "difference", "/ˈdɪfrəns/", "n. 差异"),
      mk(8, 21, "word", "alike", "/əˈlaɪk/", "adj. 相像的；adv. 相似地"),
      mk(8, 21, "word", "mirror", "/ˈmɪrər/", "n. 镜子"),
      mk(8, 21, "word", "interest", "/ˈɪntrəst/", "n. 业余爱好；兴趣；v. 使感兴趣"),
      mk(8, 21, "word", "novel", "/ˈnɑːvəl/", "n. 小说"),
      mk(8, 21, "word", "sense", "/sens/", "n. 理解力；感觉；v. 意识到；感觉到"),
      mk(8, 21, "word", "humour", "/ˈhjuːmər/", "(= humor) n. 幽默；幽默感"),
      mk(8, 21, "phrase", "thanks to", "/θæŋks tuː/", "归功于；由于；因为"),
      mk(8, 21, "word", "opinion", "/əˈpɪnjən/", "n. 看法；意见"),
      mk(8, 21, "phrase", "make a mistake", "/meɪk ə mɪˈsteɪk/", "犯错误"),
      mk(8, 21, "word", "less", "/les/", "adj. 较少的；更少的；adv. 较少地；更少地；pron. 较少；更少"),
      mk(8, 21, "word", "straightforward", "/ˌstreɪtˈfɔːrwərd/", "adj. 坦率的；简单的"),
      mk(8, 21, "word", "honest", "/ˈɑːnɪst/", "adj. 坦诚的；诚实的"),
      mk(8, 21, "word", "direct", "/dəˈrekt/", "adj. 笔直的；直接的"),
      mk(8, 21, "word", "similarity", "/ˌsɪməˈlærəti/", "n. 相似之处"),
      mk(8, 21, "word", "friendship", "/ˈfrendʃɪp/", "n. 友谊；友情"),
      mk(8, 21, "word", "metre", "/ˈmiːtər/", "(= meter) n. 米"),
      mk(8, 21, "word", "prince", "/prɪns/", "n. 王子"),
      mk(8, 21, "word", "character", "/ˈkærəktər/", "n. 人物；个性"),
      mk(8, 21, "word", "pauper", "/ˈpɔːpər/", "n. 贫民；乞丐"),
      mk(8, 21, "word", "exchange", "/ɪksˈtʃeɪndʒ/", "v. & n. 交换"),
      mk(8, 21, "word", "accident", "/ˈæksɪdənt/", "n. 意外；（交通）事故"),
      mk(8, 21, "phrase", "by accident", "/baɪ ˈæksɪdənt/", "偶然；意外地"),
      mk(8, 21, "word", "expect", "/ɪkˈspekt/", "v. 预料；期待"),
      mk(8, 21, "word", "silver", "/ˈsɪlvər/", "adj. 银色的；n. 银"),
      mk(8, 21, "word", "lining", "/ˈlaɪnɪŋ/", "n. 内衬"),
      mk(8, 21, "phrase", "silver lining", "/ˈsɪlvər ˈlaɪnɪŋ/", "一线光明"),
      mk(8, 21, "word", "situation", "/ˌsɪtʃuˈeɪʃən/", "n. 情况；状况"),
      mk(8, 21, "phrase", "care about", "/ker əˈbaʊt/", "关心；担心"),
      mk(8, 21, "word", "reach", "/riːtʃ/", "v. 伸手；到达"),
      mk(8, 21, "phrase", "reach for", "/riːtʃ fɔːr/", "伸手触碰"),
      mk(8, 21, "word", "touch", "/tʌtʃ/", "v. 触动；触碰"),
      mk(8, 21, "phrase", "lend (sb) a hand", "/lend (sʌmwʌn) ə hænd/", "帮助（某人）"),
      mk(8, 21, "word", "Julie", "/ˈdʒuːli/", "n. 朱莉"),
      mk(8, 21, "word", "Vancouver", "/vænˈkuːvər/", "n. 温哥华（加拿大大城市）"),
      mk(8, 21, "word", "Matt", "/mæt/", "n. 马特"),
      mk(8, 21, "word", "Stephen", "/ˈstiːvən/", "n. 斯蒂芬"),
      mk(8, 21, "word", "Diana", "/daɪˈænə/", "n. 戴安娜"),
      mk(8, 21, "word", "Edward", "/ˈedwərd/", "n. 爱德华"),
      mk(8, 21, "word", "Mark Twain", "/mɑːrk tweɪn/", "n. 马克·吐温"),
      mk(8, 21, "word", "Rose", "/roʊz/", "n. 罗斯"),
    ],
  },
  {
    grade: 8,
    unit: 22,
    title: "Amazing Plants and Animals 神奇的动植物",
    entries: [
      mk(8, 22, "word", "moss", "/mɔːs/", "n. 苔藓"),
      mk(8, 22, "word", "redwood", "/ˈredwʊd/", "n. 红杉；红木"),
      mk(8, 22, "word", "cheetah", "/ˈtʃiːtə/", "n. 猎豹"),
      mk(8, 22, "word", "folding", "/ˈfoʊldɪŋ/", "adj. 折叠式的；可折叠的"),
      mk(8, 22, "phrase", "folding fan", "/ˈfoʊldɪŋ fæn/", "折扇"),
      mk(8, 22, "word", "bamboo", "/ˌbæmˈbuː/", "n. 竹；竹子"),
      mk(8, 22, "word", "yeah", "/jeə/", "interj. 是的；对"),
      mk(8, 22, "word", "popular", "/ˈpɑːpjələr/", "adj. 受欢迎的；流行的"),
      mk(8, 22, "word", "goodness", "/ˈɡʊdnəs/", "n. 美德；善良"),
      mk(8, 22, "word", "tool", "/tuːl/", "n. 工具；手段"),
      mk(8, 22, "word", "actually", "/ˈæktʃuəli/", "adv. 实际上；居然"),
      mk(8, 22, "word", "shoot", "/ʃuːt/", "n. 幼苗；嫩芽；v. (shot) 开（枪）；射击"),
      mk(8, 22, "word", "appear", "/əˈpɪr/", "v. 出现；看来好像"),
      mk(8, 22, "phrase", "feel free (to do sth)", "/fiːl friː tu duː sʌmθɪŋ/", "可以随便做某事"),
      mk(8, 22, "word", "land", "/lænd/", "n. 陆地；土地；v. 降落；着陆"),
      mk(8, 22, "word", "African", "/ˈæfrɪkən/", "adj. 非洲的；非洲人的；n. 非洲人"),
      mk(8, 22, "word", "rose", "/roʊz/", "n. 玫瑰；蔷薇"),
      mk(8, 22, "word", "peony", "/ˈpiːəni/", "n. 牡丹；芍药"),
      mk(8, 22, "word", "lotus", "/ˈloʊtəs/", "n. 莲花"),
      mk(8, 22, "word", "butterfly", "/ˈbʌtərflaɪ/", "n. 蝴蝶"),
      mk(8, 22, "word", "wing", "/wɪŋ/", "n. 翅膀；翼"),
      mk(8, 22, "word", "frog", "/frɑːɡ/", "n. 蛙；青蛙"),
      mk(8, 22, "phrase", "up to", "/ʌp tuː/", "接近；直到"),
      mk(8, 22, "word", "weigh", "/weɪ/", "v. 有……重；称重量"),
      mk(8, 22, "word", "kg", "/kɪləɡræm/", "(= kilogram) 千克；公斤"),
      mk(8, 22, "word", "ginkgo", "/ˈɡɪŋkoʊ/", "n. 银杏"),
      mk(8, 22, "word", "believe", "/bɪˈliːv/", "v. 相信；认为有可能"),
      mk(8, 22, "word", "province", "/ˈprɑːvɪns/", "n. 省份"),
      mk(8, 22, "phrase", "take a walk", "/teɪk ə wɔːk/", "散步"),
      mk(8, 22, "word", "connect", "/kəˈnekt/", "v. 联想；连接"),
      mk(8, 22, "word", "connected", "/kəˈnektɪd/", "adj. 连接的；相关的"),
      mk(8, 22, "phrase", "be connected with / to", "/bi kəˈnektɪd wɪð/", "与……相连；与……有关联"),
      mk(8, 22, "word", "without", "/wɪˈðaʊt/", "prep. 没有；缺乏"),
      mk(8, 22, "word", "imagine", "/ɪˈmædʒɪn/", "v. 想象；猜想"),
      mk(8, 22, "word", "honey", "/ˈhʌni/", "n. 蜂蜜；（爱称）亲爱的"),
      mk(8, 22, "word", "disappointed", "/ˌdɪsəˈpɔɪntɪd/", "adj. 失望的；沮丧的"),
      mk(8, 22, "word", "connection", "/kəˈnekʃən/", "n. 联系；连接"),
      mk(8, 22, "word", "pollination", "/ˌpɑːləˈneɪʃən/", "n. 花粉"),
      mk(8, 22, "word", "pollen", "/ˈpɑːlən/", "n. 花粉"),
      mk(8, 22, "word", "action", "/ˈækʃən/", "n. 行动；行为"),
      mk(8, 22, "phrase", "in fact", "/ɪn fækt/", "确切地说；实际上"),
      mk(8, 22, "word", "per cent", "/pər sent/", "(= percent) n. 百分之……；adj. & adv. 每一百中"),
      mk(8, 22, "phrase", "for this reason", "/fɔːr ðɪs ˈriːzən/", "出于这个原因"),
      mk(8, 22, "word", "planet", "/ˈplænɪt/", "n. 行星"),
      mk(8, 22, "phrase", "in order to", "/ɪn ˈɔːrdər tu/", "为了；以便"),
      mk(8, 22, "word", "store", "/stɔːr/", "v. 贮存；存储；n. 百货商店；商店"),
      mk(8, 22, "word", "honeycomb", "/ˈhʌnikoʊm/", "n. 蜂巢"),
      mk(8, 22, "word", "communicate", "/kəˈmjuːnɪkeɪt/", "v. 交流；沟通"),
      mk(8, 22, "phrase", "play a part (in sth)", "/pleɪ ə pɑːrt ɪn sʌmθɪŋ/", "（在某事中）起作用；参与某事"),
      mk(8, 22, "word", "ecosystem", "/ˈiːkoʊˌsɪstəm/", "n. 生态系统"),
      mk(8, 22, "word", "protect", "/prəˈtekt/", "v. 保护；防护"),
      mk(8, 22, "word", "importance", "/ɪmˈpɔːrtəns/", "n. 重要性"),
      mk(8, 22, "word", "title", "/ˈtaɪtəl/", "n. 标题；题目；名称"),
      mk(8, 22, "word", "human", "/ˈhjuːmən/", "n. 人；adj. 人的；人类的"),
      mk(8, 22, "word", "ant", "/ænt/", "n. 蚂蚁"),
      mk(8, 22, "phrase", "be home to sb / sth", "/bi hoʊm tu/", "有……栖息；是……的家乡"),
      mk(8, 22, "word", "happiness", "/ˈhæpinəs/", "n. 幸福；快乐"),
      mk(8, 22, "word", "disappoint", "/ˌdɪsəˈpɔɪnt/", "v. 使失望；使破灭"),
      mk(8, 22, "word", "mushroom", "/ˈmʌʃruːm/", "n. 蘑菇；伞菌"),
      mk(8, 22, "word", "ton", "/tʌn/", "n. 吨"),
      mk(8, 22, "word", "role", "/roʊl/", "n. 作用；职能；角色"),
      mk(8, 22, "phrase", "play a role (in)", "/pleɪ ə roʊl ɪn/", "在……中发挥作用；扮演角色"),
      mk(8, 22, "word", "pea", "/piː/", "n. 豌豆"),
      mk(8, 22, "word", "climate", "/ˈklaɪmət/", "n. 气候"),
      mk(8, 22, "word", "ocean", "/ˈoʊʃən/", "n. 大海；海洋"),
      mk(8, 22, "word", "except", "/ɪkˈsept/", "prep. 除……之外；除了"),
      mk(8, 22, "word", "tiny", "/ˈtaɪni/", "adj. 极小的；微小的"),
      mk(8, 22, "word", "lively", "/ˈlaɪvli/", "adj. 精力充沛的；生机勃勃的"),
      mk(8, 22, "word", "the Arctic Ocean", "/ði ˈɑːrktɪk ˈoʊʃən/", "n. 北冰洋"),
      mk(8, 22, "word", "Billy", "/ˈbɪli/", "n. 比利"),
    ],
  },
  {
    grade: 8,
    unit: 23,
    title: "What a Delicious Meal! 多么美味的一餐！",
    entries: [
      mk(8, 23, "word", "pepper", "/ˈpepər/", "n. 胡椒粉；辣椒"),
      mk(8, 23, "phrase", "cut up", "/kʌt ʌp/", "切碎；剁碎"),
      mk(8, 23, "word", "mix", "/mɪks/", "v. (使) 混合；融合；调配；n. 混合；混杂；混合料"),
      mk(8, 23, "word", "bake", "/beɪk/", "v. 烘烤"),
      mk(8, 23, "word", "oven", "/ˈʌvən/", "n. 烤箱；烤炉"),
      mk(8, 23, "phrase", "pour sth into sth", "/pɔːr sʌmθɪŋ ˈɪntuː sʌmθɪŋ/", "将……倒入……"),
      mk(8, 23, "word", "flour", "/ˈflaʊər/", "n. 面粉"),
      mk(8, 23, "word", "boil", "/bɔɪl/", "v. 煮沸；烧开；n. 沸腾；沸点"),
      mk(8, 23, "word", "butter", "/ˈbʌtər/", "n. 黄油"),
      mk(8, 23, "word", "cheese", "/tʃiːz/", "n. 奶酪；干酪"),
      mk(8, 23, "phrase", "cut sth in / into sth", "/kʌt sʌmθɪŋ ɪntuː/", "将……切成……"),
      mk(8, 23, "word", "tablespoon", "/ˈteɪbəlspuːn/", "n. 一汤匙（的量）；餐匙；汤匙"),
      mk(8, 23, "word", "mash", "/mæʃ/", "v. 捣烂；捣碎"),
      mk(8, 23, "phrase", "mashed potatoes", "/mæʃt pəˈteɪtoʊz/", "土豆泥"),
      mk(8, 23, "word", "stir-fry", "/ˈstɜːrfraɪ/", "v. 翻炒；炒；煸"),
      mk(8, 23, "phrase", "do with", "/duː wɪð/", "处理"),
      mk(8, 23, "word", "bowl", "/boʊl/", "n. 碗；钵；盆"),
      mk(8, 23, "word", "heat", "/hiːt/", "v. 加热；变热；n. 热；温度；炎热天气"),
      mk(8, 23, "word", "oil", "/ɔɪl/", "n. 食用油；石油；燃油"),
      mk(8, 23, "word", "pan", "/pæn/", "n. 平底锅；烤盘"),
      mk(8, 23, "phrase", "put sth back", "/pʊt sʌmθɪŋ bæk/", "将……放回"),
      mk(8, 23, "phrase", "mix ... with ...", "/mɪks ... wɪð .../", "（使）……和……混合"),
      mk(8, 23, "word", "simple", "/ˈsɪmpəl/", "adj. 简单的；朴素的"),
      mk(8, 23, "word", "ingredient", "/ɪnˈɡriːdiənt/", "n. 食材；成分"),
      mk(8, 23, "word", "instruction", "/ɪnˈstrʌkʃən/", "n. (pl.) 用法说明；操作指南"),
      mk(8, 23, "phrase", "steamed fish", "/stiːmd fɪʃ/", "清蒸鱼"),
      mk(8, 23, "word", "sour", "/ˈsaʊər/", "adj. 酸的；有酸味的"),
      mk(8, 23, "phrase", "hot and sour soup", "/hɑːt ənd ˈsaʊər suːp/", "酸辣汤"),
      mk(8, 23, "word", "mess", "/mes/", "n. 脏乱；凌乱"),
      mk(8, 23, "word", "pretty", "/ˈprɪti/", "adj. 漂亮的；美丽的；adv. 相当；十分；非常"),
      mk(8, 23, "word", "Christmas", "/ˈkrɪsməs/", "n. 圣诞节"),
      mk(8, 23, "word", "pancake", "/ˈpænkeɪk/", "n. 烙饼；薄饼"),
      mk(8, 23, "word", "dream", "/driːm/", "n. 梦想；梦；v. (dreamt/dreamed) 做梦；梦见；梦想"),
      mk(8, 23, "word", "university", "/ˌjuːnɪˈvɜːrsəti/", "n. (综合性) 大学；高等学府"),
      mk(8, 23, "phrase", "go boating", "/ɡoʊ ˈboʊtɪŋ/", "去划船"),
      mk(8, 23, "word", "memory", "/ˈmeməri/", "n. 回忆；记忆"),
      mk(8, 23, "word", "visible", "/ˈvɪzəbəl/", "adj. 看得见的；可见的"),
      mk(8, 23, "phrase", "along with sb / sth", "/əˈlɔːŋ wɪð/", "除……以外（还）；与……同样地"),
      mk(8, 23, "word", "pumpkin", "/ˈpʌmpkɪn/", "n. 南瓜"),
      mk(8, 23, "word", "pie", "/paɪ/", "n. 果馅饼；肉馅饼"),
      mk(8, 23, "phrase", "warm up", "/wɔːrm ʌp/", "变暖和；（使）活跃起来；热身"),
      mk(8, 23, "word", "cinnamon", "/ˈsɪnəmən/", "n. 肉桂皮；桂皮香料"),
      mk(8, 23, "phrase", "fill ... with ...", "/fɪl wɪð/", "（使）充满；（使）填满"),
      mk(8, 23, "word", "sweetness", "/ˈswiːtnəs/", "n. 甜；芬芳；愉悦"),
      mk(8, 23, "word", "college", "/ˈkɑːlɪdʒ/", "n. 学院；大学"),
      mk(8, 23, "word", "host", "/hoʊst/", "n. 主人；东道主；v. 主办；主持（活动）"),
      mk(8, 23, "word", "hostess", "/ˈhoʊstəs/", "n. 女主人；女房东"),
      mk(8, 23, "word", "recipe", "/ˈresəpi/", "n. 食谱；烹饪法"),
      mk(8, 23, "word", "cream", "/kriːm/", "n. 奶油；护肤霜"),
      mk(8, 23, "word", "crust", "/krʌst/", "n. 糕饼酥皮；面包皮"),
      mk(8, 23, "word", "mixture", "/ˈmɪkstʃər/", "n. 混合物；结合体"),
      mk(8, 23, "word", "least", "/liːst/", "adv. & pron. 最小；最少"),
      mk(8, 23, "phrase", "at least", "/ət liːst/", "至少"),
      mk(8, 23, "word", "secret", "/ˈsiːkrət/", "n. 诀窍；秘密；adj. 秘密的；隐秘的"),
      mk(8, 23, "word", "according", "/əˈkɔːrdɪŋ/", "prep. 根据；依照"),
      mk(8, 23, "word", "whenever", "/wenˈevər/", "adv. & conj. 每当；在任何……的时候"),
      mk(8, 23, "word", "item", "/ˈaɪtəm/", "n. 项目；条"),
      mk(8, 23, "word", "spaghetti", "/spəˈɡeti/", "n. 意大利细面条"),
      mk(8, 23, "word", "spoon", "/spuːn/", "n. (= spoonful) 一勺的量；勺"),
      mk(8, 23, "word", "slice", "/slaɪs/", "n. 薄片；片；v. 把……切成薄片；切；割"),
      mk(8, 23, "word", "couple", "/ˈkʌpəl/", "n. 夫妻；情侣；两人"),
      mk(8, 23, "word", "island", "/ˈaɪlənd/", "n. 岛"),
      mk(8, 23, "word", "wife", "/waɪf/", "n. (pl wives) 妻子"),
      mk(8, 23, "word", "separate", "/ˈsepərət/", "adj. 单独的；分开的；v. (separate) 分开；（使）分离"),
      mk(8, 23, "word", "born", "/bɔːrn/", "v. 出生；出世；adj. 天生（有某方面才能的）"),
      mk(8, 23, "phrase", "one by one", "/wʌn baɪ wʌn/", "逐个地；逐一地"),
      mk(8, 23, "word", "Thanksgiving", "/ˈθæŋksˌɡɪvɪŋ/", "n. 感恩节"),
      mk(8, 23, "word", "Guoqiao Rice Noodles", "/ɡwoʊtʃjaʊ raɪs ˈnuːdlz/", "过桥米线"),
    ],
  },
  {
    grade: 8,
    unit: 24,
    title: "Plan for Yourself 为自己制定计划",
    entries: [
      mk(8, 24, "word", "yourself", "/jʊrˈself/", "pron. (pl yourselves) 你自己；您自己"),
      mk(8, 24, "word", "engineer", "/ˌendʒɪˈnɪr/", "n. 工程师；技师"),
      mk(8, 24, "word", "fashion", "/ˈfæʃən/", "n. 时装业；时尚"),
      mk(8, 24, "word", "designer", "/dɪˈzaɪnər/", "n. 设计师"),
      mk(8, 24, "word", "director", "/dəˈrektər/", "n. 导演；主任；董事"),
      mk(8, 24, "word", "musician", "/mjuˈzɪʃən/", "n. 音乐家；乐师"),
      mk(8, 24, "word", "fireman", "/ˈfaɪərmən/", "n. (pl firemen) 消防队员"),
      mk(8, 24, "word", "AI", "/ˌeɪ ˈaɪ/", "(= artificial intelligence) 人工智能"),
      mk(8, 24, "word", "essay", "/ˈeseɪ/", "n. 小品文；文章"),
      mk(8, 24, "word", "classic", "/ˈklæsɪk/", "n. 经典作品；名著；adj. 最优秀的；古典的"),
      mk(8, 24, "phrase", "keep on doing sth", "/kiːp ɑːn ˈduːɪŋ sʌmθɪŋ/", "继续做；反复做"),
      mk(8, 24, "phrase", "make sure", "/meɪk ʃʊr/", "确保；保证"),
      mk(8, 24, "phrase", "try one's best", "/traɪ wʌnz best/", "尽最大努力"),
      mk(8, 24, "word", "literature", "/ˈlɪtərətʃər/", "n. 文学；文献"),
      mk(8, 24, "word", "athlete", "/ˈæθliːt/", "n. 运动员"),
      mk(8, 24, "word", "photographer", "/fəˈtɑːɡrəfər/", "n. 摄影师；拍照者"),
      mk(8, 24, "word", "painter", "/ˈpeɪntər/", "n. 画家；油漆匠"),
      mk(8, 24, "word", "businessman", "/ˈbɪznəsmæn/", "n. 商业人士；企业家"),
      mk(8, 24, "word", "actress", "/ˈæktrəs/", "n. 女演员"),
      mk(8, 24, "word", "lawyer", "/ˈlɔːjər/", "n. 律师"),
      mk(8, 24, "word", "law", "/lɔː/", "n. 法律；法规"),
      mk(8, 24, "word", "bath", "/bæθ/", "n. 洗澡；浴缸"),
      mk(8, 24, "word", "miss", "/mɪs/", "v. 想念；错过"),
      mk(8, 24, "phrase", "be tired of", "/bi ˈtaɪərd əv/", "对……感到厌倦"),
      mk(8, 24, "word", "able", "/ˈeɪbəl/", "adj. 能够；有才能的"),
      mk(8, 24, "word", "stick", "/stɪk/", "v. (stuck) 粘贴；将……刺入；n. 枝条；棍"),
      mk(8, 24, "phrase", "stick to sth", "/stɪk tu/", "坚持；维持"),
      mk(8, 24, "word", "resolution", "/ˌrezəˈluːʃən/", "n. 决定；决议"),
      mk(8, 24, "phrase", "have (...) to do with sb / sth", "/hæv tu duː wɪð/", "与……有关系"),
      mk(8, 24, "word", "mini-goal", "/ˈmɪni ɡoʊl/", "n. 小目标"),
      mk(8, 24, "word", "achieve", "/əˈtʃiːv/", "v. (经过努力) 达到；完成"),
      mk(8, 24, "word", "physical", "/ˈfɪzɪkəl/", "adj. 身体的；物质的"),
      mk(8, 24, "word", "health", "/helθ/", "n. 健康"),
      mk(8, 24, "word", "healthily", "/ˈhelθəli/", "adv. 健康地"),
      mk(8, 24, "phrase", "take up", "/teɪk ʌp/", "开始学；开始从事"),
      mk(8, 24, "word", "photography", "/fəˈtɑːɡrəfi/", "n. 照相术；摄影"),
      mk(8, 24, "word", "self-improvement", "/ˌself ɪmˈpruːvmənt/", "n. 自我改进；自我提高"),
      mk(8, 24, "word", "confident", "/ˈkɑːnfɪdənt/", "adj. 自信的；肯定的"),
      mk(8, 24, "word", "organized", "/ˈɔːrɡənaɪzd/", "(= organised) adj. 有条理的；有组织的"),
      mk(8, 24, "word", "wisely", "/ˈwaɪzli/", "adv. 聪明地；明智地"),
      mk(8, 24, "word", "possible", "/ˈpɑːsəbəl/", "adj. 可能的；合理的"),
      mk(8, 24, "word", "paragraph", "/ˈpærəɡræf/", "n. 段；段落"),
      mk(8, 24, "word", "introduce", "/ˌɪntrəˈduːs/", "v. 介绍；引见；引进"),
      mk(8, 24, "word", "meaning", "/ˈmiːnɪŋ/", "n. 意义；含义"),
      mk(8, 24, "word", "fail", "/feɪl/", "v. 未能（做到）；失败"),
      mk(8, 24, "word", "ahead", "/əˈhed/", "adv. 提前；在前面"),
      mk(8, 24, "phrase", "put out", "/pʊt aʊt/", "扑灭；把……熄好"),
      mk(8, 24, "word", "design", "/dɪˈzaɪn/", "v. 设计；计划；n. 设计；花纹"),
      mk(8, 24, "word", "bridge", "/brɪdʒ/", "n. 桥"),
      mk(8, 24, "word", "final", "/ˈfaɪnəl/", "adj. 最后的；最终的；n. 决赛"),
      mk(8, 24, "word", "confidence", "/ˈkɑːnfɪdəns/", "n. 信心；信任"),
      mk(8, 24, "phrase", "find out", "/faɪnd aʊt/", "查明；弄清（情况）"),
      mk(8, 24, "phrase", "draw to a close", "/drɔː tu ə kloʊz/", "即将结束；即将完成"),
      mk(8, 24, "word", "form", "/fɔːrm/", "v. (使) 形成；组成；n. 类型；形式；表格"),
      mk(8, 24, "word", "relationship", "/rɪˈleɪʃənʃɪp/", "n. 关系；联系"),
      mk(8, 24, "word", "push-up", "/ˈpʊʃʌp/", "n. 俯卧撑"),
      mk(8, 24, "word", "energetic", "/ˌenərˈdʒetɪk/", "adj. 精力充沛的；充满活力的"),
      mk(8, 24, "phrase", "last but not least", "/læst bʌt nɑːt liːst/", "最后但同等重要的"),
      mk(8, 24, "word", "Jason", "/ˈdʒeɪsən/", "n. 贾森"),
      mk(8, 24, "word", "Tina", "/ˈtiːnə/", "n. 蒂娜"),
    ],
  },
  {
    grade: 8,
    unit: 25,
    title: "When Tomorrow Comes 当明天到来",
    entries: [
      mk(8, 25, "word", "prediction", "/prɪˈdɪkʃən/", "n. 预测；预言"),
      mk(8, 25, "word", "outer", "/ˈaʊtər/", "adj. 外面的；外表的"),
      mk(8, 25, "phrase", "outer space", "/ˈaʊtər speɪs/", "太空；外层空间"),
      mk(8, 25, "word", "worse", "/wɜːrs/", "adj. (bad 的比较级) 更差的；更糟的；更坏的；adv. (badly 的比较级) 更差；更糟；更坏"),
      mk(8, 25, "phrase", "take over", "/teɪk ˈoʊvər/", "接管；接收"),
      mk(8, 25, "word", "sci-fi", "/ˈsaɪ faɪ/", "(= science fiction) 科幻小说（或影片等）"),
      mk(8, 25, "word", "ticket", "/ˈtɪkɪt/", "n. 票；券"),
      mk(8, 25, "word", "positive", "/ˈpɑːzətɪv/", "adj. 乐观的；积极的；良好的"),
      mk(8, 25, "word", "traffic", "/ˈtræfɪk/", "n. 交通；运输；v. (非法) 进行交易；做……买卖"),
      mk(8, 25, "word", "technology", "/tekˈnɑːlədʒi/", "n. 科技；工艺"),
      mk(8, 25, "word", "video", "/ˈvɪdioʊ/", "n. 视频；录像系统；v. 录视频；给……录像"),
      mk(8, 25, "word", "transport", "/ˈtrænspɔːrt/", "n. 交通运输系统；旅行方式；v. (transport) 运输；运送"),
      mk(8, 25, "word", "system", "/ˈsɪstəm/", "n. 系统"),
      mk(8, 25, "word", "efficient", "/ɪˈfɪʃənt/", "adj. 效率高的；有功效的"),
      mk(8, 25, "word", "education", "/ˌedʒuˈkeɪʃən/", "n. 教育"),
      mk(8, 25, "word", "length", "/leŋθ/", "n. 时长；长度"),
      mk(8, 25, "word", "topic", "/ˈtɑːpɪk/", "n. 话题；题目；标题"),
      mk(8, 25, "word", "partner", "/ˈpɑːrtnər/", "n. 搭档；同伴"),
      mk(8, 25, "word", "shall", "/ʃæl/", "modal v. (should) 将要；将会"),
      mk(8, 25, "phrase", "Shall I / we ...?", "/ʃæl aɪ wiː/", "……好吗？要不要……？？（用于提出意见或征求意见）"),
      mk(8, 25, "word", "pass", "/pæs/", "v. 及格；通过"),
      mk(8, 25, "word", "winner", "/ˈwɪnər/", "n. 优胜者；成功者"),
      mk(8, 25, "word", "cure", "/kjʊr/", "n. 药物；疗法；v. 治愈；治好"),
      mk(8, 25, "word", "cancer", "/ˈkænsər/", "n. 癌症"),
      mk(8, 25, "word", "concert", "/ˈkɑːnsərt/", "n. 音乐会；演奏会"),
      mk(8, 25, "word", "cash", "/kæʃ/", "n. 现金；金钱；v. 兑现"),
      mk(8, 25, "word", "wallet", "/ˈwɑːlɪt/", "n. 钱包；皮夹"),
      mk(8, 25, "word", "guest", "/ɡest/", "n. 客人；宾客"),
      mk(8, 25, "word", "chief", "/tʃiːf/", "adj. 首席的；最主要的；n. 首领；首长"),
      mk(8, 25, "word", "researcher", "/rɪˈsɜːrtʃər/", "n. 研究者；探索者"),
      mk(8, 25, "word", "research", "/rɪˈsɜːrtʃ/", "n. & v. 研究；调查"),
      mk(8, 25, "word", "futurist", "/ˈfjuːtʃərɪst/", "n. 未来学家"),
      mk(8, 25, "word", "everywhere", "/ˈevriwer/", "adv., pron. & conj. 到处；所有地方"),
      mk(8, 25, "word", "robotics", "/roʊˈbɑːtɪks/", "n. 机器入学"),
      mk(8, 25, "word", "industry", "/ˈɪndəstri/", "n. 行业；工业"),
      mk(8, 25, "word", "service", "/ˈsɜːrvɪs/", "n. 服务；公共服务"),
      mk(8, 25, "word", "disaster", "/dɪˈzæstər/", "n. 灾难；不幸"),
      mk(8, 25, "word", "emergency", "/iˈmɜːrdʒənsi/", "n. 突发事件；紧急情况"),
      mk(8, 25, "word", "disappear", "/ˌdɪsəˈper/", "v. 消失；不见"),
      mk(8, 25, "word", "challenging", "/ˈtʃælɪndʒɪŋ/", "adj. 挑战性的"),
      mk(8, 25, "word", "pilot", "/ˈpaɪlət/", "n. 飞行员；领航员"),
      mk(8, 25, "word", "expert", "/ˈekspɜːrt/", "n. 专家；行家；adj. 熟练的；内行的"),
      mk(8, 25, "word", "replace", "/rɪˈpleɪs/", "v. 代替；取代"),
      mk(8, 25, "word", "creativity", "/ˌkriːeɪˈtɪvəti/", "n. 创造力"),
      mk(8, 25, "word", "emotional", "/iˈmoʊʃənəl/", "adj. 情感的；情绪的"),
      mk(8, 25, "word", "intelligence", "/ɪnˈtelɪdʒəns/", "n. 智力；智慧"),
      mk(8, 25, "phrase", "emotional intelligence", "/iˈmoʊʃənəl ɪnˈtelɪdʒəns/", "情绪智力"),
      mk(8, 25, "word", "mention", "/ˈmenʃən/", "v. 提到；写到"),
      mk(8, 25, "word", "refrigerator", "/rɪˈfrɪdʒəreɪtər/", "(= fridge) n. 冰箱"),
      mk(8, 25, "word", "low", "/loʊ/", "adj. 向……底部；低；adj. 低的；矮的"),
      mk(8, 25, "phrase", "run low (on sth)", "/rʌn loʊ/", "即将用尽；快用完"),
      mk(8, 25, "word", "accept", "/əkˈsept/", "v. 接受；相信"),
      mk(8, 25, "word", "influence", "/ˈɪnfluəns/", "n. 影响；作用；v. 对……起作用"),
      mk(8, 25, "word", "creative", "/kriˈeɪtɪv/", "adj. 创造性的；创作的"),
      mk(8, 25, "word", "impossible", "/ɪmˈpɑːsəbəl/", "adj. 不可能的"),
      mk(8, 25, "word", "quality", "/ˈkwɑːləti/", "n. 素质；质量；品质；adj. 优质的；高质量的"),
      mk(8, 25, "word", "develop", "/dɪˈveləp/", "v. 增强；发展；开发"),
      mk(8, 25, "word", "German", "/ˈdʒɜːrmən/", "n. 德语；德国人；adj. 德国的"),
      mk(8, 25, "word", "valuable", "/ˈvæljuəbəl/", "adj. 很有用的；宝贵的"),
      mk(8, 25, "word", "public", "/ˈpʌblɪk/", "adj. 公共的；公众的"),
      mk(8, 25, "word", "medical", "/ˈmedɪkəl/", "adj. 医学的；医疗的"),
      mk(8, 25, "word", "challenge", "/ˈtʃælɪndʒ/", "n. 挑战；质疑；v. 向（某人）挑战；对……怀疑"),
      mk(8, 25, "word", "task", "/tæsk/", "n. 任务；工作"),
      mk(8, 25, "word", "depend", "/dɪˈpend/", "v. 取决于；依靠"),
      mk(8, 25, "phrase", "depend on / upon", "/dɪˈpend ɑːn/", "取决于；依靠"),
      mk(8, 25, "phrase", "come over", "/kʌm ˈoʊvər/", "来访；拜访"),
      mk(8, 25, "phrase", "come true", "/kʌm truː/", "实现"),
      mk(8, 25, "phrase", "as long as", "/æz lɔːŋ æz/", "只要"),
      mk(8, 25, "word", "Jennifer", "/ˈdʒenɪfər/", "n. 珍妮弗"),
      mk(8, 25, "word", "Harry", "/ˈhæri/", "n. 哈利"),
      mk(8, 25, "word", "Asimov", "/ˈæzɪmɑːf/", "n. 阿西莫夫"),
      mk(8, 25, "word", "France", "/fræns/", "n. 法国"),
      mk(8, 25, "word", "Mandy", "/ˈmændi/", "n. 曼迪"),
    ],
  },
  {
    grade: 8,
    unit: 26,
    title: "Let's Communicate! 让我们交流吧！",
    entries: [
      mk(8, 26, "word", "communication", "/kəˌmjuːnɪˈkeɪʃən/", "n. 表达；交流"),
      mk(8, 26, "phrase", "face to face", "/feɪs tu feɪs/", "面对面"),
      mk(8, 26, "phrase", "text message", "/tekst ˈmesɪdʒ/", "(手机) 短信息；短信"),
      mk(8, 26, "word", "sign", "/saɪn/", "n. 手势；迹象；标志；v. 签（名）；签字"),
      mk(8, 26, "word", "speaker", "/ˈspiːkər/", "n. 说话者；发言者"),
      mk(8, 26, "word", "rehearsal", "/rɪˈhɜːrsəl/", "n. 排演；排练"),
      mk(8, 26, "phrase", "show sb around", "/ʃoʊ sʌmwʌn əˈraʊnd/", "领某人参观"),
      mk(8, 26, "word", "local", "/ˈloʊkəl/", "adj. 当地的；地方的；n. 当地产；本地人"),
      mk(8, 26, "word", "face-to-face", "/ˌfeɪs tu feɪs/", "adj. 对面的"),
      mk(8, 26, "word", "professor", "/prəˈfesər/", "n. 教授"),
      mk(8, 26, "word", "speech", "/spiːtʃ/", "n. 演说；发言"),
      mk(8, 26, "word", "argue", "/ˈɑːrɡjuː/", "v. 争论；争吵"),
      mk(8, 26, "phrase", "make up (with sb)", "/meɪk ʌp wɪð/", "与……言归于好"),
      mk(8, 26, "phrase", "in person", "/ɪn ˈpɜːrsən/", "亲自；亲身"),
      mk(8, 26, "word", "prefer", "/prɪˈfɜːr/", "v. 较喜欢"),
      mk(8, 26, "word", "calm", "/kɑːm/", "adj. 镇静的；沉着的；v. 使平静；使镇静"),
      mk(8, 26, "phrase", "worry about", "/ˈwɜːri əˈbaʊt/", "为……担心"),
      mk(8, 26, "word", "expression", "/ɪkˈspreʃən/", "n. 表达方式；表达"),
      mk(8, 26, "word", "chance", "/tʃæns/", "n. 机会；可能性；adj. 意外的；偶然的"),
      mk(8, 26, "word", "meeting", "/ˈmiːtɪŋ/", "n. 会面；会议"),
      mk(8, 26, "word", "difficulty", "/ˈdɪfɪkəlti/", "n. 困难；难题"),
      mk(8, 26, "word", "right away", "/raɪt əˈweɪ/", "立即；马上"),
      mk(8, 26, "word", "line", "/laɪn/", "n. 字行；便条；线"),
      mk(8, 26, "phrase", "drop sb a line", "/drɑːp sʌmwʌn ə laɪn/", "给……写信"),
      mk(8, 26, "word", "detail", "/ˈdiːteɪl/", "n. 细节；详情"),
      mk(8, 26, "word", "reunion", "/riːˈjuːnjən/", "n. 团聚；重逢；聚会"),
      mk(8, 26, "word", "seriously", "/ˈsɪriəsli/", "adv. 严重地；认真地"),
      mk(8, 26, "word", "training", "/ˈtreɪnɪŋ/", "n. 训练；培训"),
      mk(8, 26, "word", "nervous", "/ˈnɜːrvəs/", "adj. 担忧的；焦虑的；胆怯的"),
      mk(8, 26, "word", "stranger", "/ˈstreɪndʒər/", "n. 陌生人"),
      mk(8, 26, "word", "tip", "/tɪp/", "n. 指点；实用的提示；尖端；v. (使) 倾斜；使倾斜；给小费"),
      mk(8, 26, "word", "carefully", "/ˈkerfəli/", "adv. 认真地；仔细地；小心地"),
      mk(8, 26, "phrase", "show interest in sth", "/ʃoʊ ˈɪntrəst ɪn sʌmθɪŋ/", "对……表现出兴趣"),
      mk(8, 26, "word", "listener", "/ˈlɪsənər/", "n. 听者"),
      mk(8, 26, "word", "point", "/pɔɪnt/", "n. 观点；重点；v. 指向；瞄准"),
      mk(8, 26, "word", "surely", "/ˈʃʊrli/", "adv. 想必；必定"),
      mk(8, 26, "word", "continue", "/kənˈtɪnjuː/", "v. 持续；继续做"),
      mk(8, 26, "word", "impolite", "/ˌɪmpəˈlaɪt/", "adj. 不礼貌的；粗鲁的"),
      mk(8, 26, "word", "personal", "/ˈpɜːrsənəl/", "adj. 个人的；私人的"),
      mk(8, 26, "phrase", "argue with sb", "/ˈɑːrɡjuː wɪð/", "与某人争论"),
      mk(8, 26, "phrase", "move on (to sth)", "/muːv ɑːn/", "换话题；开始做（别的事）"),
      mk(8, 26, "word", "sincere", "/sɪnˈsɪr/", "adj. 真诚的；诚挚的"),
      mk(8, 26, "word", "pay", "/peɪ/", "v. (paid) 付费；交纳；偿还；n. 工资；薪水"),
      mk(8, 26, "word", "attention", "/əˈtenʃən/", "n. 注意；专心；关注"),
      mk(8, 26, "phrase", "pay attention (to ...)", "/peɪ əˈtenʃən tu/", "注意；关注"),
      mk(8, 26, "phrase", "be yourself", "/bi jʊrˈself/", "行为自然；不做作"),
      mk(8, 26, "word", "offer", "/ˈɔːfər/", "v. 提供；主动提出；n. 主动提议；出价"),
      mk(8, 26, "word", "reasonable", "/ˈriːzənəbəl/", "adj. 公平的；合理的"),
      mk(8, 26, "word", "social", "/ˈsoʊʃəl/", "adj. 社会的；社交的；n. 联谊会；联欢会"),
      mk(8, 26, "word", "medium", "/ˈmiːdiəm/", "n. (pl media) 媒介；手段；adj. 中等的；适中的"),
      mk(8, 26, "phrase", "social media", "/ˈsoʊʃəl ˈmiːdiə/", "社交媒体"),
      mk(8, 26, "word", "trust", "/trʌst/", "n. & v. 信任；相信"),
      mk(8, 26, "phrase", "keep (...) away from ...", "/kiːp əˈweɪ frəm/", "（使）远离；避免……靠近"),
      mk(8, 26, "word", "misunderstanding", "/ˌmɪsʌndərˈstændɪŋ/", "n. 误解；误会"),
      mk(8, 26, "word", "event", "/ɪˈvent/", "n. 公开活动；重要事情"),
      mk(8, 26, "phrase", "take place", "/teɪk pleɪs/", "发生；进行"),
      mk(8, 26, "word", "cost", "/kɔːst/", "n. 费用；价钱；代价；v. 价格为；使损失；使付出努力"),
      mk(8, 26, "word", "opportunity", "/ˌɑːpərˈtuːnəti/", "n. 机会；时机"),
      mk(8, 26, "word", "benefit", "/ˈbenɪfɪt/", "v. 对……有用；使受益；n. 益处；成效"),
      mk(8, 26, "phrase", "benefit from ...", "/ˈbenɪfɪt frəm/", "从……获益"),
      mk(8, 26, "word", "reply", "/rɪˈplaɪ/", "n. & v. 回答；回复"),
      mk(8, 26, "word", "honour", "/ˈɑːnər/", "(= honor) n. 荣幸；尊敬；v. 给……荣幸；表彰"),
      mk(8, 26, "word", "sincerely", "/sɪnˈsɪrli/", "adv. 真诚地；诚挚地"),
      mk(8, 26, "word", "opening", "/ˈoʊpənɪŋ/", "adj. 开幕的；开始的；n. 开始；孔；洞"),
      mk(8, 26, "word", "closing", "/ˈkloʊzɪŋ/", "adj. 结尾的；结束的；n. 停业；关闭"),
      mk(8, 26, "word", "sentence", "/ˈsentəns/", "n. 句子；判决；v. 判决；宣判"),
      mk(8, 26, "word", "date", "/deɪt/", "n. 日期；日子；约会；v. 确定年代；注明日期"),
      mk(8, 26, "word", "clause", "/klɔːz/", "n. 从句；分句"),
      mk(8, 26, "word", "Susan", "/ˈsuːzən/", "n. 苏珊"),
      mk(8, 26, "word", "Jones", "/dʒoʊnz/", "n. 琼斯"),
    ],
  },
` + OLD_END_MARK;

const src = fs.readFileSync(FILE, 'utf8');
const startIdx = src.indexOf(OLD_START_MARK);
if (startIdx === -1) { console.error('OLD_START_MARK not found'); process.exit(1); }
const endIdx = src.indexOf(OLD_END_MARK, startIdx);
if (endIdx === -1) { console.error('OLD_END_MARK not found'); process.exit(1); }

const before = src.slice(0, startIdx);
const after = src.slice(endIdx + OLD_END_MARK.length);
const next = before + NEW_BLOCK + after;
fs.writeFileSync(FILE, next);
console.log('patched. before chars:', before.length, '/ after chars:', after.length, '/ total delta:', next.length - src.length);